//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <XDInterface/NSAnimationDelegate-Protocol.h>
#import <XDInterface/NSWindowDelegate-Protocol.h>

@class NSString, XDBezelWidgetPanel, XDBezelWidgetView;

@interface XDBezelWidgetManager : NSObject <NSWindowDelegate, NSAnimationDelegate>
{
    struct __CFRunLoopTimer *_bezelWidgetTimer;
    XDBezelWidgetView *_bezelWidgetView;
    XDBezelWidgetPanel *_bezelWidgetPanel;
}

+ (Class)_sharedBezelWidgetManagerClass;
+ (void)initialize;
+ (id)sharedBezelWidgetManager;
+ (BOOL)sharedBezelWidgetManagerExists;
- (void)_createBezelWidgetTimer;
- (void)_destroyBezelWidgetTimer;
- (void)animationDidEnd:(id)arg1;
- (id)bezelWidgetView;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (BOOL)isBezelWidgetVisible;
- (void)orderFrontBezelWidgetForView:(id)arg1;
- (void)orderOutBezelWidget;
- (void)windowDidResignKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

