//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDInterface/XDComponentManager.h>

@interface XDShapeManager : XDComponentManager
{
}

+ (Class)_sharedShapeManagerClass;
+ (void)initialize;
+ (void)registerShape:(id)arg1;
+ (id)registeredShapes;
+ (id)sharedShapeManager;
+ (BOOL)sharedShapeManagerExists;
+ (void)unregisterShape:(id)arg1;
- (id)componentWithIdentifier:(id)arg1;

@end

