//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class IDESourceControlWorkingCopyCreationChooserWindowController, NSButton;

@interface DVTProjectWorkingCopyTableCellView : NSTableCellView
{
    IDESourceControlWorkingCopyCreationChooserWindowController *_windowController;
    NSButton *_checkBox;
}

@property NSButton *checkBox; // @synthesize checkBox=_checkBox;
- (void)checkBox:(id)arg1;
@property IDESourceControlWorkingCopyCreationChooserWindowController *windowController; // @synthesize windowController=_windowController;

@end

