//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import <IDEKit/IDEAccountDetailsRefresherDelegate-Protocol.h>

@class DVTBorderedView, DVTTableView, IDEAccountDetailsRefresher, NSArrayController, NSImageView, NSObjectController, NSSet, NSView;

@interface IDEAccountPrefsDeveloperAccountDetailViewController : IDEViewController <IDEAccountDetailsRefresherDelegate>
{
    NSObjectController *_objectController;
    NSArrayController *_teamDescriptionsArrayController;
    NSSet *_teamDescriptions;
    DVTTableView *_teamsTable;
    NSImageView *_imageView;
    DVTBorderedView *_borderedView;
    NSView *_credentialsView;
    NSView *_passwordView;
    NSView *_tokenView;
    NSImageView *_errorImageView1;
    NSImageView *_errorImageView2;
    IDEAccountDetailsRefresher *_refresher;
}

+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (id)keyPathsForValuesAffectingDeveloperAccount;
+ (id)keyPathsForValuesAffectingPassword;
+ (id)keyPathsForValuesAffectingUserDescription;
- (void).cxx_destruct;
- (void)_refreshUI;
@property(retain) DVTBorderedView *borderedView; // @synthesize borderedView=_borderedView;
- (id)contextMenu;
@property __weak NSView *credentialsView; // @synthesize credentialsView=_credentialsView;
- (id)developerAccount;
@property __weak NSImageView *errorImageView1; // @synthesize errorImageView1=_errorImageView1;
@property __weak NSImageView *errorImageView2; // @synthesize errorImageView2=_errorImageView2;
@property(retain) NSImageView *imageView; // @synthesize imageView=_imageView;
@property __weak NSObjectController *objectController; // @synthesize objectController=_objectController;
- (id)password;
@property(retain) NSView *passwordView; // @synthesize passwordView=_passwordView;
- (void)primitiveInvalidate;
@property(retain, nonatomic) IDEAccountDetailsRefresher *refresher; // @synthesize refresher=_refresher;
- (void)refresherDidFail:(id)arg1;
- (void)refresherDidFinishWithTeamDescriptions:(id)arg1;
- (void)setPassword:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
@property(copy, nonatomic) NSSet *teamDescriptions; // @synthesize teamDescriptions=_teamDescriptions;
@property(retain, nonatomic) NSArrayController *teamDescriptionsArrayController; // @synthesize teamDescriptionsArrayController=_teamDescriptionsArrayController;
@property(retain) DVTTableView *teamsTable; // @synthesize teamsTable=_teamsTable;
@property(retain) NSView *tokenView; // @synthesize tokenView=_tokenView;
- (void)setUserDescription:(id)arg1;
- (void)signInAgain:(id)arg1;
- (void)tableViewDoubleClicked:(id)arg1;
- (id)userDescription;
- (void)viewDetails:(id)arg1;
- (void)viewDetailsForTeam:(id)arg1;
- (void)viewDidInstall;

@end

