//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class DVTBorderedView, IDEAssistant, IDEAssistantContext, IDEFilterControlBar, NSBox, NSButton, NSMutableArray, NSString, NSTextField, NSView;

@interface IDEAssistantWindowController : NSWindowController
{
    NSBox *_box;
    DVTBorderedView *_outerBorderedView;
    DVTBorderedView *_borderedView;
    DVTBorderedView *_sourceListBorderedView;
    NSButton *_nextButton;
    NSButton *_backButton;
    NSButton *_cancelButton;
    NSTextField *_titleField;
    IDEFilterControlBar *_filterControlBar;
    NSButton *_helpButton;
    IDEAssistant *_installedAssistant;
    CDUnknownBlockType _currentCompletionBlock;
    NSMutableArray *_assistantHistory;
    NSMutableArray *_allAnimations;
    NSView *_nextKeyView;
    double _lastAnimationDirection;
    _Bool _backtrackingFromOverlayAssistant;
    _Bool _closing;
    BOOL _preventGoNextOrFinish;
    IDEAssistant *_currentAssistant;
    IDEAssistantContext *_assistantContext;
    NSString *_nextButtonTitle;
    NSString *_finishButtonTitle;
    NSMutableArray *_completionPreprocessors;
    NSMutableArray *_completionPreprocessorExecutionStack;
}

+ (id)keyPathsForValuesAffectingAssistantTitle;
+ (id)keyPathsForValuesAffectingCanCancel;
+ (id)keyPathsForValuesAffectingCanGoForwardOrFinish;
+ (id)keyPathsForValuesAffectingForwardOrFinishButtonTitle;
+ (id)keyPathsForValuesAffectingOnFirstAssistant;
- (void).cxx_destruct;
- (void)_clearAssistantHistoryStack;
- (void)_finishWithAction:(id)arg1;
- (id)_popAssistantHistoryStack;
- (id)_popAssistantHistoryStackToIdentifier:(id)arg1;
- (void)_pushAssistantOntoHistoryStack:(id)arg1;
- (void)addAnimationForKey:(id)arg1 toView:(id)arg2;
- (void)addGoForwardPreprocessor:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) IDEAssistantContext *assistantContext; // @synthesize assistantContext=_assistantContext;
- (id)assistantTitle;
- (id)assistantWithIdentifier:(id)arg1;
- (void)beginSessionForWorkspaceWindow:(id)arg1;
- (void)beginSessionWithAssistantIdentifier:(id)arg1 context:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (BOOL)canCancel;
- (BOOL)canGoBack;
- (BOOL)canGoForwardOrFinish;
- (void)cancelSession;
- (void)close;
@property(retain, nonatomic) NSMutableArray *completionPreprocessorExecutionStack; // @synthesize completionPreprocessorExecutionStack=_completionPreprocessorExecutionStack;
@property(retain, nonatomic) NSMutableArray *completionPreprocessors; // @synthesize completionPreprocessors=_completionPreprocessors;
- (void)configureAnimationImageViewWithDirection:(double)arg1 actionBlock:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) IDEAssistant *currentAssistant; // @synthesize currentAssistant=_currentAssistant;
- (void)didInstallViewController:(id)arg1;
- (void)drainPreprocessorOrContinueWithSender:(id)arg1;
- (void)endAssistantSessionWithResult:(int)arg1 error:(id)arg2;
@property(retain, nonatomic) NSString *finishButtonTitle; // @synthesize finishButtonTitle=_finishButtonTitle;
- (id)forwardOrFinishButtonTitle;
- (void)goBack:(id)arg1;
- (void)goNextOrFinish:(id)arg1;
- (void)helpAction:(id)arg1;
- (id)init;
@property(retain, nonatomic) NSString *nextButtonTitle; // @synthesize nextButtonTitle=_nextButtonTitle;
- (BOOL)onFirstAssistant;
@property(nonatomic) BOOL preventGoNextOrFinish; // @synthesize preventGoNextOrFinish=_preventGoNextOrFinish;
- (void)setCurrentAssistant:(id)arg1;
- (void)setCurrentAssistant:(id)arg1 andInstallView:(BOOL)arg2;
- (void)setupAccessoriesForAssistant:(id)arg1 animated:(BOOL)arg2;
- (id)skipAheadIfPossibleAndReturnAssistantIdentifier;
- (void)willInstallViewController:(id)arg1;
- (void)windowDidLoad;
- (void)windowWillClose:(id)arg1;

@end

