//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEBatchFindScopeRuleRow.h>

@class NSArray, NSString, NSTextField;

@interface IDEBatchFindScopeSourceControlStatusRow : IDEBatchFindScopeRuleRow
{
    NSArray *_displayValues;
    NSArray *_predicateValues;
    NSTextField *_textField;
}

+ (id)_displayStringForComparisonType:(unsigned long long)arg1;
- (void).cxx_destruct;
- (unsigned long long)_operatorTypeForComparisonAtIndex:(long long)arg1;
- (long long)childCountForIndexPath:(id)arg1;
@property(readonly) NSArray *comparisonDisplayValues;
@property(readonly) NSArray *comparisonPredicateValues;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)criteriaNodesForMatchingPredicate:(id)arg1;
- (id)displayValueForPath:(id)arg1;
- (unsigned long long)hash;
- (id)initWithLHSDisplayValue:(id)arg1 lhsPredicateValue:(id)arg2 andComparisonTypes:(id)arg3;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSString *lhsDisplayValue;
@property(readonly) NSString *lhsPredicateValue;
- (id)predicateForIndexPath:(id)arg1;
- (void)setError:(BOOL)arg1;
@property(readonly) NSTextField *textField; // @synthesize textField=_textField;

@end

