//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class DVTFindDescriptor, IDEBatchFindCandidateFile, IDEWorkspace, NSArray, NSError;

@interface IDEBatchFindable : NSOperation
{
    NSArray *_findResults;
    DVTFindDescriptor *_findDescriptor;
    IDEBatchFindCandidateFile *_file;
    NSError *_error;
    IDEWorkspace *_workspace;
}

+ (BOOL)findableCanHandleFile:(id)arg1 forFindDescriptor:(id)arg2;
+ (id)findableForFindDescriptor:(id)arg1 onFile:(id)arg2 inWorkspace:(id)arg3;
- (void).cxx_destruct;
@property(copy) NSError *error; // @synthesize error=_error;
@property(readonly) IDEBatchFindCandidateFile *file; // @synthesize file=_file;
@property(readonly) DVTFindDescriptor *findDescriptor; // @synthesize findDescriptor=_findDescriptor;
@property(readonly) NSArray *findResults; // @synthesize findResults=_findResults;
- (id)initWithFindDescriptor:(id)arg1 onFile:(id)arg2 inWorkspace:(id)arg3;
@property(readonly) BOOL requiresMainThreadAccess;
- (void)setDVTFindResults:(id)arg1;
@property(readonly) BOOL shouldFallbackToDocumentFindable;
@property(readonly) IDEWorkspace *workspace; // @synthesize workspace=_workspace;

@end

