//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

@class NSArray, NSPopUpButton;
@protocol ITunesSoftwareApplicationDescription;

@interface IDEDistributionAppRecordSelectionViewController : IDEViewController
{
    NSArray *_applicationRecords;
    id <ITunesSoftwareApplicationDescription> _selectedApplicationRecord;
    NSPopUpButton *_appRecordPopUpButton;
}

- (void).cxx_destruct;
@property(retain) NSPopUpButton *appRecordPopUpButton; // @synthesize appRecordPopUpButton=_appRecordPopUpButton;
@property(retain) NSArray *applicationRecords; // @synthesize applicationRecords=_applicationRecords;
- (id)nibName;
- (void)selectAppRecord:(id)arg1;
@property(retain, nonatomic) id <ITunesSoftwareApplicationDescription> selectedApplicationRecord; // @synthesize selectedApplicationRecord=_selectedApplicationRecord;

@end

