//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEDistributionStepViewController.h>

@class NSPopUpButton;

@interface IDEDistributionThinningStepViewController : IDEDistributionStepViewController
{
    int _thinningChoice;
    NSPopUpButton *_thinningOptionsPopUp;
}

+ (id)keyPathsForValuesAffectingEnableDeviceFamiliesPopup;
- (void).cxx_destruct;
- (BOOL)canGoNext;
@property(readonly) BOOL enableDeviceFamiliesPopup;
- (void)learnMore:(id)arg1;
- (id)nextButtonTitle;
@property(nonatomic) int thinningChoice; // @synthesize thinningChoice=_thinningChoice;
@property(retain, nonatomic) NSPopUpButton *thinningOptionsPopUp; // @synthesize thinningOptionsPopUp=_thinningOptionsPopUp;
- (id)title;
- (void)updateMenuWithFamilies:(id)arg1;
- (void)updateValueFromMenu:(id)arg1;
- (void)viewDidLoad;

@end

