//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEAlertViewController.h>

@class NSTextField;

@interface IDEDialogAlertViewController : IDEAlertViewController
{
    NSTextField *alertKindLabel;
}

- (void).cxx_destruct;
@property(retain) NSTextField *alertKindLabel; // @synthesize alertKindLabel;
- (void)loadView;

@end

