//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/IDETestReport_TestGroup-Protocol.h>

@class IDESchemeActionTestSummaryGroup, NSArray, NSMutableArray, NSString;

@interface IDELogTestsViewTestGroup : NSObject <IDETestReport_TestGroup>
{
    NSMutableArray *_failingTestWrappers;
    NSMutableArray *_passingTestWrappers;
    IDESchemeActionTestSummaryGroup *_parentGroup;
    NSArray *_testSummaries;
    NSString *_name;
}

- (void).cxx_destruct;
- (void)addTestWrapper:(id)arg1;
- (id)ide_sharedTests_failingTests;
- (id)ide_sharedTests_passingTests;
- (id)ide_sharedTests_testGroup_allTests;
- (id)ide_sharedTests_testGroup_includePassingTests:(BOOL)arg1 includeFailingTests:(BOOL)arg2 includeOnlyPerfTests:(BOOL)arg3;
- (id)ide_sharedTests_testGroup_perfTests;
@property(readonly, copy, nonatomic) NSString *ide_testReport_base_identifier;
@property(readonly, copy, nonatomic) NSString *ide_testReport_testGroup_groupName;
@property(readonly, copy, nonatomic) NSString *ide_testReport_testGroup_testTargetName;
@property(copy) NSString *name; // @synthesize name=_name;
@property(retain) IDESchemeActionTestSummaryGroup *parentGroup; // @synthesize parentGroup=_parentGroup;
@property(readonly, copy) NSArray *testSummaries; // @synthesize testSummaries=_testSummaries;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

