//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDENavigableItemFilteringCoordinator.h>

@class DVTTimeSlicedMainThreadWorkQueue, NSMutableDictionary;

@interface IDENavigableItemAsyncFilteringCoordinator : IDENavigableItemFilteringCoordinator
{
    int _currentFilteringGeneration;
    NSMutableDictionary *_filteringProxiesByKey;
    DVTTimeSlicedMainThreadWorkQueue *_itemsToFilterQueue;
    DVTTimeSlicedMainThreadWorkQueue *_itemsToInvalidateChildArrangedItemsQueue;
}

+ (id)keyPathsForValuesAffectingPerformingFiltering;
- (void).cxx_destruct;
- (id)_arrangeItems:(id)arg1 ofItem:(id)arg2;
- (void)_beginFilteringFrom:(id)arg1;
- (int)_filterCurrentGeneration;
- (void)_filterDidChange;
- (id)_filteredItemProxyForItems:(id)arg1;
- (id)_filteredItemProxyForKey:(id)arg1;
- (id)_filteringProxiesByKey;
- (void)_handleItemsPropertiesDidChange:(id)arg1;
- (void)_handleObjectGraphDidChange:(id)arg1;
- (void)_invalidateArrangedChildrenOfFilterProxies;
- (void)_invalidateParentsChildrenOf:(id)arg1;
- (void)_itemInvalidateMatchState:(id)arg1;
- (void)_markItem:(id)arg1 matches:(BOOL)arg2;
- (void)_performFilterEvaluationOf:(id)arg1;
- (void)_setFilteredItemProxy:(id)arg1 forKey:(id)arg2;
- (void)_stopAllWork;
- (id)init;
@property(readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToFilterQueue; // @synthesize itemsToFilterQueue=_itemsToFilterQueue;
@property(readonly) DVTTimeSlicedMainThreadWorkQueue *itemsToInvalidateChildArrangedItemsQueue; // @synthesize itemsToInvalidateChildArrangedItemsQueue=_itemsToInvalidateChildArrangedItemsQueue;
- (BOOL)performingFiltering;
- (void)primitiveInvalidate;
- (void)resumeFiltering;
- (void)suspendFiltering;

@end

