//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDENavigableItemCoordinator.h>

@class DVTNotificationToken, IDENavigableItemFilter;

@interface IDENavigableItemFilteringCoordinator : IDENavigableItemCoordinator
{
    DVTNotificationToken *_itemPropertyChangeObserver;
    DVTNotificationToken *_objectGraphChangeObserver;
    BOOL _isSuspended;
    BOOL _performingFiltering;
    IDENavigableItemFilter *_filter;
}

- (void).cxx_destruct;
- (id)_arrangeItems:(id)arg1 ofItem:(id)arg2;
- (id)_arrangedChildItemsOfItem:(id)arg1;
- (void)_filterDidChange;
- (BOOL)_filterMatchesItem:(id)arg1;
- (void)_handleItemsPropertiesDidChange:(id)arg1;
- (void)_handleItemsPropertiesDidChangeNotification:(id)arg1;
- (void)_handleObjectGraphDidChange:(id)arg1;
- (void)_handleObjectGraphDidChangeNotification:(id)arg1;
- (BOOL)_shouldDecendFilteringIntoChildrenOf:(id)arg1;
@property(retain, nonatomic) IDENavigableItemFilter *filter; // @synthesize filter=_filter;
- (id)init;
@property BOOL performingFiltering; // @synthesize performingFiltering=_performingFiltering;
- (void)primitiveInvalidate;
- (void)resumeFiltering;
- (void)suspendFiltering;

@end

