//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLayoutView_ML.h>

#import <IDEKit/NSTextViewDelegate-Protocol.h>

@class NSButton, NSString, NSTextView;
@protocol IDEProvisioningIssueSliceViewDelegate, NSTextAttachmentCell;

@interface IDEProvisioningIssueSliceView : DVTLayoutView_ML <NSTextViewDelegate>
{
    BOOL _wantsSubtitleButton;
    NSString *_title;
    NSString *_subtitle;
    NSString *_buttonTitle;
    NSTextView *_textView;
    NSButton *_button;
    double _bottomSpace;
    id <NSTextAttachmentCell> _textAttachmentCell;
    id <IDEProvisioningIssueSliceViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)attributedStringForTitle:(id)arg1 subtitle:(id)arg2 wantsSubtitleButton:(BOOL)arg3;
@property(nonatomic) double bottomSpace; // @synthesize bottomSpace=_bottomSpace;
@property(retain, nonatomic) NSButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
- (void)clickedIssueButton:(id)arg1;
- (void)clickedSubtitleButton:(id)arg1;
@property(nonatomic) __weak id <IDEProvisioningIssueSliceViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithButtonTitle:(id)arg1 sliceViewDelegate:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 wantsSubtitleButton:(BOOL)arg3 sliceViewDelegate:(id)arg4;
- (BOOL)isFlipped;
- (void)layoutBottomUp;
- (void)layoutTopDown;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) id <NSTextAttachmentCell> textAttachmentCell; // @synthesize textAttachmentCell=_textAttachmentCell;
@property(retain, nonatomic) NSTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) BOOL wantsSubtitleButton; // @synthesize wantsSubtitleButton=_wantsSubtitleButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

