//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@class NSTrackingArea;

@interface IDEProcessActionPopUpButton : NSPopUpButton
{
    NSTrackingArea *_trackingArea;
}

- (void).cxx_destruct;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (id)processActionPopUpCell;
@property(retain) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;
- (void)updateTrackingAreas;

@end

