//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTExtension, NSImage, NSString;

@interface IDEToolbarItemProxy : NSObject
{
    BOOL _providesItems;
    NSString *_toolbarItemIdentifier;
    NSString *_toolbarItemLabel;
    NSString *_toolbarItemPaletteLabel;
    NSString *_toolbarItemTooltip;
    SEL _toolbarItemAction;
    NSImage *_toolbarItemImage;
    DVTExtension *_commandDefinitionExtension;
    Class _providerClass;
}

+ (id)proxyForToolbarItemElement:(id)arg1 errorMessage:(id *)arg2;
- (void).cxx_destruct;
@property(retain) DVTExtension *commandDefinitionExtension; // @synthesize commandDefinitionExtension=_commandDefinitionExtension;
- (id)initWithItemIdentifier:(id)arg1;
@property(retain) Class providerClass; // @synthesize providerClass=_providerClass;
@property BOOL providesItems; // @synthesize providesItems=_providesItems;
@property SEL toolbarItemAction; // @synthesize toolbarItemAction=_toolbarItemAction;
@property(copy) NSString *toolbarItemIdentifier; // @synthesize toolbarItemIdentifier=_toolbarItemIdentifier;
@property(retain) NSImage *toolbarItemImage; // @synthesize toolbarItemImage=_toolbarItemImage;
@property(copy) NSString *toolbarItemLabel; // @synthesize toolbarItemLabel=_toolbarItemLabel;
@property(copy) NSString *toolbarItemPaletteLabel; // @synthesize toolbarItemPaletteLabel=_toolbarItemPaletteLabel;
@property(copy) NSString *toolbarItemTooltip; // @synthesize toolbarItemTooltip=_toolbarItemTooltip;
- (id)toolbarItemForToolbarInWindow:(id)arg1;

@end

