//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface IDEWorkspaceWindow : NSWindow
{
    BOOL __isOverridingEscapeInsteadOfExitingFullscreen;
}

+ (id)lastActiveWorkspaceWindowController;
- (BOOL)_addCursorRect:(struct CGRect)arg1 cursor:(id)arg2 forView:(id)arg3;
- (struct CGRect)_adjustedFrameForSaving:(struct CGRect)arg1;
- (void)_invalidateCursorRectsForView:(id)arg1 force:(BOOL)arg2;
- (void)_invalidateCursorRectsForViewsWithNoTrackingAreas;
@property BOOL _isOverridingEscapeInsteadOfExitingFullscreen; // @synthesize _isOverridingEscapeInsteadOfExitingFullscreen=__isOverridingEscapeInsteadOfExitingFullscreen;
- (BOOL)_keyViewRedirectionDisabled;
- (void)_setCursorForMouseLocation:(struct CGPoint)arg1;
- (struct CGRect)adjustedFrameForCascade:(struct CGRect)arg1 fromWindow:(id)arg2;
- (void)becomeMainWindow;
- (BOOL)canBecomeKeyWindow;
- (BOOL)canBecomeMainWindow;
- (void)cancelOperation:(id)arg1;
- (void)close;
- (void)dvt_shouldDeallocate;
- (void)endSheet:(id)arg1 returnCode:(long long)arg2;
- (void)exitFullScreenMode:(id)arg1;
- (id)firstResponder;
- (void)recalculateKeyViewLoop;
- (void)sendEvent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setWindowController:(id)arg1;
- (void)toggleToolbarShown:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;

@end

