//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEActivityReporter.h>

@class DVTObservingToken, IDEActivityReport;

@interface IDEWorkspaceActivityReporter : IDEActivityReporter
{
    DVTObservingToken *_activityObserverToken;
    DVTObservingToken *_workspaceNameObserverToken;
    IDEActivityReport *_activeReport;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)_title;
- (id)initWithWorkspace:(id)arg1;
- (void)primitiveInvalidate;
- (void)updateActivity;

@end

