//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDBase/XDUMLNamespaceImp.h>

#import <XDBase/XDUMLClassifier-Protocol.h>

@class NSString;

@interface XDUMLClassifierImp : XDUMLNamespaceImp <XDUMLClassifier>
{
    BOOL _isAbstract;
}

- (void)addOperation:(id)arg1;
- (void)addProperty:(id)arg1;
- (id)attributes;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)features;
- (void)generalizationAdded:(id)arg1;
- (void)generalizationRemoved:(id)arg1;
- (id)generalizations;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)insertObject:(id)arg1 inPropertiesAtIndex:(unsigned long long)arg2;
- (BOOL)isAbstract;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (id)newGeneralizationFrom:(id)arg1;
- (id)newOperationWithName:(id)arg1;
- (id)newPropertyWithName:(id)arg1;
- (id)operationForName:(id)arg1;
- (id)ownedAttributes;
- (id)ownedOperations;
- (id)package;
- (id)properties;
- (id)propertyForName:(id)arg1;
- (void)removeObjectFromPropertiesAtIndex:(unsigned long long)arg1;
- (void)removeOperation:(id)arg1;
- (void)removeProperty:(id)arg1;
- (void)setIsAbstract:(BOOL)arg1;
- (void)specializationAdded:(id)arg1;
- (void)specializationRemoved:(id)arg1;
- (id)specializations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

