//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ModelIO/MDLNamed-Protocol.h>

@class NSData, NSString;

@interface MDLTexture : NSObject <MDLNamed>
{
    NSString *_name;
    struct MDLTextureData _textureData;
    long long _channelEncoding;
    NSData *_topLeftOriginData[14];
    NSData *_bottomLeftOriginData[14];
    BOOL _selfCreating;
    BOOL _alphaValuesSet;
    BOOL _hasAlphaValues;
}

+ (id)_textureCubeWithSingleImageNamed:(id)arg1 bundle:(id)arg2;
+ (id)irradianceTextureCubeWithTexture:(id)arg1 name:(id)arg2 dimensions: /* Error: Ran out of types for this method. */;
+ (id)irradianceTextureCubeWithTexture:(id)arg1 name:(id)arg2 dimensions:(float)arg3 roughness: /* Error: Ran out of types for this method. */;
+ (id)textureCubeWithImagesNamed:(id)arg1;
+ (id)textureCubeWithImagesNamed:(id)arg1 bundle:(id)arg2;
+ (id)textureNamed:(id)arg1;
+ (id)textureNamed:(id)arg1 bundle:(id)arg2;
- (void).cxx_destruct;
- (id)allocateDataAtLevel:(long long)arg1;
@property(readonly, nonatomic) unsigned long long channelCount;
@property(readonly, nonatomic) long long channelEncoding; // @synthesize channelEncoding=_channelEncoding;
- (void)clearTexelData;
// Error parsing type for property dimensions:
// Property attributes: T,R,N

- (id)generateDataAtLevel:(long long)arg1;
@property(nonatomic) BOOL hasAlphaValues;
- (struct CGImage *)imageFromTexture;
- (id)init;
- (id)initWithData:(id)arg1 topLeftOrigin:(BOOL)arg2 name:(id)arg3 dimensions:(long long)arg4 rowStride:(unsigned long long)arg5 channelCount:(long long)arg6 channelEncoding:(BOOL)arg7 isCube: /* Error: Ran out of types for this method. */;
@property(nonatomic) BOOL isCube;
- (void)loadDataWithBottomLeftOriginAtMipLevel:(long long)arg1 create:(BOOL)arg2;
- (void)loadDataWithTopLeftOriginAtMipLevel:(long long)arg1 create:(BOOL)arg2;
@property(readonly, nonatomic) unsigned long long mipLevelCount;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) long long rowStride;
- (void)setTexelDataWithBottomLeftOrigin:(id)arg1 atMipLevel:(long long)arg2;
- (void)setTexelDataWithTopLeftOrigin:(id)arg1 atMipLevel:(long long)arg2;
- (id)texelDataWithBottomLeftOrigin;
- (id)texelDataWithBottomLeftOriginAtMipLevel:(long long)arg1 create:(BOOL)arg2;
- (id)texelDataWithTopLeftOrigin;
- (id)texelDataWithTopLeftOriginAtMipLevel:(long long)arg1 create:(BOOL)arg2;
- (struct MDLTextureData *)textureData;
- (BOOL)writeToFile:(id)arg1 atomically:(BOOL)arg2;
- (BOOL)writeToURL:(id)arg1;
- (BOOL)writeToURL:(id)arg1 type:(struct __CFString *)arg2;

@end

