//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface DVT_VMUProcInfo : NSObject
{
    unsigned int _task;
    BOOL _needTaskPortDealloc;
    NSString *_name;
    NSArray *_arguments;
    NSArray *_envVars;
    NSString *_procTableName;
    NSString *_realAppName;
    NSString *_requestedAppName;
    NSString *_firstArg;
    int _pid;
    int _ppid;
    struct timeval _startTime;
}

+ (id)getProcessIds;
+ (BOOL)isProcessRunning:(int)arg1;
+ (int)processParentId:(int)arg1;
- (id)_infoFromCommandLine:(int)arg1;
- (id)arguments;
- (long long)compare:(id)arg1;
- (long long)compareByName:(id)arg1;
- (long long)compareByUserAppName:(id)arg1;
- (int)cpuType;
- (void)dealloc;
- (id)description;
- (id)envVars;
- (void)finalize;
- (id)firstArgument;
- (unsigned long long)hash;
- (id)init;
- (id)initWithPid:(int)arg1;
- (id)initWithTask:(unsigned int)arg1;
- (BOOL)isApp;
- (BOOL)isCFM;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isMachO;
- (BOOL)isNative;
- (BOOL)isRunning;
- (id)name;
- (int)pid;
- (int)ppid;
- (id)procTableName;
- (id)realAppName;
- (id)requestedAppName;
- (BOOL)signal:(int)arg1;
- (struct timeval)startTime;
- (unsigned int)task;
- (BOOL)terminate;
- (void)update;
- (id)userAppName;
- (id)valueForEnvVar:(id)arg1;

@end

