//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEBaseDocumentNavigableItem.h>

@class DVTDocumentLocation;

@interface IDEDocumentURLNavigableItem : IDEBaseDocumentNavigableItem
{
    DVTDocumentLocation *_contentDocumentLocation;
}

- (void).cxx_destruct;
- (id)_documentURL;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)fileURL;
- (id)initWithRepresentedObject:(id)arg1;
- (id)name;
- (id)newImage;

@end

