//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTDelayedInvocation, DVTStackBacktrace, IDEOpenQuicklyContext, NSArray, NSString;
@protocol IDEOpenQuicklyQueryDelegate;

@interface IDEOpenQuicklyQuery : NSObject <DVTInvalidation>
{
    NSArray *_matchProviders;
    NSArray *_observationTokens;
    IDEOpenQuicklyContext *_context;
    NSArray *_matches;
    NSArray *_providerClasses;
    DVTDelayedInvocation *_matchInvocation;
    id <IDEOpenQuicklyQueryDelegate> _delegate;
    BOOL _idle;
}

+ (void)initialize;
+ (id)scopedProviderClasses;
+ (id)unscopedProviderClasses;
- (void).cxx_destruct;
- (BOOL)_allMatchProvidersAreIdle;
- (void)_invokeBlockWithScoredMatches:(CDUnknownBlockType)arg1;
- (void)_validateMatches:(id)arg1;
- (id)beRuthless:(id)arg1;
@property(retain, nonatomic) IDEOpenQuicklyContext *context; // @synthesize context=_context;
@property(retain) id <IDEOpenQuicklyQueryDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithProviderClasses:(id)arg1;
@property(getter=isIdle) BOOL idle; // @synthesize idle=_idle;
- (void)logMatches:(id)arg1 logLevel:(int)arg2;
@property(copy) NSArray *matches; // @synthesize matches=_matches;
- (void)primitiveInvalidate;
- (id)sortedTopMatches:(long long)arg1;
- (void)toggleRuthless;
- (long long)totalNumberOfMatches;
- (id)trimDuplicates:(id)arg1;
- (id)trimSymbolMatches:(id)arg1;
- (void)validateMatches;
- (void)validateMatchesIfNeeded;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

