//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HexFiend/HFRepresenter.h>

@class NSScroller;

@interface HFVerticalScrollerRepresenter : HFRepresenter
{
    NSScroller *_scroller;
}

+ (struct CGPoint)defaultLayoutPosition;
- (void)accomodateGrowBox;
- (void)controllerDidChange:(unsigned long long)arg1;
- (id)createView;
- (double)minimumViewWidthForBytesPerLine:(unsigned long long)arg1;
- (void)scrollByKnobToValue:(double)arg1;
- (void)scrollByLines:(long long)arg1;
- (void)scrollerDidChangeValue:(id)arg1;
- (void)updateScrollerValue;
- (unsigned long long)visibleLines;

@end

