//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEDistributionContext, NSSet;

@interface IDEDistributionStep : NSObject
{
    IDEDistributionContext *_context;
}

+ (id)availableOptionsForPropertyList;
- (void).cxx_destruct;
@property(readonly) IDEDistributionContext *context; // @synthesize context=_context;
- (id)init;
- (id)initWithContext:(id)arg1;
- (BOOL)loadFromPropertyList:(id)arg1 error:(id *)arg2;
@property(readonly) NSSet *providedOutputContextPropertyNames;
@property(readonly) NSSet *requiredInputContextPropertyNames;

@end

