//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTDocumentLocation.h>

@class NSString;

@interface IDEGaugeDocumentLocation : DVTDocumentLocation
{
    BOOL _displaysWhileTracing;
    NSString *_displayName;
    unsigned long long _priority;
}

+ (id)URLForScheme:(id)arg1 launchSession:(id)arg2;
+ (id)URLForScheme:(id)arg1 launchSession:(id)arg2 otherQueryString:(id)arg3;
+ (id)launchSessionFromURL:(id)arg1;
- (void).cxx_destruct;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
@property BOOL displaysWhileTracing; // @synthesize displaysWhileTracing=_displaysWhileTracing;
- (id)initWithDisplayName:(id)arg1 documentURL:(id)arg2 priority:(unsigned long long)arg3;
@property(readonly) unsigned long long priority; // @synthesize priority=_priority;

@end

