//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTFilePath, DVTSDK, DVTStackBacktrace, IDEPlaygroundAuxiliarySourceFrameworkLocation, NSArray, NSHashTable, NSSet, NSString, NSUUID;

@interface IDEPlaygroundCommonSharedContext : NSObject
{
    DVTStackBacktrace *_creationBacktrace;
    NSSet *_sourcesDirectorySwiftFiles;
    IDEPlaygroundCommonSharedContext *_parentContext;
    IDEPlaygroundAuxiliarySourceFrameworkLocation *_expectedAuxiliarySourceFrameworkLocation;
    DVTFilePath *_expectedSymlinkedResourcesLocation;
    NSUUID *_UUID;
    DVTFilePath *_filePath;
    NSHashTable *_referencingContainersTable;
}

+ (id)UTI;
+ (Class)contextDeserializerClass;
+ (Class)contextSerializerClass;
+ (id)filePathExtension;
+ (id)keyPathsForValuesAffectingExpectedAuxiliarySourceFrameworkLocation;
+ (id)keyPathsForValuesAffectingExpectedSymlinkedResourcesLocation;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingResourceDirectoryFilePaths;
+ (id)keyPathsForValuesAffectingResourcesDirectoryPath;
+ (id)keyPathsForValuesAffectingSourcesDirectoryPath;
+ (id)keyPathsForValuesAffectingSwiftContentsFilePath;
+ (id)keyPathsForValuesAffectingTimelineFilePath;
- (void).cxx_destruct;
@property(retain, nonatomic) NSUUID *UUID; // @synthesize UUID=_UUID;
- (void)_filePathDidChange;
- (void)_filePathWillChange;
- (void)_notifyResourcesDirectoryChangedOnBackgroundQueue;
- (void)_notifySourcesDirectoryChangedOnBackgroundQueue;
- (id)_platformForFrameworkSearchPaths;
@property(readonly, nonatomic) DVTSDK *_sdkForAuxiliarySource;
@property(readonly, nonatomic) NSString *_targetTripleForAuxiliarySource;
- (void)_workspaceRunContextsChanged;
- (void)addSourcesDirectoryObserver;
- (void)dealloc;
- (id)description;
- (void)enumerateReferencingContainersWithBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) IDEPlaygroundAuxiliarySourceFrameworkLocation *expectedAuxiliarySourceFrameworkLocation; // @synthesize expectedAuxiliarySourceFrameworkLocation=_expectedAuxiliarySourceFrameworkLocation;
@property(retain, nonatomic) DVTFilePath *expectedSymlinkedResourcesLocation; // @synthesize expectedSymlinkedResourcesLocation=_expectedSymlinkedResourcesLocation;
@property(retain, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly, nonatomic) NSString *filename;
@property(readonly, nonatomic) NSArray *frameworkSearchPaths;
@property(readonly, nonatomic) BOOL implicit;
- (id)init;
- (id)initWithFilePath:(id)arg1 parentContext:(id)arg2;
- (void)invalidateCachedSourcesDirectorySwiftFiles;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) IDEPlaygroundCommonSharedContext *parentContext; // @synthesize parentContext=_parentContext;
@property(readonly) NSHashTable *referencingContainersTable; // @synthesize referencingContainersTable=_referencingContainersTable;
- (BOOL)registerReferencingContainer:(id)arg1;
- (void)removeSourcesDirectoryObserver;
@property(readonly, nonatomic) NSArray *resourceDirectoryFilePaths;
@property(readonly, nonatomic) DVTFilePath *resourcesDirectoryPath;
@property(readonly, nonatomic) DVTFilePath *sourcesDirectoryPath;
- (id)sourcesDirectorySwiftFiles;
@property(readonly, nonatomic) DVTFilePath *swiftContentsFilePath;
- (id)timelineFilePath;
- (BOOL)unregisterReferencingContainer:(id)arg1;

@end

