//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class IDEProfileQualification, NSArray, NSOrderedSet, NSString;
@protocol IDEProvisioningBasicProfile, IDEProvisioningBasicSigningIdentity, IDEProvisioningBasicTeam;

@protocol IDEProvisioningSigningSelectionDataSource
@property(readonly) NSString *configurationName;
@property(readonly) NSArray *errors;
@property(readonly, getter=isProfileChangeable) BOOL profileChangeable;
@property(readonly, getter=isRepairBusy) BOOL repairBusy;
@property(readonly) BOOL isSigningIdentityChangeable;
@property(readonly, nonatomic) BOOL isTeamSelectionRequired;
- (void)locateEligibleProfiles:(id *)arg1 ineligibleProfiles:(id *)arg2;
@property(readonly, nonatomic) IDEProfileQualification *profileQualification;
@property(readonly) long long profileSupport;
@property(retain, nonatomic) id <IDEProvisioningBasicProfile> provisioningProfile;
@property(readonly) NSString *repairBusyReason;
@property(retain, nonatomic) id <IDEProvisioningBasicSigningIdentity> signingIdentity;
@property(retain, nonatomic) id <IDEProvisioningBasicTeam> team;
@property(readonly, nonatomic) NSOrderedSet *signingIdentities;
@property(readonly) long long signingStyle;
@property(readonly) BOOL wantsTeamSelectionRegardlessOfSigningStyle;
@end

