//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTOperation.h>

@class DVTTask, IDEActivityLogSection, IDEPlaygroundAuxiliarySourceFrameworkLocation, IDEPlaygroundCommonSharedContext, NSArray, NSDate, NSSet;

@interface IDEPlaygroundAuxiliarySourceCompilerOperation : DVTOperation
{
    BOOL _compilerLoggingEnabled;
    NSDate *_compilationDate;
    IDEPlaygroundAuxiliarySourceFrameworkLocation *_frameworkLocation;
    IDEActivityLogSection *_activityLogSection;
    IDEPlaygroundCommonSharedContext *_context;
    NSSet *_sourcesDirectorySwiftFiles;
    DVTTask *_compilerTask;
}

+ (id)logAspect;
- (void).cxx_destruct;
@property(retain) IDEActivityLogSection *activityLogSection; // @synthesize activityLogSection=_activityLogSection;
@property(readonly) NSArray *basicBuildFlags;
- (void)cancel;
@property(retain) NSDate *compilationDate; // @synthesize compilationDate=_compilationDate;
@property(retain) DVTTask *compilerTask; // @synthesize compilerTask=_compilerTask;
@property __weak IDEPlaygroundCommonSharedContext *context; // @synthesize context=_context;
@property(retain) IDEPlaygroundAuxiliarySourceFrameworkLocation *frameworkLocation; // @synthesize frameworkLocation=_frameworkLocation;
- (id)initWithContext:(id)arg1 swiftSourceFiles:(id)arg2;
- (id)linkerBuildFlags;
- (void)main;
- (void)makeDefaultPriority;
- (void)makeHighestPriority;
- (BOOL)signFrameworkDylibAtPath:(id)arg1 error:(id *)arg2;
@property(readonly, copy) NSSet *sourcesDirectorySwiftFiles; // @synthesize sourcesDirectorySwiftFiles=_sourcesDirectorySwiftFiles;

@end

