//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDECommandLineVerb.h>

@interface IDEResultBundleCommandLineVerb : IDECommandLineVerb
{
}

+ (id)arrayOfDictionaryRepresentationsForIssueSummaries:(id)arg1;
+ (void)emitJSONForPropertyList:(id)arg1 toFileHandle:(id)arg2;
+ (id)issueSummariesForSchemeActionsInvocationRecord:(id)arg1;
+ (id)optionDefinitionsWithEnvironment:(id)arg1;
+ (int)performWithEnvironment:(id)arg1;
+ (id)simpleSummaryForSchemeActionsInvocationRecord:(id)arg1;
+ (id)stringForSchemeActionInvocationRecordStatus:(int)arg1;
+ (id)stringForSimpleOperationStatus:(int)arg1;

@end

