//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTCrashPoint, IDEWorkspace, NSMutableDictionary, NSSet;

@interface IDECrashPointTranslationContext : NSObject
{
    DVTCrashPoint *_crashPoint;
    IDEWorkspace *_workspace;
    NSSet *_binaryUUIDs;
    NSMutableDictionary *_fileNameToFilePathMap;
    NSMutableDictionary *_codeModulesByName;
}

- (void).cxx_destruct;
@property(retain) NSSet *binaryUUIDs; // @synthesize binaryUUIDs=_binaryUUIDs;
- (id)codeModuleForName:(id)arg1;
@property(retain) NSMutableDictionary *codeModulesByName; // @synthesize codeModulesByName=_codeModulesByName;
- (BOOL)containsBinaryUUID:(id)arg1;
@property(retain) DVTCrashPoint *crashPoint; // @synthesize crashPoint=_crashPoint;
@property(retain) NSMutableDictionary *fileNameToFilePathMap; // @synthesize fileNameToFilePathMap=_fileNameToFilePathMap;
- (id)filePathForFileName:(id)arg1;
- (id)initWithCrashPoint:(id)arg1 workspace:(id)arg2;
- (id)initWithCrashPoint:(id)arg1 workspace:(id)arg2 binaryUUIDs:(id)arg3;
- (void)setCodeModule:(id)arg1 forName:(id)arg2 passesBuildProductDirFallback:(BOOL)arg3;
@property __weak IDEWorkspace *workspace; // @synthesize workspace=_workspace;

@end

