//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSBundle.h>

@interface NSBundle (TSBundleAdditions)
+ (id)cachedBundleWithIdentifier:(id)arg1;
+ (unsigned long long)defaultDomainMask;
+ (id)searchPathsForSupportFilesWithSubpath:(id)arg1;
+ (id)searchPathsForSupportFilesWithSubpath:(id)arg1 developerPaths:(id)arg2;
+ (id)searchPathsForSupportFilesWithSubpath:(id)arg1 developerPaths:(id)arg2 domainMask:(unsigned long long)arg3;
+ (id)searchPathsForSupportFilesWithSubpath:(id)arg1 developerPaths:(id)arg2 domainMask:(unsigned long long)arg3 forToolsVersions:(id)arg4;
- (id)_TS_localizedInfoDictionary:(id)arg1;
- (id)infoDictionaryFullyLocalized;
@end

