//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsSupport/PBXTSByteStream.h>

#import <DevToolsSupport/PBXTSByteStreamConsuming-Protocol.h>
#import <DevToolsSupport/PBXTSTaskSynchronizedFileHandle-Protocol.h>

@class NSConditionLock, NSFileHandle, NSMutableArray, NSMutableData, NSString, PBXTSTask;

@interface PBXTSPTYDeviceByteStream : PBXTSByteStream <PBXTSByteStreamConsuming, PBXTSTaskSynchronizedFileHandle>
{
    int _masterFD;
    int _slaveFD;
    NSString *_slaveDeviceName;
    NSFileHandle *_slaveFileHandle;
    BOOL _receivedLastDataBuffer;
    PBXTSTask *_taskToSynchronizeWith;
    int _fromSignalPipeFD;
    int _toSignalPipeFD;
    BOOL _watcherThreadRunning;
    NSConditionLock *_queueLock;
    NSMutableArray *_queue;
    NSMutableData *_accumulator;
    unsigned long long _bufferedDataLength;
    unsigned long long _stats_numBytesSent;
    unsigned long long _stats_numBytesRead;
}

- (void)_processPtyData;
- (void)_ptyWatcherThreadDidExit;
- (void)_setupPTYWatcherThread;
- (void)_stopPTYWatcherThread;
- (void)_watchPTY;
- (void)closePTY;
- (void)dealloc;
- (BOOL)didSynchronizedFileHandleReceiveLastData;
- (id)fileHandleForSlaveDevice;
- (void)finalize;
- (id)init;
- (int)masterDeviceFD;
- (void)sendStreamDidEnd;
- (id)slaveDeviceName;
- (void)stream:(id)arg1 processBytes:(id)arg2;
- (void)streamDidEnd:(id)arg1;
- (void)synchronizeWithTask:(id)arg1;
- (void)taskDidStopForSynchronizedFileHandle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

