//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TSLineDataBuffer : NSObject
{
    struct __CFData *_data;
    unsigned long long _offsetOfIncompleteLine;
}

- (void)appendBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (void)appendData:(id)arg1;
- (void)appendNewlineIfNeeded;
- (const char *)bytes;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(unsigned long long)arg1;
- (unsigned long long)length;
- (unsigned long long)lengthOfCompleteLines;
- (unsigned long long)processCompleteLinesUsingFunction:(CDUnknownFunctionPointerType)arg1 context:(void *)arg2 andRemove:(BOOL)arg3;
- (void)removeBytesInRange:(struct _NSRange)arg1;

@end

