//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL, NSURLDownload;
@protocol DSADownloaderDelegate;

__attribute__((visibility("hidden")))
@interface DSADownloader : NSObject
{
    NSURLDownload *_download;
    NSURL *_downloadURL;
    NSString *_downloadPath;
    BOOL _isDownloading;
    long long _bytesDownloaded;
    long long _sizeOfDownload;
    BOOL _downloadRequiresAuthorization;
    BOOL _authenticationDidFail;
    BOOL _didReceiveChallenge;
    double _lastNotificationTime;
    NSObject<DSADownloaderDelegate> *_delegate;
}

+ (void)cleanUpDownloadFolder;
+ (id)downloadFolder;
@property BOOL authenticationDidFail; // @synthesize authenticationDidFail=_authenticationDidFail;
- (long long)bytesDownloaded;
- (void)cancel;
- (void)dealloc;
- (id)delegate;
@property BOOL didReceiveChallenge; // @synthesize didReceiveChallenge=_didReceiveChallenge;
- (void)download:(id)arg1 decideDestinationWithSuggestedFilename:(id)arg2;
- (void)download:(id)arg1 didCreateDestination:(id)arg2;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)download:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;
- (id)download:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)downloadDidBegin:(id)arg1;
- (void)downloadDidFinish:(id)arg1;
@property(copy) NSString *downloadPath; // @synthesize downloadPath=_downloadPath;
@property BOOL downloadRequiresAuthorization; // @synthesize downloadRequiresAuthorization=_downloadRequiresAuthorization;
- (BOOL)downloadShouldUseCredentialStorage:(id)arg1;
@property(copy) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
- (id)initWithDownloadURL:(id)arg1 toPath:(id)arg2;
- (BOOL)isDownloading;
- (void)removeDownload;
- (void)setDelegate:(id)arg1;
- (long long)sizeOfDownload;
- (void)startDownload;

@end

