//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class ASTNode, Declaration, Expression, NSArray, NSData, NSMutableDictionary, NSString, SourceLocation;

@protocol RefactoringParserCallbacks
- (void)addFunctionBody:(Expression *)arg1;
- (NSMutableDictionary *)allClassMethods;
- (NSArray *)allFunctionBodies;
- (NSMutableDictionary *)allInstanceMethods;
- (BOOL)beginHeader:(NSString *)arg1;
- (NSString *)getStringAtFile:(NSString *)arg1 line:(unsigned long long)arg2;
- (NSString *)getStringAtLocation:(SourceLocation *)arg1;
- (NSString *)getStringAtLocation:(SourceLocation *)arg1 replacing:(NSArray *)arg2;
- (Declaration *)globalScope;
- (BOOL)isLocationInMacro:(SourceLocation *)arg1;
- (BOOL)isMacroDefined:(const char *)arg1;
- (BOOL)isPointInMacro:(SourceLocation *)arg1 checkBefore:(BOOL)arg2;
- (BOOL)isPointInMacroBody:(SourceLocation *)arg1 checkBefore:(BOOL)arg2;
- (SourceLocation *)macroDefinitionLocation:(const char *)arg1;
- (NSData *)memorySourceForFile:(const char *)arg1;
- (ASTNode *)nodeAtLocation:(SourceLocation *)arg1;
@end

