//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTServices/NSObject-Protocol.h>

@class DVTDeveloperAccount, NSData, NSString;

@protocol DVTDirectoryServicesSessionDescription <NSObject>
@property(readonly, nonatomic) DVTDeveloperAccount *account;
@property(readonly, copy, nonatomic) NSData *sessionData;
@property(readonly, copy, nonatomic) NSString *sessionID;
@end

