//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTServicesType, NSString;

@interface DVTServicesTypeProperty : NSObject
{
    BOOL _multiple;
    BOOL _optional;
    NSString *_serviceKey;
    NSString *_propertyName;
    DVTServicesType *_type;
    NSString *_deserializeType;
}

- (void).cxx_destruct;
- (id)description;
- (id)deserialize:(id)arg1 context:(id)arg2 error:(id *)arg3;
@property(copy, nonatomic) NSString *deserializeType; // @synthesize deserializeType=_deserializeType;
- (id)initWithExtensionParameter:(id)arg1 context:(id)arg2;
- (id)initWithPropertyName:(id)arg1 serviceKey:(id)arg2 type:(id)arg3 multiple:(BOOL)arg4 optional:(BOOL)arg5;
@property(nonatomic, getter=isMultiple) BOOL multiple; // @synthesize multiple=_multiple;
@property(nonatomic, getter=isOptional) BOOL optional; // @synthesize optional=_optional;
@property(readonly, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;
@property(readonly, nonatomic) NSString *serviceKey; // @synthesize serviceKey=_serviceKey;
@property(readonly, nonatomic) DVTServicesType *type; // @synthesize type=_type;

@end

