//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTMarkup/_TtC9DVTMarkup6XPView.h>

@interface _TtC9DVTMarkupP33_8D794F29D5B038FCB7B9F093D50033A411OrdinalView : _TtC9DVTMarkup6XPView
{
    // Error parsing type: , name: drawingMode
    // Error parsing type: , name: label
    // Error parsing type: , name: style
}

- (CDUnknownBlockType).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;

@end

