//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableHeaderCell.h>

@interface DVTModernTableHeaderCell : NSTableHeaderCell
{
    BOOL _isSortable;
    double _leftTitleMargin;
    double _topTitleMargin;
}

- (void)drawSortIndicatorWithFrame:(struct CGRect)arg1 inView:(id)arg2 ascending:(BOOL)arg3 priority:(long long)arg4;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)init;
@property BOOL isSortable; // @synthesize isSortable=_isSortable;
@property double leftTitleMargin; // @synthesize leftTitleMargin=_leftTitleMargin;
@property double topTitleMargin; // @synthesize topTitleMargin=_topTitleMargin;
- (struct CGRect)sortIndicatorRectForBounds:(struct CGRect)arg1;

@end

