//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextView.h>

@interface DVTSearchFieldTextEditor : NSTextView
{
}

- (void)_didChangeSelection:(id)arg1;
- (void)autoHighlightMatchingBracketAtLocationIfNecessary:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 textContainer:(id)arg2;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)showMatchingBraceAtLocation:(id)arg1;

@end

