//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTKit/DVTTextCompletionItem-Protocol.h>

@class NSArray, NSAttributedString, NSImage, NSString;

@interface DVTStringTextCompletionItem : NSObject <DVTTextCompletionItem>
{
    NSString *_name;
    NSString *_localizedName;
    NSImage *_icon;
    double _priority;
    double _fuzzyMatchingScore;
    long long _priorityBucket;
    unsigned long long _priorityComparatorKind;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *completionText;
@property(readonly, copy) NSString *description;
@property(readonly, copy) NSAttributedString *descriptionText;
@property(readonly, copy) NSString *displayText;
@property(readonly, copy) NSString *displayType;
@property double fuzzyMatchingScore; // @synthesize fuzzyMatchingScore=_fuzzyMatchingScore;
@property(readonly) unsigned long long hash;
@property(retain) NSImage *icon; // @synthesize icon=_icon;
- (id)initWithName:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(copy) NSString *localizedName; // @synthesize localizedName=_localizedName;
@property(copy) NSString *name; // @synthesize name=_name;
@property(readonly) BOOL notRecommended;
@property(readonly, copy) NSString *parentText;
@property double priority; // @synthesize priority=_priority;
@property long long priorityBucket; // @synthesize priorityBucket=_priorityBucket;
@property unsigned long long priorityComparatorKind; // @synthesize priorityComparatorKind=_priorityComparatorKind;

// Remaining properties
@property(readonly, copy) NSString *action;
@property(readonly, copy) NSArray *additionalCompletions;
@property(readonly) int completionItemStyle;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) NSImage *highlightedStatusIcon;
@property(readonly) NSImage *statusIcon;
@property(readonly) Class superclass;

@end

