//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

@class CALayer, DVTTabbedWindowTabViewItem, NSColor;

@interface DVTScrollableTabBarViewButton : NSButton
{
    NSColor *_backgroundColor;
    CALayer *_backgroundLayer;
    CALayer *_centerLayer;
    CALayer *_leftBorderLayer;
    CALayer *_rightBorderLayer;
    CALayer *_topBorderLayer;
    CALayer *_bottomBorderLayer;
    BOOL _active;
    BOOL _showsLeftSeparator;
    BOOL _showsRightSeparator;
    BOOL _hasMouseOverHighlight;
    BOOL _mouseOverHighlightShouldIncludeRightBorderFrameWidth;
    BOOL _forceRepaintWithActiveWindowAppearance;
    DVTTabbedWindowTabViewItem *_tabViewItem;
}

+ (Class)cellClass;
+ (double)contentBoundsWidthForButtonWidth:(double)arg1;
- (void).cxx_destruct;
- (BOOL)_isAnimatingBackgroundColor;
- (void)_setBackgroundColor:(id)arg1 withAnimation:(id)arg2;
- (void)_setUpBackgroundLayer;
- (void)_updateBackgroundLayerImagesForActiveTab:(BOOL)arg1 inActiveWindow:(BOOL)arg2;
- (void)_windowChangedKeyState;
- (struct CGRect)contentBounds;
@property(nonatomic) BOOL forceRepaintWithActiveWindowAppearance; // @synthesize forceRepaintWithActiveWindowAppearance=_forceRepaintWithActiveWindowAppearance;
@property(nonatomic) BOOL hasMouseOverHighlight; // @synthesize hasMouseOverHighlight=_hasMouseOverHighlight;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
- (void)layout;
- (double)leftCapWidth;
@property(nonatomic) BOOL mouseOverHighlightShouldIncludeRightBorderFrameWidth; // @synthesize mouseOverHighlightShouldIncludeRightBorderFrameWidth=_mouseOverHighlightShouldIncludeRightBorderFrameWidth;
- (double)rightCapWidth;
- (void)setHasMouseOverHighlight:(BOOL)arg1 animated:(BOOL)arg2;
@property(nonatomic) BOOL showsLeftSeparator; // @synthesize showsLeftSeparator=_showsLeftSeparator;
@property(nonatomic) BOOL showsRightSeparator; // @synthesize showsRightSeparator=_showsRightSeparator;
@property(nonatomic) DVTTabbedWindowTabViewItem *tabViewItem; // @synthesize tabViewItem=_tabViewItem;
- (void)updateLayer;
- (BOOL)wantsUpdateLayer;

@end

