//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSNumberFormatter.h>

@class NSFormatter, NSString;

@interface DVTStepperTextFieldFormatter : NSNumberFormatter
{
    NSFormatter *_wrappedFormatter;
    NSString *_prefix;
    NSString *_suffix;
}

+ (id)_labelAttributes;
- (void).cxx_destruct;
- (id)attributedStringForObjectValue:(id)arg1 withDefaultAttributes:(id)arg2;
- (BOOL)getObjectValue:(out id *)arg1 forString:(id)arg2 errorDescription:(out id *)arg3;
- (id)init;
@property(copy) NSString *prefix; // @synthesize prefix=_prefix;
@property(copy) NSString *suffix; // @synthesize suffix=_suffix;
@property(copy) NSFormatter *wrappedFormatter; // @synthesize wrappedFormatter=_wrappedFormatter;
- (id)stringForObjectValue:(id)arg1;

@end

