//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUndoManager.h>

#import <DVTKit/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, NSMutableArray, NSString;
@protocol DVTUndoManagerDelegate;

@interface DVTUndoManager : NSUndoManager <DVTInvalidation>
{
    char *_delegateDescription;
    NSMutableArray *_undoGroupingBacktraces;
    NSMutableArray *_undoRegistrationBacktraces;
    long long _beginCount;
    long long _endCount;
    BOOL _willAutomaticallyUndoNextChangeGroup;
    id <DVTUndoManagerDelegate> _delegate;
}

+ (void)initialize;
- (void).cxx_destruct;
- (long long)_beginCount;
- (void)_clearUndoGroupingBacktraces;
- (long long)_endCount;
- (void)_setBeginCount:(long long)arg1;
- (void)_setEndCount:(long long)arg1;
- (id)_undoGroupingBacktraces;
- (id)_undoRegistrationBacktraces;
- (void)automaticallyUndoNextChangeGroup;
- (void)beginUndoGrouping;
@property(retain, nonatomic) id <DVTUndoManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)disableUndoRegistration;
- (void)enableUndoRegistration;
- (void)endUndoGrouping;
- (id)init;
- (id)prepareWithInvocationTarget:(id)arg1;
- (void)primitiveInvalidate;
- (void)redo;
- (void)registerUndoWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
- (void)removeAllActions;
- (void)undo;
- (void)undoNestedGroup;
@property(readonly) BOOL willAutomaticallyUndoNextChangeGroup; // @synthesize willAutomaticallyUndoNextChangeGroup=_willAutomaticallyUndoNextChangeGroup;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

