//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (DVTThemeAdditions)
+ (id)_createStackFrameIconFromName:(id)arg1 withRed:(float)arg2 green:(float)arg3 blue:(float)arg4 alpha:(float)arg5;
+ (id)dvt_archiveIcon;
+ (id)dvt_blankDocumentIcon;
+ (id)dvt_crashPointIcon;
+ (id)dvt_downloadArrowDarkIcon;
+ (id)dvt_downloadArrowIcon;
+ (id)dvt_folderIcon;
+ (id)dvt_genericiOSDeviceIcon;
+ (id)dvt_goToButtonIcon;
+ (id)dvt_groupDefaultAssetIcon;
+ (id)dvt_groupEveryingIcon;
+ (id)dvt_groupLibrarySourceIcon;
+ (id)dvt_iOSApplicationIcon;
+ (id)dvt_navAppExtensionIcon;
+ (id)dvt_navApplicationIcon;
+ (id)dvt_navFrameworkIcon;
+ (id)dvt_navGroupIcon;
+ (id)dvt_navIOSApplicationIcon;
+ (id)dvt_navInAppPurchaseIcon;
+ (id)dvt_navLibraryIcon;
+ (id)dvt_navModuleIcon;
+ (id)dvt_navPluginIcon;
+ (id)dvt_navSDKIcon;
+ (id)dvt_navSourcesFolderIcon;
+ (id)dvt_navSubmoduleIcon;
+ (id)dvt_navTargetIcon;
+ (id)dvt_navToolIcon;
+ (id)dvt_navTvOSApplicationIcon;
+ (id)dvt_navWatchOSApplicationIcon;
+ (id)dvt_navXPCServiceIcon;
+ (id)dvt_questionMarkIcon;
+ (id)dvt_stackFrameGenericIconWithOverrideColor:(id)arg1;
+ (id)dvt_stackFrameIconForLibraryPath:(id)arg1 overrideColor:(id)arg2;
+ (id)dvt_stackFrameIconForUserCodeWithOverrideColor:(id)arg1;
+ (id)dvt_tabIcon;
+ (id)dvt_unknownFSObjectIcon;
+ (id)dvt_watchAppIcon;
@end

