//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DocSetAccess/DSAResultSource.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface DSAArrayResultSource : DSAResultSource
{
    NSArray *_theResults;
}

- (void)cancel;
- (void)dealloc;
- (BOOL)hasMoreResults;
- (id)initWithResults:(id)arg1 withSortDescriptor:(id)arg2;
- (id)nextResultsInTime:(double)arg1;
- (id)remainingResults;

@end

