//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DSASubscription, NSMutableArray, NSString, NSURL;

@interface DSADocSetGroup : NSObject
{
    NSString *_name;
    NSString *_publisherName;
    id _subscription;
    NSString *_defaultFeedName;
    NSURL *_defaultFeedURL;
    NSMutableArray *_docSetItems;
}

+ (id)_docSetDictionaryForPSObject:(id)arg1;
+ (CDStruct_6df46f26)currentXcodeVersion;
+ (id)defaultFeedClient;
+ (BOOL)isVersion:(CDStruct_6df46f26)arg1 compatibleWithKeys:(id)arg2;
+ (void)refreshAll;
+ (void)setCurrentXcodeVersion:(CDStruct_6df46f26)arg1;
+ (void)setDefaultFeedClient:(id)arg1;
+ (void)setRefreshInterval:(double)arg1;
+ (id)subscribedGroups;
- (id)_docSetItemForDocSet:(id)arg1;
- (id)_docSetNamespacePrefixForFeed:(id)arg1;
- (id)_errorForSubscriptionFailure:(id)arg1 URL:(id)arg2;
- (id)_feedEntries;
- (id)_loadFeedURL:(id)arg1 error:(id *)arg2;
- (void)_postChangeNotificationForModifiedItems:(id)arg1 andRemovedItems:(id)arg2;
- (void)_resetName;
- (BOOL)_subscribeToURL:(id)arg1 error:(id *)arg2;
- (void)_updateChanged:(id)arg1;
- (id)_validateFeedURL:(id)arg1 error:(id *)arg2;
- (void)addDocSet:(id)arg1;
- (id)bestFeedEntryFromList:(id)arg1 forUpdate:(id)arg2;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)docSetItems;
- (id)docSetUpdateForDocSet:(id)arg1;
- (id)docSets;
- (id)feed;
- (id)feedEntriesByIdentifier:(id)arg1;
- (id)feedURL;
- (BOOL)hasNewDocSets;
- (BOOL)hasUpdatedDocSets;
- (id)init;
- (id)initWithDocSet:(id)arg1;
- (id)initWithFeedURL:(id)arg1;
- (id)initWithFeedURL:(id)arg1 error:(id *)arg2;
- (id)initWithFeedURL:(id)arg1 name:(id)arg2 subscribe:(BOOL)arg3 error:(id *)arg4;
- (id)initWithSubscription:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSString *localizedPublisherName;
- (id)name;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly) NSString *publisherIdentifier;
- (BOOL)refreshDocSetItems;
- (void)refreshNow;
@property(retain) DSASubscription *subscription; // @synthesize subscription=_subscription;
- (void)subscribe;
- (BOOL)subscribeWithError:(id *)arg1;
- (void)unsubscribe;

@end

