//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DSATextSearchResult : NSObject
{
    id _searchResultIvars;
}

+ (id)searchResultWithPath:(id)arg1 searchResultID:(unsigned long long)arg2 documentID:(unsigned long long)arg3 docRootID:(unsigned long long)arg4 relevance:(float)arg5 fromIndex:(id)arg6;
- (id)URL;
- (void)dealloc;
- (id)docRootType;
- (id)docSet;
- (id)enclosingDocument;
- (long long)enclosingDocumentID;
- (id)index;
- (id)initWithPath:(id)arg1 searchResultID:(unsigned long long)arg2 documentID:(unsigned long long)arg3 docRootID:(unsigned long long)arg4 relevance:(float)arg5 fromIndex:(id)arg6;
- (BOOL)matchesDocumentInformation;
- (id)parentNode;
- (long long)parentNodeID;
- (id)path;
- (float)relevance;
- (unsigned long long)searchKitID;
- (id)title;
- (id)url;

@end

