//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CAMReturnArray, CAMReturnBool, CAMReturnDictionary, CAMReturnDouble, CAMReturnInteger, CAMReturnString, CAMReturnVoid, NSDate, NSNumber, NSString;

@protocol CAMCoreMotion

@optional
- (CAMReturnDictionary *)accelerometerData;
- (CAMReturnDouble *)accelerometerUpdateInterval;
- (CAMReturnInteger *)attitudeReferenceFrame;
- (CAMReturnInteger *)availableAttitudeReferenceFrames;
- (CAMReturnString *)createNewPedometer;
- (CAMReturnVoid *)deletePedometer:(NSString *)arg1;
- (CAMReturnDictionary *)deviceMotion;
- (CAMReturnDouble *)deviceMotionUpdateInterval;
- (CAMReturnDictionary *)getLatestQueryResultOnPedometer:(NSString *)arg1;
- (CAMReturnArray *)getPedometerItemsOnPedometer:(NSString *)arg1;
- (CAMReturnDictionary *)gyroData;
- (CAMReturnDouble *)gyroUpdateInterval;
- (CAMReturnBool *)isAccelerometerActive;
- (CAMReturnBool *)isAccelerometerAvailable;
- (CAMReturnBool *)isDeviceMotionActive;
- (CAMReturnBool *)isDeviceMotionAvailable;
- (CAMReturnBool *)isDistanceAvailable;
- (CAMReturnBool *)isFloorCountingAvailable;
- (CAMReturnBool *)isGyroActive;
- (CAMReturnBool *)isGyroAvailable;
- (CAMReturnBool *)isMagnetometerActive;
- (CAMReturnBool *)isMagnetometerAvailable;
- (CAMReturnBool *)isPaceAvailable;
- (CAMReturnBool *)isStepCountingAvailable;
- (CAMReturnDictionary *)magnetometerData;
- (CAMReturnDouble *)magnetometerUpdateInterval;
- (CAMReturnVoid *)queryPedometer:(NSString *)arg1 startingfrom:(NSDate *)arg2 to:(NSDate *)arg3;
- (CAMReturnArray *)queued6AxisData;
- (CAMReturnArray *)queuedAccelerometerData;
- (CAMReturnArray *)queuedAccelerometerErrors;
- (CAMReturnArray *)queuedDeviceMotionErrors;
- (CAMReturnArray *)queuedDeviceMotions;
- (CAMReturnArray *)queuedGyroData;
- (CAMReturnArray *)queuedGyroErrors;
- (CAMReturnArray *)queuedMagnetometerData;
- (CAMReturnArray *)queuedMagnetometerErrors;
- (CAMReturnArray *)resultsFromClearing6AxisData;
- (CAMReturnArray *)resultsFromClearingAccelerometerDataAndErrors;
- (CAMReturnArray *)resultsFromClearingDeviceMotionsAndErrors;
- (CAMReturnArray *)resultsFromClearingGyroDataAndErrors;
- (CAMReturnArray *)resultsFromClearingMagnetometerDataAndErrors;
- (CAMReturnVoid *)setAccelerometerUpdateInterval:(NSNumber *)arg1;
- (CAMReturnVoid *)setDeviceMotionUpdateInterval:(NSNumber *)arg1;
- (CAMReturnVoid *)setGyroUpdateInterval:(NSNumber *)arg1;
- (CAMReturnVoid *)setMagnetometerUpdateInterval:(NSNumber *)arg1;
- (CAMReturnVoid *)startAccelerometerUpdates;
- (CAMReturnVoid *)startAccelerometerUpdatesToQueue;
- (CAMReturnVoid *)startDeviceMotionUpdates;
- (CAMReturnVoid *)startDeviceMotionUpdatesToQueue;
- (CAMReturnVoid *)startDeviceMotionUpdatesToQueueUsingReferenceFrame:(NSNumber *)arg1;
- (CAMReturnVoid *)startDeviceMotionUpdatesUsingReferenceFrame:(NSNumber *)arg1;
- (CAMReturnVoid *)startGyroUpdates;
- (CAMReturnVoid *)startGyroUpdatesToQueue;
- (CAMReturnVoid *)startMagnetometerUpdates;
- (CAMReturnVoid *)startMagnetometerUpdatesToQueue;
- (CAMReturnVoid *)startPedometerUpdates:(NSString *)arg1;
- (CAMReturnVoid *)startSimulatedDeviceMotion:(NSNumber *)arg1;
- (CAMReturnVoid *)startUsing6AxisSensorFusionOnInterval:(NSNumber *)arg1 fsync:(NSNumber *)arg2 bandwidth:(NSNumber *)arg3 useAccelerometer:(NSNumber *)arg4;
- (CAMReturnVoid *)stopAccelerometerUpdates;
- (CAMReturnVoid *)stopDeviceMotionUpdates;
- (CAMReturnVoid *)stopGyroUpdates;
- (CAMReturnVoid *)stopMagnetometerUpdates;
- (CAMReturnVoid *)stopPedometerUpdates:(NSString *)arg1;
- (CAMReturnVoid *)stopSimulatedDeviceMotion;
- (CAMReturnVoid *)stopUsing6AxisSensorFusion;
- (CAMReturnBool *)supportSimulatedDeviceMotion;
@end

