//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CAMReturnArray, CAMReturnBool, CAMReturnCGRect, CAMReturnData, CAMReturnDictionary, CAMReturnDouble, CAMReturnInteger, CAMReturnVoid, NSArray, NSString;

@protocol CAMGraphicsUtilities

@optional
- (CAMReturnDictionary *)appIconsForIdentifiers:(NSArray *)arg1;
- (CAMReturnData *)currentScreenImage;
- (CAMReturnData *)currentStarkScreenImage;
- (CAMReturnData *)currentUnrotatedScreenImage;
- (CAMReturnBool *)isPasscodeRequired;
- (CAMReturnBool *)isScreenLocked;
- (CAMReturnBool *)isScreenOrientationLandscape;
- (CAMReturnBool *)isScreenOrientationPortrait;
- (CAMReturnArray *)pasteboardStrings;
- (CAMReturnCGRect *)screenBounds;
- (CAMReturnInteger *)screenOrientation;
- (CAMReturnDouble *)screenScale;
- (CAMReturnVoid *)sendAppPreferencesChangedWithDomain:(NSString *)arg1 key:(NSString *)arg2;
- (CAMReturnVoid *)setPasteboardString:(NSString *)arg1;
- (CAMReturnInteger *)userInterfaceIdiom;
@end

