//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCondition;
@protocol CAMSocketProtocol, OS_dispatch_queue, OS_dispatch_source;

@interface CAMSocket : NSObject
{
    NSObject<OS_dispatch_queue> *qSocketIO;
    NSObject<OS_dispatch_source> *socketReadSource;
    NSCondition *socketSourceCond;
    BOOL _isConnectionStarted;
    id <CAMSocketProtocol> _delegate;
    CDUnknownBlockType _readHandler;
    CDUnknownBlockType _readEventHandler;
    CDUnknownBlockType _cancelEventHandler;
}

- (void).cxx_destruct;
- (id)alloc_source;
- (unsigned long long)bytesAvailableToRead;
@property(copy) CDUnknownBlockType cancelEventHandler; // @synthesize cancelEventHandler=_cancelEventHandler;
- (void)cancel_source:(id)arg1;
- (unsigned long long)createReadDispatcher;
- (void)dealloc;
@property(retain) id <CAMSocketProtocol> delegate; // @synthesize delegate=_delegate;
- (void)dispatcherStopped;
- (id)initWithDelegate:(id)arg1;
- (void)initializeEventHandlers;
@property BOOL isConnectionStarted; // @synthesize isConnectionStarted=_isConnectionStarted;
- (BOOL)isSocketValid;
@property(copy) CDUnknownBlockType readEventHandler; // @synthesize readEventHandler=_readEventHandler;
@property(copy) CDUnknownBlockType readHandler; // @synthesize readHandler=_readHandler;
- (unsigned long long)recv:(id *)arg1 withMaxLength:(unsigned int)arg2;
- (void)resume_source:(id)arg1;
- (unsigned long long)send:(id)arg1;
- (void)set_cancel_handler:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)set_event_handler:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (unsigned long long)startConnection;
- (unsigned long long)stopConnection;

@end

