//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

@class SAMCoding;

@interface SAMObjectProxy : NSProxy
{
    SAMCoding *simpleCoding;
    BOOL isClassObject;
}

+ (id)objectProxyWithDictionary:(id)arg1 simple:(id)arg2;
- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (id)initWithClassName:(id)arg1 simple:(id)arg2;
- (id)initWithDictionary:(id)arg1 simple:(id)arg2;
- (id)initWithObject:(id)arg1 simple:(id)arg2;
- (BOOL)isKindOfClass:(Class)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
@property(readonly, retain, nonatomic) SAMCoding *simpleCoding; // @synthesize simpleCoding;

@end

