//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSButton, NSString, NSTextField;

@interface _IDETestReportActivities_TableCellView : NSTableCellView
{
    BOOL _isMasterActivity;
    BOOL _containsFailure;
    BOOL _containsCrash;
    BOOL _selected;
    id _assertion;
    NSString *_activityString;
    NSString *_durationString;
    NSTextField *_primaryLabel;
    NSButton *_button;
}

- (void).cxx_destruct;
@property(copy) NSString *activityString; // @synthesize activityString=_activityString;
@property(retain) id assertion; // @synthesize assertion=_assertion;
@property __weak NSButton *button; // @synthesize button=_button;
@property BOOL containsCrash; // @synthesize containsCrash=_containsCrash;
@property BOOL containsFailure; // @synthesize containsFailure=_containsFailure;
@property(copy) NSString *durationString; // @synthesize durationString=_durationString;
@property BOOL isMasterActivity; // @synthesize isMasterActivity=_isMasterActivity;
@property __weak NSTextField *primaryLabel; // @synthesize primaryLabel=_primaryLabel;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;
- (void)setBackgroundStyle:(long long)arg1;

@end

