//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTLanguageSpecification.h>

@interface DVTLanguageSpecification (IBDVTFoundationAdditions)
+ (id)objCAtDynamicSpecification;
+ (id)objCAtSynthesizeSpecification;
+ (id)objCBlockSpecification;
+ (id)objCBracketExpressionSpecification;
+ (id)objCCategoryClauseSpecification;
+ (id)objCCategoryNameSpecification;
+ (id)objCCategoryOpenParenSpecification;
+ (id)objCClassMethodDeclarationSpecification;
+ (id)objCClassMethodImplementationSpecification;
+ (id)objCClassNameSpecification;
+ (id)objCIdentifierSpecification;
+ (id)objCImplementationDeclaratorSpecification;
+ (id)objCImplementationSpecification;
+ (id)objCInstanceMethodDeclarationSpecification;
+ (id)objCInstanceMethodImplementationSpecification;
+ (id)objCInterfaceDeclaratorSpecification;
+ (id)objCInterfaceSpecification;
+ (id)objCParenthesisExpressionSpecification;
+ (id)objCPropertyDeclarationSpecification;
- (BOOL)conformsToAnySpecificationInSet:(id)arg1;
- (BOOL)conformsToSpecification:(id)arg1;
- (BOOL)conformsToSpecificationForIdentifier:(id)arg1;
- (BOOL)isObjCGenericClassMethodSpecification;
- (BOOL)isObjCGenericInstanceMethodSpecification;
- (BOOL)isObjCGenericMethodSpecification;
- (id)specificationLineage;
@end

