//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable, NSMutableArray, NSMutableSet, NSSet;

@interface IDEActivityReportFileIOCoordinator : NSObject
{
    NSMutableArray *_activityReports;
    NSMutableSet *_runningThrottleableActivityReports;
    NSMutableSet *_runningUnthrottleableActivityReports;
    NSMapTable *_activityReportObservations;
}

+ (unsigned long long)assertionBehaviorForKeyValueObservationsAtEndOfEvent;
+ (void)initialize;
+ (id)sharedActivityReportFileIOCoordinator;
- (void).cxx_destruct;
- (CDUnknownBlockType)_activityReportPriorityComparator;
- (unsigned long long)_allowedConcurrentActivities;
- (id)_init;
- (void)_insertSortedActivityReport:(id)arg1;
- (BOOL)_removeSortedActivityReport:(id)arg1;
- (void)_startObservingReport:(id)arg1;
- (void)_stopObservingReport:(id)arg1;
- (void)_throttleActivityReport:(id)arg1 throttleFactor:(double)arg2;
- (void)_updateRunningActivityReports;
@property(readonly) NSArray *activityReports; // @synthesize activityReports=_activityReports;
- (id)init;
@property(readonly) NSSet *runningThrottleableActivityReports; // @synthesize runningThrottleableActivityReports=_runningThrottleableActivityReports;
@property(readonly) NSSet *runningUnthrottleableActivityReports; // @synthesize runningUnthrottleableActivityReports=_runningUnthrottleableActivityReports;
- (void)updateWithAddedActivityReports:(id)arg1;
- (void)updateWithAddedActivityReports:(id)arg1 deletedActivityReports:(id)arg2;

@end

