//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, IDEBatchFindQuery, IDENavigableItemAsyncFilteringCoordinator, NSString;

@interface IDEBatchFindResultUIState : NSObject <DVTInvalidation>
{
    IDENavigableItemAsyncFilteringCoordinator *_navigableItemCoordinator;
    IDEBatchFindQuery *_query;
    long long _resultGroupIndex;
    long long _resultIndex;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)initWithQuery:(id)arg1 navigableItemCoordinator:(id)arg2;
@property(readonly) IDENavigableItemAsyncFilteringCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
- (void)primitiveInvalidate;
@property(retain) IDEBatchFindQuery *query; // @synthesize query=_query;
@property long long resultGroupIndex; // @synthesize resultGroupIndex=_resultGroupIndex;
@property long long resultIndex; // @synthesize resultIndex=_resultIndex;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

