//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/IDEGeniusResultNavigableRepresentedObject-Protocol.h>
#import <IDEKit/IDEKeyDrivenNavigableItemRepresentedObject-Protocol.h>

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, NSImage, NSString, NSURL;

@interface IDECoverageDocumentItem : NSObject <IDEGeniusResultNavigableRepresentedObject, IDEKeyDrivenNavigableItemRepresentedObject>
{
    NSString *_name;
    DVTDocumentLocation *_location;
    DVTFileDataType *_type;
    NSURL *_fileURL;
}

- (void).cxx_destruct;
@property(readonly) DVTDocumentLocation *documentLocation; // @synthesize documentLocation=_location;
- (id)geniusResult_identifierForGeniusCategory;
- (id)geniusResult_identifierForManualCategory;
- (id)initWithName:(id)arg1 originalFileURL:(id)arg2 generatedContentLocation:(id)arg3 type:(id)arg4;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSURL *originalFileURL; // @synthesize originalFileURL=_fileURL;
@property(readonly) DVTFileDataType *type; // @synthesize type=_type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSString *navigableItem_accessibleImageDescription;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) BOOL navigableItem_missingReferencedContentIsImportant;
@property(readonly) BOOL navigableItem_referencedContentExists;
@property(readonly) NSString *navigableItem_subtitle;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

