//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTFileDataType, DVTStackBacktrace, NSMutableArray, NSString;
@protocol IDEEditorDocumentDerivedContentOwner, NSCopying;

@interface IDEEditorDocumentDerivedContentProvider : NSObject <DVTInvalidation>
{
    id <IDEEditorDocumentDerivedContentOwner> _owner;
    NSMutableArray *_registeredClients;
    DVTFileDataType *_derivedContentType;
    id <NSCopying> _derivedContent;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)derivedContent;
- (id)derivedContentType;
- (BOOL)hasClients;
- (id)init;
- (id)initWithOwner:(id)arg1;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (id)owner;
- (void)primitiveInvalidate;
- (void)registerClient:(id)arg1;
- (void)setDerivedContent:(id)arg1 ofType:(id)arg2;
- (void)unregisterClient:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;

@end

