//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class DVTFontAndColorTheme, NSColor, NSFont, NSString;

@protocol IDEFontAndColorItem
- (NSColor *)colorForTheme:(DVTFontAndColorTheme *)arg1;
- (NSString *)displayName;
- (NSFont *)fontForTheme:(DVTFontAndColorTheme *)arg1;
- (void)setColor:(NSColor *)arg1 forTheme:(DVTFontAndColorTheme *)arg2;
- (void)setFont:(NSFont *)arg1 forTheme:(DVTFontAndColorTheme *)arg2;
@end

