//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTLayoutView_ML.h>

#import <IDEKit/DVTInvalidation-Protocol.h>

@class DVTDelayedInvocation, DVTStackBacktrace, NSColor, NSError, NSImageView, NSProgressIndicator, NSString, NSTextView;
@protocol IDEFlightChecking;

@interface IDEFlightCheckView : DVTLayoutView_ML <DVTInvalidation>
{
    DVTDelayedInvocation *_stateUpdatingDelayedInvocation;
    BOOL _blockHidingProgressView;
    BOOL _wantsToHideProgressView;
    int _state;
    int _style;
    id <IDEFlightChecking> _flightCheck;
    NSError *_errorForTooltip;
    NSTextView *_textView;
    NSImageView *_imageView;
    NSProgressIndicator *_progressView;
    NSColor *_textColor;
    DVTDelayedInvocation *_delayedHideProgressView;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(nonatomic) BOOL blockHidingProgressView; // @synthesize blockHidingProgressView=_blockHidingProgressView;
@property(retain, nonatomic) DVTDelayedInvocation *delayedHideProgressView; // @synthesize delayedHideProgressView=_delayedHideProgressView;
@property(retain, nonatomic) NSError *errorForTooltip; // @synthesize errorForTooltip=_errorForTooltip;
- (id)errorImage;
- (id)finishedImage;
@property(readonly, nonatomic) id <IDEFlightChecking> flightCheck; // @synthesize flightCheck=_flightCheck;
- (void)flightCheckStateChanged;
- (void)hideProgress;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1 flightCheck:(id)arg2 style:(int)arg3 textColor:(id)arg4;
- (void)layoutBottomUp;
- (void)layoutTopDown;
- (void)primitiveInvalidate;
@property(retain, nonatomic) NSProgressIndicator *progressView; // @synthesize progressView=_progressView;
@property(nonatomic) int state; // @synthesize state=_state;
@property int style; // @synthesize style=_style;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSTextView *textView; // @synthesize textView=_textView;
- (void)setTitle:(id)arg1;
@property(nonatomic) BOOL wantsToHideProgressView; // @synthesize wantsToHideProgressView=_wantsToHideProgressView;
- (void)showProgress;
- (id)title;
- (void)updateState;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

