//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEKit/NSMenuDelegate-Protocol.h>

@class NSString;

@interface IDESchemeMenuDelegate : NSObject <NSMenuDelegate>
{
    BOOL _needsUpdate;
    id _currentRunContextManagerObservingToken;
}

+ (id)_currentRunContextManager;
- (void).cxx_destruct;
- (id)_schemeMenuItems;
- (void)_selectScheme:(id)arg1;
- (id)init;
- (void)menuNeedsUpdate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

