//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSWindow;

@interface IDETestReportBatchBaselineUpdateWindow : NSWindowController
{
    NSWindow *_owningWindow;
    NSButton *_updateAllTestsButton;
    NSButton *_updateNewTestsButton;
    NSButton *_updateBetterTestsButton;
    NSButton *_updateWorseTestsButton;
    NSButton *_updateSelectedTestsButton;
}

+ (id)defaultViewNibBundle;
+ (id)defaultViewNibName;
- (void).cxx_destruct;
- (void)cancel:(id)arg1;
@property(retain) NSWindow *owningWindow; // @synthesize owningWindow=_owningWindow;
- (unsigned long long)selectedBaselineRecordBehavior;
@property __weak NSButton *updateAllTestsButton; // @synthesize updateAllTestsButton=_updateAllTestsButton;
@property __weak NSButton *updateBetterTestsButton; // @synthesize updateBetterTestsButton=_updateBetterTestsButton;
@property __weak NSButton *updateNewTestsButton; // @synthesize updateNewTestsButton=_updateNewTestsButton;
@property __weak NSButton *updateSelectedTestsButton; // @synthesize updateSelectedTestsButton=_updateSelectedTestsButton;
@property __weak NSButton *updateWorseTestsButton; // @synthesize updateWorseTestsButton=_updateWorseTestsButton;
- (void)update:(id)arg1;
- (void)updateAllTests:(id)arg1;
- (void)updateBetterTests:(id)arg1;
- (void)updateNewTests:(id)arg1;
- (void)updateSelectedTests:(id)arg1;
@property(readonly, nonatomic) BOOL updateSelectedTestsInReport;
- (void)updateWorseTests:(id)arg1;
- (void)windowDidLoad;

@end

