//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTKit/DVTOnboardingPage.h>

#import <DVTKit/NSTextFieldDelegate-Protocol.h>

@class NSButton, NSSecureTextField, NSString, NSTextField;

@interface DVTOnboardingTutorialAddAppleID : DVTOnboardingPage <NSTextFieldDelegate>
{
    NSTextField *_appleIDField;
    NSSecureTextField *_passwordField;
    NSButton *_forgotPasswordButton;
    NSTextField *_errorField;
    NSButton *_createAppleIDButton;
}

- (void).cxx_destruct;
- (id)_accountWithAppleID:(id)arg1 password:(id)arg2;
- (void)appleIDAction:(id)arg1;
@property __weak NSTextField *appleIDField; // @synthesize appleIDField=_appleIDField;
- (void)controlTextDidChange:(id)arg1;
- (void)createAppleIDAction:(id)arg1;
@property(retain) NSButton *createAppleIDButton; // @synthesize createAppleIDButton=_createAppleIDButton;
@property __weak NSTextField *errorField; // @synthesize errorField=_errorField;
- (void)forgotAppleIDAction:(id)arg1;
@property __weak NSButton *forgotPasswordButton; // @synthesize forgotPasswordButton=_forgotPasswordButton;
- (void)passwordAction:(id)arg1;
@property __weak NSSecureTextField *passwordField; // @synthesize passwordField=_passwordField;
- (BOOL)readyForNextPage;
- (void)viewDidAppear;
- (void)viewDidLoad;
- (BOOL)willNavigateToNextPage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

