//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DVTObjectLiteral : NSObject
{
    BOOL _showsEditorString;
    unsigned long long _type;
    id _representedObject;
}

+ (id)objectLiteralForObject:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)editorString;
- (id)initWithType:(unsigned long long)arg1 representedObject:(id)arg2;
@property(retain) id representedObject; // @synthesize representedObject=_representedObject;
@property BOOL showsEditorString; // @synthesize showsEditorString=_showsEditorString;
@property unsigned long long type; // @synthesize type=_type;

@end

