//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <DVTKit/DVTInvalidation-Protocol.h>
#import <DVTKit/NSAnimationDelegate-Protocol.h>
#import <DVTKit/NSTableViewDataSource-Protocol.h>
#import <DVTKit/NSTableViewDelegate-Protocol.h>

@class DVTBorderedView, DVTDelayedInvocation, DVTObservingToken, DVTStackBacktrace, DVTTextCompletionSession, DVTTextCompletionWindowResizeAnimation, DVTViewController, NSDictionary, NSScrollView, NSString, NSTableColumn, NSTableView, NSTextField, NSViewAnimation;
@protocol DVTInvalidation;

@interface DVTTextCompletionListWindowController : NSWindowController <DVTInvalidation, NSTableViewDataSource, NSTableViewDelegate, NSAnimationDelegate>
{
    NSTextField *_messagesField;
    NSTableView *_completionsTableView;
    NSTableColumn *_iconColumn;
    NSTableColumn *_typeColumn;
    NSTableColumn *_titleColumn;
    NSScrollView *_completionsScrollView;
    DVTBorderedView *_quickHelpView;
    DVTBorderedView *_divider;
    DVTTextCompletionSession *_session;
    struct CGRect _referenceFrameInView;
    DVTTextCompletionWindowResizeAnimation *_resizeAnimation;
    NSViewAnimation *_fadeOutAnimation;
    DVTObservingToken *_sessionCompletionsObserver;
    DVTObservingToken *_sessionSelectionObserver;
    NSDictionary *_selectedTitleCellAttributes;
    NSDictionary *_selectedTypeCellAttributes;
    DVTViewController<DVTInvalidation> *_infoContentViewController;
    int _hideReason;
    BOOL _showingWindow;
    BOOL _shouldIgnoreSelectionChange;
    BOOL _quickHelpOnTop;
    DVTDelayedInvocation *_delayedQuickHelpClearing;
    DVTBorderedView *_contentView;
    NSTableColumn *_leftPaddingColumn;
}

+ (id)_nonSelectedTitleColor;
+ (id)_nonSelectedTypeColor;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_doubleClickOnRow:(id)arg1;
- (void)_getTitleColumnWidth:(double *)arg1 typeColumnWidth:(double *)arg2;
- (void)_hideWindow;
- (void)_loadColorsFromCurrentTheme;
- (id)_messageTextAttributes;
- (id)_notRecommendedAttributes;
- (struct CGRect)_preferredWindowFrameForTextFrame:(struct CGRect)arg1 columnsWidth:(double *)arg2 titleColumnX:(double)arg3;
- (void)_removeQuickHelpView;
- (id)_selectedCompletionItem;
- (void)_startDelayedAnimation;
- (void)_themeColorsChanged:(id)arg1;
- (void)_updateCurrentDisplayState;
- (void)_updateCurrentDisplayStateForQuickHelp;
- (void)_updateInfoNewSelection;
- (void)_updateInfoPaneForCompletionItem:(id)arg1 andViewController:(id)arg2;
- (void)_updateSelectedRow;
- (void)animationDidEnd:(id)arg1;
- (void)animationDidStop:(id)arg1;
- (void)close;
@property(readonly) NSScrollView *completionsScrollView; // @synthesize completionsScrollView=_completionsScrollView;
@property __weak DVTBorderedView *contentView; // @synthesize contentView=_contentView;
@property(readonly) NSString *debugStateString;
@property(nonatomic) int hideReason; // @synthesize hideReason=_hideReason;
- (void)hideWindowWithReason:(int)arg1;
- (id)initWithSession:(id)arg1;
@property __weak NSTableColumn *leftPaddingColumn; // @synthesize leftPaddingColumn=_leftPaddingColumn;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)primitiveInvalidate;
@property(readonly) DVTTextCompletionSession *session; // @synthesize session=_session;
- (BOOL)showInfoForSelectedCompletionItem;
- (void)showInfoPaneForCompletionItem:(id)arg1;
- (void)showWindowForTextFrame:(struct CGRect)arg1 explicitAnimation:(BOOL)arg2;
@property(readonly) BOOL showingWindow; // @synthesize showingWindow=_showingWindow;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)window;
- (void)windowDidLoad;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

