//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTKit/NSAnimationDelegate-Protocol.h>

@class DVTSourceTextView, DVTWeakInterposer, NSAnimation, NSString;

@interface DVTTextVisualization : NSObject <NSAnimationDelegate>
{
    DVTWeakInterposer *_textView_dvtWeakInterposer;
    NSAnimation *_fadeAnimation;
    double _opacity;
    unsigned long long _drawOrdering;
}

+ (unsigned long long)defaultDrawOrdering;
- (void).cxx_destruct;
- (void)animationDidEnd:(id)arg1;
@property(readonly) struct CGRect bounds;
@property unsigned long long drawOrdering; // @synthesize drawOrdering=_drawOrdering;
- (void)drawOverTextInRect:(struct CGRect)arg1;
- (void)drawUnderCurrentLineHighlightInRect:(struct CGRect)arg1;
- (void)drawUnderTextInRect:(struct CGRect)arg1;
- (void)fadeToOpacity:(double)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)init;
- (void)mouseMoved:(id)arg1;
@property(nonatomic) double opacity; // @synthesize opacity=_opacity;
- (void)resetCursorRects;
@property(retain) DVTSourceTextView *textView;
- (BOOL)trackMouse:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

