//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTSourceControl/DVTSourceControlPlugInCallbackProtocol-Protocol.h>

@class NSMutableDictionary, NSOperationQueue, NSSet, NSString, NSXPCConnection;
@protocol DVTSourceControlAuthenticationFailureHandler, OS_dispatch_queue;

@interface DVTSourceControlManager : NSObject <DVTSourceControlPlugInCallbackProtocol>
{
    NSXPCConnection *_sshHelperConnection;
    NSXPCConnection *_workingCopyScannerConnection;
    NSOperationQueue *_sourceControlOperationQueue;
    NSMutableDictionary *_currentOperations;
    NSObject<OS_dispatch_queue> *_currentOperationsChangeQueue;
    NSMutableDictionary *_plugInConnections;
    NSObject<OS_dispatch_queue> *_plugInConnectionsChangeQueue;
    id <DVTSourceControlAuthenticationFailureHandler> _failureHandler;
    NSSet *_cachedSourceControlSystems;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_allPlugInIdentifiers;
- (id)_init;
- (id)_plugInConntectionForPlugInIdentifier:(id)arg1 UUIDString:(id)arg2;
- (id)addBranch:(id)arg1 fromBranch:(id)arg2 toRepository:(id)arg3 branchAndTagLocations:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)addFiles:(id)arg1 inWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)addOperation:(id)arg1;
- (id)addRemoteRepository:(id)arg1 withName:(id)arg2 toRepository:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)ancestorRevisionInRepository:(id)arg1 ofBranch:(id)arg2 otherBranch:(id)arg3 branchAndTagLocations:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)automaticallyDetectBranchAndTagLocationsForRepository:(id)arg1 fromPath:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)baseRevisionOfWorkingCopy:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)blameFile:(id)arg1 inWorkingCopy:(id)arg2 fromRevisionLocation:(id)arg3 ignoreWhitespace:(BOOL)arg4 completionBlock:(CDUnknownBlockType)arg5;
@property(retain) NSSet *cachedSourceControlSystems; // @synthesize cachedSourceControlSystems=_cachedSourceControlSystems;
- (void)cancelAllOperations;
- (id)commitDetails:(id)arg1 revisions:(id)arg2 incrementalLogBlock:(CDUnknownBlockType)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)commitDetailsWithParents:(id)arg1 forRevision:(id)arg2 path:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)commitFiles:(id)arg1 inWorkingCopy:(id)arg2 message:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)copyFiles:(id)arg1 toFilePaths:(id)arg2 inWorkingCopy:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)createDirectory:(id)arg1 withIntermediateDirectories:(BOOL)arg2 attributes:(id)arg3 inWorkingCopy:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)createRepositoryAtFileURL:(id)arg1 withSystem:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)createWorkingCopyFromRepository:(id)arg1 atURL:(id)arg2 existingWorkingCopyURL:(id)arg3 location:(id)arg4 branchAndTagLocations:(id)arg5 useRevision:(BOOL)arg6 progressBlock:(CDUnknownBlockType)arg7 completionBlock:(CDUnknownBlockType)arg8;
- (id)currentLocationOfWorkingCopy:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)defaultSSHKeyAuthenticationStrategyForURL:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)diffRepository:(id)arg1 fromLocation:(id)arg2 againstLocation:(id)arg3 branchAndTagLocations:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)discardAllChangesInWorkingCopy:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)discardChangesInFiles:(id)arg1 inWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)downloadUpdatesFromRemoteRepository:(id)arg1 toRepository:(id)arg2 progressBlock:(CDUnknownBlockType)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)exportFile:(id)arg1 inWorkingCopy:(id)arg2 fromRevisionLocation:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)exportFileWithParent:(id)arg1 path:(id)arg2 revision:(id)arg3 status:(unsigned long long)arg4 completionBlock:(CDUnknownBlockType)arg5;
@property(retain) id <DVTSourceControlAuthenticationFailureHandler> failureHandler; // @synthesize failureHandler=_failureHandler;
- (id)filesAndStatusOfWorkingCopy:(id)arg1 withRemoteStatus:(BOOL)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)forceUpdateWorkingCopy:(id)arg1 fromRepository:(id)arg2 progressBlock:(CDUnknownBlockType)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)generateSSHKeysWithPassphrase:(id)arg1 comment:(id)arg2 inFolder:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)generateSSHKeysWithPassphrase:(id)arg1 inFolder:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)headRevisionOfRepository:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)historyOfFile:(id)arg1 inWorkingCopy:(id)arg2 searchString:(id)arg3 searchType:(unsigned long long)arg4 showMergeCommits:(BOOL)arg5 incrementalLogBlock:(CDUnknownBlockType)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)historyOfFileWithNameStatus:(id)arg1 inWorkingCopy:(id)arg2 fromRevisionLocation:(id)arg3 showMergeCommits:(BOOL)arg4 follow:(BOOL)arg5 maxLogItems:(long long)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (id)historyOfWorkingCopy:(id)arg1 fromRevision:(id)arg2 toRevision:(id)arg3 inclusionType:(unsigned long long)arg4 maximumLogItems:(long long)arg5 searchString:(id)arg6 searchType:(unsigned long long)arg7 includeFilePaths:(BOOL)arg8 showMergeCommits:(BOOL)arg9 incrementalLogBlock:(CDUnknownBlockType)arg10 completionBlock:(CDUnknownBlockType)arg11;
- (void)incrementalLogStatus:(id)arg1 info:(id)arg2 progressIdentifier:(id)arg3;
- (id)init;
- (void)invalidateProcessForOperation:(id)arg1 withForce:(BOOL)arg2;
- (id)keychainNameFromURL:(id)arg1 forSystem:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)knownSSHHostsAndFingerprintsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)listBranchesOfRepository:(id)arg1 branchAndTagLocations:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)listRemoteBranchesOfRepository:(id)arg1 branchAndTagLocations:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)listRemoteRepositoriesForRepository:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)listSubpathsOfRepository:(id)arg1 atPath:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)markAsResolvedFiles:(id)arg1 inWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)mergeBranch:(id)arg1 intoWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)moveFiles:(id)arg1 toFilePaths:(id)arg2 inWorkingCopy:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)operationDidFinish:(id)arg1;
- (void)operationDidStart:(id)arg1;
- (id)operationForConnection:(id)arg1;
- (id)parentBranchesOfBranch:(id)arg1 inRepository:(id)arg2 branchAndTagLocations:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)progressStatus:(long long)arg1 withDictionary:(id)arg2 progressIdentifier:(id)arg3;
- (id)remoteBranchFromRepository:(id)arg1 forBranch:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)remoteProxyObjectForPlugInIdentifier:(id)arg1 operation:(id)arg2;
- (id)remoteProxyObjectForSSHKeyGeneration;
- (id)remoteProxyObjectForSourceControlSystem:(id)arg1 operation:(id)arg2;
- (id)remoteProxyObjectForWorkingCopyScanning;
- (id)removeBranch:(id)arg1 fromRepository:(id)arg2 andRemoteRepository:(id)arg3 branchAndTagLocations:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)removeFiles:(id)arg1 inWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)removeRemoteRepositoryNamed:(id)arg1 fromRepository:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)revisionOfLocation:(id)arg1 inRepository:(id)arg2 branchAndTagLocations:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)scanForWorkingCopiesInFolderPaths:(id)arg1 traversingUp:(BOOL)arg2 usingSourceControlSystems:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)sourceControlSystemsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)switchLocation:(id)arg1 ofWorkingCopy:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)systemWithIdentifer:(id)arg1;
- (id)updateIdentifierOfRepositoryForWorkingCopy:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)updateRepositoryURLRootForRepository:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)upgradeWorkingCopy:(id)arg1 progressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)uploadCommitsToRemoteRepository:(id)arg1 fromLocalRepository:(id)arg2 remoteBranch:(id)arg3 progressBlock:(CDUnknownBlockType)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)uploadPublicSSHKeyFromFolder:(id)arg1 toServer:(id)arg2 forUsername:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)validateAuthenticationOfRepository:(id)arg1 location:(id)arg2 branchAndTagLocations:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)validateSSHKeysWithPrivateKeyURL:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

