//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTSourceControl/DVTSourceControlSerializable-Protocol.h>
#import <DVTSourceControl/NSCopying-Protocol.h>
#import <DVTSourceControl/NSSecureCoding-Protocol.h>

@class DVTSourceControlPathLocation, NSString;

@interface DVTSourceControlBranchAndTagLocations : NSObject <DVTSourceControlSerializable, NSSecureCoding, NSCopying>
{
    DVTSourceControlPathLocation *_relativePrimaryBranchLocation;
    DVTSourceControlPathLocation *_relativeBranchesLocation;
    DVTSourceControlPathLocation *_relativeTagsLocation;
}

+ (id)locationsWithPrimaryBranchPath:(id)arg1 branchesPath:(id)arg2 tagsPath:(id)arg3;
+ (id)locationsWithStandardLayout;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)dictionaryRepresentationWithOptions:(unsigned long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
@property(readonly, getter=isCompleteForBranches) BOOL completeForBranches;
@property(readonly, getter=isCompleteForTags) BOOL completeForTags;
@property(copy) DVTSourceControlPathLocation *relativeBranchesLocation; // @synthesize relativeBranchesLocation=_relativeBranchesLocation;
@property(copy) DVTSourceControlPathLocation *relativePrimaryBranchLocation; // @synthesize relativePrimaryBranchLocation=_relativePrimaryBranchLocation;
@property(copy) DVTSourceControlPathLocation *relativeTagsLocation; // @synthesize relativeTagsLocation=_relativeTagsLocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

