//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DNTDocumentationSupport/_TtC23DNTDocumentationSupport18DocumentationStore.h>

@interface _TtC23DNTDocumentationSupport25IndexedDocumentationStore : _TtC23DNTDocumentationSupport18DocumentationStore
{
    // Error parsing type: , name: documentationIndex
    // Error parsing type: , name: lookupMap
}

@end

