//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GPUToolsServices/DYAnalyzerFinding.h>

@interface DYAnalyzerErrorFinding : DYAnalyzerFinding
{
    unsigned int _functionEnum;
}

- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) unsigned int functionEnum; // @synthesize functionEnum=_functionEnum;
- (id)initWithCoder:(id)arg1;
- (id)initWithFunctionEnum:(unsigned int)arg1;
- (BOOL)isBufferDataCompletelyUpdated;
- (BOOL)isDataRestoreUnnecessaryForFunc:(const struct Function *)arg1 targetArgIndex:(int)arg2 objectType:(unsigned int)arg3 analyzerEngine:(id)arg4;
- (BOOL)isFrameStatistics;
- (BOOL)isInefficientStateUpdate;
- (BOOL)isRedundantCall;
- (BOOL)isRedundantCallOrQuery;
- (BOOL)isTextureImageCompletelyUpdated;

@end

