//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

@interface _TtC23DNTDocumentationSupport22DocumentationLookupMap : SwiftObject
{
    // Error parsing type: , name: mapDatabasePathURL
    // Error parsing type: , name: logCategory
    // Error parsing type: , name: database
    // Error parsing type: , name: referencePathSelectStatements
    // Error parsing type: , name: languageSwapSelectStatements
    // Error parsing type: , name: insertStatement
    // Error parsing type: , name: isReadOnly
}

@end

