//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <ModelIO/NSCopying-Protocol.h>
#import <ModelIO/NSFastEnumeration-Protocol.h>

@class MDLVertexDescriptor, NSMutableArray, NSURL;
@protocol MDLMeshBufferAllocator, MDLObjectContainerComponent;

@interface MDLAsset : NSObject <NSCopying, NSFastEnumeration>
{
    NSURL *_URL;
    NSMutableArray *_objects;
    id <MDLObjectContainerComponent> _masters;
    double _startTime;
    double _endTime;
    double _frameInterval;
    id <MDLMeshBufferAllocator> _bufferAllocator;
    MDLVertexDescriptor *_vertexDescriptor;
}

+ (BOOL)canExportFileExtension:(id)arg1;
+ (BOOL)canImportFileExtension:(id)arg1;
+ (id)placeLightProbesWithDensity:(float)arg1 heuristic:(long long)arg2 usingIrradianceDataSource:(id)arg3;
- (void).cxx_destruct;
@property(readonly, retain, nonatomic) NSURL *URL;
@property(readonly, nonatomic) struct MDLAABB _bounds;
- (void)_commonInit;
- (void)addObject:(id)arg1;
@property(readonly, nonatomic) struct boundingBox;
- (struct)boundingBoxAtTime:(double)arg1;
@property(readonly, retain, nonatomic) id <MDLMeshBufferAllocator> bufferAllocator; // @synthesize bufferAllocator=_bufferAllocator;
- (id)childObjectsOfClass:(Class)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) unsigned long long count;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
@property(nonatomic) double endTime;
- (void)enumerateChildObjectsOfClass:(Class)arg1 usingBlock:(CDUnknownBlockType)arg2 stopPointer:(char *)arg3;
- (BOOL)exportAssetToURL:(id)arg1;
- (BOOL)exportAssetToURL:(id)arg1 error:(id *)arg2;
@property(nonatomic) double frameInterval; // @synthesize frameInterval=_frameInterval;
- (id)init;
- (id)initWithBufferAllocator:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithURL:(id)arg1 vertexDescriptor:(id)arg2 bufferAllocator:(id)arg3;
- (id)initWithURL:(id)arg1 vertexDescriptor:(id)arg2 bufferAllocator:(id)arg3 preserveTopology:(BOOL)arg4 error:(id *)arg5;
@property(retain, nonatomic) id <MDLObjectContainerComponent> masters; // @synthesize masters=_masters;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objects;
- (void)removeObject:(id)arg1;
@property(nonatomic) double startTime;
@property(readonly, retain, nonatomic) MDLVertexDescriptor *vertexDescriptor; // @synthesize vertexDescriptor=_vertexDescriptor;

@end

