//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreAutomation/CAMUSBController.h>

#import <CoreAutomation/CAMCambrionixProtocol-Protocol.h>

@class CAMSerialPort, NSNumber, NSString;

@interface CAMCambrionixUSBController : CAMUSBController <CAMCambrionixProtocol>
{
    NSString *serialPath;
    CAMSerialPort *serialConnection;
    BOOL serialConnected;
    BOOL firmwareVerified;
    NSNumber *numberOfPorts;
}

+ (id)getAliasFile;
+ (int)highPowerChargeForProduct:(unsigned int)arg1 atPower:(unsigned short)arg2;
- (void).cxx_destruct;
- (id)charge;
- (id)chargePort:(unsigned long long)arg1;
- (id)chargePort:(unsigned long long)arg1 withDelay:(unsigned long long)arg2;
- (id)chargePorts:(id)arg1;
- (id)chargePorts:(id)arg1 withDelay:(unsigned long long)arg2;
- (id)checkPorts:(id)arg1;
- (void)close;
- (id)command:(id)arg1 flush:(BOOL)arg2 prompts:(id)arg3;
- (id)commandImplementation:(id)arg1;
- (id)connectAll;
- (id)connectPort:(unsigned long long)arg1;
- (id)connectPort:(unsigned long long)arg1 withDelay:(unsigned long long)arg2;
- (id)connectPorts:(id)arg1;
- (id)connectPorts:(id)arg1 withDelay:(unsigned long long)arg2;
- (void)dealloc;
- (id)disconnectAll;
- (id)disconnectPort:(unsigned long long)arg1;
- (id)disconnectPort:(unsigned long long)arg1 withDelay:(unsigned long long)arg2;
- (id)disconnectPorts:(id)arg1;
- (id)disconnectPorts:(id)arg1 withDelay:(unsigned long long)arg2;
- (id)findFirmwareVersion:(id)arg1 pattern:(id)arg2;
@property BOOL firmwareVerified; // @synthesize firmwareVerified;
- (id)firmwareVersion;
- (void)flush;
- (id)getAddress;
- (id)getAlias;
- (long long)getNumberOfPorts;
- (void)info;
- (id)initWithAddress:(id)arg1 numberOfPorts:(long long)arg2 error:(id *)arg3;
@property(readonly) __weak NSNumber *numberOfPorts; // @synthesize numberOfPorts;
- (void)open;
- (id)port:(unsigned long long)arg1 state:(unsigned long long)arg2;
- (id)ports:(id)arg1 state:(unsigned long long)arg2;
- (id)ports:(id)arg1 state:(unsigned long long)arg2 withDelay:(unsigned long long)arg3;
- (id)restartFirmware;
@property(readonly) __weak NSString *serialPath; // @synthesize serialPath;
- (id)serialReadBuffer;
- (id)serialWriteBuffer;
- (id)stringInfo;
- (id)whereAmI;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

