//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CAMFileRelayConnection : NSObject
{
    struct _AMDServiceConnection *service;
}

+ (id)connectionWithAMDConnection:(id)arg1;
+ (BOOL)retrieveSource:(id)arg1 toLocation:(id)arg2 withAMDConnection:(id)arg3;
+ (BOOL)retrieveSources:(id)arg1 toLocation:(id)arg2 withAMDConnection:(id)arg3;
- (void)dealloc;
- (void)disconnect;
- (id)initWithAMDConnection:(id)arg1;
- (BOOL)receiveAtPath:(id)arg1 onSocket:(long long)arg2;
- (id)receiveDictOnSocket:(long long)arg1;
- (BOOL)retrieveSource:(id)arg1 toLocation:(id)arg2;
- (BOOL)retrieveSources:(id)arg1 toLocation:(id)arg2;
- (BOOL)sendDict:(id)arg1 onSocket:(long long)arg2;

@end

