//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CAMReturnArray, CAMReturnAsynchronousShellTask, CAMReturnBool, CAMReturnDictionary, CAMReturnDouble, CAMReturnShellTask, CAMReturnString, CAMReturnVoid, NSArray, NSDictionary, NSNumber, NSString;

@protocol CAMShell

@optional
- (CAMReturnArray *)contentsOfDirectoryAtPath:(NSString *)arg1;
- (CAMReturnArray *)contentsOfDirectoryAtPath:(NSString *)arg1 recursively:(NSNumber *)arg2;
- (CAMReturnDictionary *)contentsOfDirectoryAtPath:(NSString *)arg1 recursively:(NSNumber *)arg2 includingPropertiesForKeys:(NSArray *)arg3 options:(NSNumber *)arg4;
- (CAMReturnBool *)copyItemAtPath:(NSString *)arg1 toPath:(NSString *)arg2;
- (CAMReturnBool *)createDirectoryAtPath:(NSString *)arg1 withIntermediateDirectories:(NSNumber *)arg2 attributes:(NSDictionary *)arg3;
- (CAMReturnString *)destinationOfSymbolicLinkAtPath:(NSString *)arg1;
- (CAMReturnBool *)directoryExistsAtPath:(NSString *)arg1;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3 withTimeout:(NSNumber *)arg4;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3 withTimeout:(NSNumber *)arg4 updates:(void (^)(NSString *, NSString *))arg5 completion:(void (^)(void))arg6;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2 withTimeout:(NSNumber *)arg3;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 arguments:(NSArray *)arg2 withTimeout:(NSNumber *)arg3 updates:(void (^)(NSString *, NSString *))arg4 completion:(void (^)(void))arg5;
- (CAMReturnShellTask *)executeCommand:(NSString *)arg1 updates:(void (^)(NSString *, NSString *))arg2 completion:(void (^)(void))arg3;
- (CAMReturnShellTask *)executeShellCommand:(NSString *)arg1;
- (CAMReturnShellTask *)executeShellCommand:(NSString *)arg1 updates:(void (^)(NSString *, NSString *))arg2 completion:(void (^)(void))arg3;
- (CAMReturnBool *)fileExistsAtPath:(NSString *)arg1;
- (CAMReturnAsynchronousShellTask *)launchedNoHUPTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2;
- (CAMReturnAsynchronousShellTask *)launchedNoHUPTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3;
- (CAMReturnAsynchronousShellTask *)launchedNoHUPTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3 updates:(void (^)(NSString *, NSString *))arg4 completion:(void (^)(void))arg5;
- (CAMReturnAsynchronousShellTask *)launchedNoHUPTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 updates:(void (^)(NSString *, NSString *))arg3 completion:(void (^)(void))arg4;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 environment:(NSDictionary *)arg3 updates:(void (^)(NSString *, NSString *))arg4 completion:(void (^)(void))arg5;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1 arguments:(NSArray *)arg2 updates:(void (^)(NSString *, NSString *))arg3 completion:(void (^)(void))arg4;
- (CAMReturnAsynchronousShellTask *)launchedTaskWithCommand:(NSString *)arg1 updates:(void (^)(NSString *, NSString *))arg2 completion:(void (^)(void))arg3;
- (CAMReturnVoid *)markLogWithString:(NSString *)arg1;
- (CAMReturnBool *)moveItemAtPath:(NSString *)arg1 toPath:(NSString *)arg2;
- (CAMReturnArray *)pathsToAllCrashLogs;
- (CAMReturnArray *)pathsToCrashLogsInDirectory:(NSString *)arg1;
- (CAMReturnVoid *)postDistributedNotificationNamed:(NSString *)arg1 payload:(NSDictionary *)arg2;
- (CAMReturnVoid *)registerForDistributedNotificationsNamed:(NSString *)arg1 sender:(NSString *)arg2;
- (CAMReturnBool *)removeItemAtPath:(NSString *)arg1;
- (CAMReturnArray *)retrieveAllDistributedNotifications;
- (CAMReturnAsynchronousShellTask *)signalTaskWithUUID:(NSString *)arg1 withSignal:(NSNumber *)arg2;
- (CAMReturnVoid *)sleep;
- (CAMReturnVoid *)sleepForCycles:(NSNumber *)arg1 secondsToSleep:(NSNumber *)arg2 secondsToRemainAwake:(NSNumber *)arg3;
- (CAMReturnAsynchronousShellTask *)statusOfTaskWithUUID:(NSString *)arg1;
- (CAMReturnAsynchronousShellTask *)statusOfTaskWithUUID:(NSString *)arg1 resetOutput:(NSNumber *)arg2;
- (CAMReturnVoid *)terminateAllTasks;
- (CAMReturnAsynchronousShellTask *)terminateTaskWithUUID:(NSString *)arg1;
- (CAMReturnDouble *)timeIntervalSinceReferenceDate;
- (CAMReturnVoid *)unregisterForDistributedNotifications;
- (CAMReturnArray *)versionInformation;
- (CAMReturnArray *)waitForAndRetrieveDistributedNotificationsWithTimeout:(NSNumber *)arg1;
@end

