//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableData.h>

@interface DYVMBuffer : NSMutableData
{
    struct VMBuffer *_vmBuffer;
}

- (const void *)bytes;
- (void)dealloc;
- (id)initWithCapacity:(unsigned long long)arg1;
- (id)initWithLength:(unsigned long long)arg1;
- (id)initWithVMBuffer:(struct VMBuffer *)arg1;
- (unsigned long long)length;
- (void *)mutableBytes;
- (void)setLength:(unsigned long long)arg1;
- (id)subdataWithRange:(struct _NSRange)arg1;
@property(readonly, nonatomic) struct VMBuffer *vmBuffer; // @synthesize vmBuffer=_vmBuffer;

@end

