//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableArray.h>

@interface NSMutableArray (XCEConfigurableDataNodeArrayExtensions)
- (void)XCE_insertObject:(id)arg1 inArraySortedUsingComparator:(CDUnknownBlockType)arg2;
- (void)XCE_insertObject:(id)arg1 inArraySortedUsingSelector:(SEL)arg2;
- (void)XCE_insertObjects:(id)arg1 inArraySortedUsingComparator:(CDUnknownBlockType)arg2;
- (void)XCE_insertObjects:(id)arg1 inArraySortedUsingSelector:(SEL)arg2;
@end

