//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (PBXTextExtras)
- (struct _NSRange)PBX_characterRangeFromLineNumberRange:(struct _NSRange)arg1;
- (struct _NSRange)PBX_lineNumberRangeFromCharacterRange:(struct _NSRange)arg1;
- (id)PBX_stringByStandardizingEndOfLineToCR;
- (id)PBX_stringByStandardizingEndOfLineToCRLF;
- (id)PBX_stringByStandardizingEndOfLineToLF;
- (id)PBX_stringByStandardizingEndOfLineToLineSeparator;
- (id)PBX_stringByStandardizingEndOfLineToParagraphSeparator;
@end

