//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXPreferencesPaneModule.h>

@class NSButton, NSButtonCell, NSColor, NSColorWell, NSMatrix, NSMutableArray, NSPopUpButton, NSTextField, NSUserDefaultsController, PBXTextAttributesController;

@interface PBXDebuggerPrefsModule : PBXPreferencesPaneModule
{
    NSUserDefaultsController *_userDefaultsController;
    NSMutableArray *_controllerList;
    NSPopUpButton *_debuggerFontTypePopUp;
    NSColorWell *_debuggerFontColorWell;
    NSTextField *_debuggerFontTextField;
    NSButton *_debuggerFontSetButton;
    NSColorWell *_textHighlightColorWell;
    PBXTextAttributesController *_activeTextAttributeController;
    NSColor *_textHighlightBaseColor;
    NSPopUpButton *_debuggerClosePolicyPopUp;
    NSPopUpButton *_debuggerOpenPolicyPopUp;
    NSTextField *_gdbLogFileTextField;
    NSButton *_openLogButton;
    NSButton *_loadSymbolsLazilyCheckBox;
    NSButtonCell *_disassemblyATT;
    NSButtonCell *_disassemblyIntel;
    NSMatrix *_disassemblyMatrix;
    NSTextField *_disassemblyStyleText;
    NSButton *_autoClearLogsCheckBox;
}

+ (int)onGoAction;
+ (BOOL)useAlternateDisassemblyStyle;
- (void)awakeFromNib;
- (void)changeFont:(id)arg1;
- (void)checkBoxAction:(id)arg1;
- (void)colorWellAction:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)dealloc;
- (void)fontAction:(id)arg1;
- (id)init;
- (void)initializeFromDefaults;
- (struct CGSize)minModuleSize;
- (void)noteChange:(id)arg1;
- (void)openLogAction:(id)arg1;
- (void)popUpAction:(id)arg1;
- (void)saveChanges;
- (void)textHighlightColorWellAction:(id)arg1;
- (void)toggleDisassemblyStyleAction:(id)arg1;
- (void)update;
- (void)updateFontDescriptionString;

@end

