//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXDebugViewModule.h>

@class NSView, PBXModule;

@interface PBXDebugProcessAndThreadModule : PBXDebugViewModule
{
    NSView *_topArea;
    NSView *_bottomArea;
    PBXModule *_topModule;
    PBXModule *_bottomModule;
}

- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithModuleNibName:(id)arg1;
- (BOOL)moduleEnforcesViewMinSize;
- (void)setModuleForBottomArea:(id)arg1;
- (void)setModuleForTopArea:(id)arg1;
- (void)viewDidLoad;
- (struct CGSize)viewMinSize;

@end

