//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXProjectWizard.h>

@interface PBXEmptyProjectWizard : PBXProjectWizard
{
}

+ (id)categorizedWizardName;
+ (id)defaultModuleNibName;
+ (id)icon;
+ (id)wizardDescription;
- (id)_instantiateTemplateWithContext:(id)arg1;
- (id)_listOfFilesToCopy;
- (id)initWithSettings:(id)arg1 parentPage:(id)arg2 nextPage:(id)arg3 parentNextPageSelector:(SEL)arg4;

@end

