//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXLSModel.h>

@class NSString;

@interface PBXLSThreadGroup : PBXLSModel
{
    NSString *_name;
}

- (void)dealloc;
- (void)debugger:(id)arg1 addThread:(id)arg2;
- (void)debugger:(id)arg1 removeThread:(id)arg2;
- (void)debugger:(id)arg1 setName:(id)arg2;
- (void)debuggerDelete:(id)arg1;
- (id)displayName;
- (id)initWithDebugger:(id)arg1;
- (id)name;
- (id)parentProcess;
- (id)threads;

@end

