//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <DevToolsInterface/PBXProjectWatcherServerProtocol-Protocol.h>

@class NSConnection, NSMapTable, NSMutableArray;

@interface PBXProjectWatcherManager : NSObject <PBXProjectWatcherServerProtocol>
{
    NSConnection *_vendedConnection;
    NSMapTable *_connectionToProxyMap;
    NSMutableArray *_projectObservers;
    NSMapTable *_targetObservers;
    NSMapTable *_fileObservers;
    NSMapTable *_projectFileObservers;
    NSMapTable *_targetFileObservers;
    BOOL _observingProjectNotes;
    BOOL _observingTargetNotes;
    BOOL _observingProjectFileNotes;
    BOOL _observingTargetFileNotes;
}

+ (id)sharedProjectWatcherManager;
- (void)_activeTargetDidChange:(id)arg1;
- (void)_connectionDidDie:(id)arg1;
- (id)_insertionGroupNearFile:(id)arg1 inProject:(id)arg2 preferredGroupName:(id)arg3;
- (void)_notifyFileObserversForFile:(id)arg1 project:(id)arg2 target:(id)arg3 selector:(SEL)arg4;
- (void)_notifyProjectObserversForProject:(id)arg1 selector:(SEL)arg2;
- (void)_notifyTargetObserversForTarget:(id)arg1 selector:(SEL)arg2;
- (void)_projectDidOpen:(id)arg1;
- (void)_projectFileWasAdded:(id)arg1;
- (void)_projectFileWillBeRemoved:(id)arg1;
- (void)_projectWillClose:(id)arg1;
- (void)_registerObserverProxyIfNeeded:(id)arg1;
- (void)_targetFileWasAdded:(id)arg1;
- (void)_targetFileWillBeRemoved:(id)arg1;
- (void)_targetWasAdded:(id)arg1;
- (void)_targetWillBeRemoved:(id)arg1;
- (void)_unregisterObserverProxyIfNeeded:(id)arg1;
- (void)_updateFileNoteObserverStatus;
- (bycopy id)activeTargetInProject:(bycopy id)arg1;
- (void)addFileObserver:(byref id)arg1 forFiles:(bycopy id)arg2;
- (void)addFiles:(bycopy id)arg1 toProject:(bycopy id)arg2 nearFile:(bycopy id)arg3 preferredInsertionGroupName:(bycopy id)arg4 addToTargets:(bycopy id)arg5 copyIntoGroupFolder:(BOOL)arg6 createGroupsRecursively:(BOOL)arg7;
- (void)addFiles:(bycopy id)arg1 toProject:(bycopy id)arg2 nearFile:(bycopy id)arg3 preferredInsertionGroupName:(bycopy id)arg4 addToTargets:(bycopy id)arg5 copyIntoGroupFolder:(BOOL)arg6 createGroupsRecursively:(BOOL)arg7 fileEncoding:(unsigned long long)arg8;
- (void)addGroupWithName:(bycopy id)arg1 path:(bycopy id)arg2 toProject:(bycopy id)arg3 nearFile:(bycopy id)arg4 preferredInsertionGroupName:(bycopy id)arg5;
- (void)addOpenProjectObserver:(byref id)arg1;
- (void)addProjectFileObserver:(byref id)arg1 forDictionary:(bycopy id)arg2;
- (void)addTargetFileObserver:(byref id)arg1 forDictionary:(bycopy id)arg2;
- (void)addTargetObserver:(byref id)arg1 forProjects:(bycopy id)arg2;
- (bycopy id)builtProductsLocationOfTarget:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (bycopy id)canonicalNameOfSDKOfTarget:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (void)dealloc;
- (bycopy id)filesOfTypes:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (bycopy id)filesOfTypes:(bycopy id)arg1 inTarget:(bycopy id)arg2 ofProject:(bycopy id)arg3;
- (bycopy id)fullProductNameOfTarget:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (id)init;
- (bycopy id)nameOfProject:(bycopy id)arg1;
- (bycopy id)nameOfTarget:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (bycopy id)openProjects;
- (bycopy id)openProjectsAppropriateForFile:(bycopy id)arg1;
- (bycopy id)openProjectsContainingFile:(bycopy id)arg1;
- (bycopy id)pathForFileWithName:(bycopy id)arg1 inProject:(bycopy id)arg2;
- (bycopy id)pathOfProject:(bycopy id)arg1;
- (bycopy id)productSettingsForTarget:(bycopy id)arg1 ofProject:(bycopy id)arg2;
- (void)removeFileObserver:(byref id)arg1;
- (void)removeOpenProjectObserver:(byref id)arg1;
- (void)removeProductSettingForKey:(bycopy id)arg1 inTarget:(bycopy id)arg2 ofProject:(bycopy id)arg3;
- (void)removeProjectFileObserver:(byref id)arg1;
- (void)removeTargetFileObserver:(byref id)arg1;
- (void)removeTargetObserver:(byref id)arg1;
- (void)setProductSetting:(bycopy id)arg1 forKey:(bycopy id)arg2 inTarget:(bycopy id)arg3 ofProject:(id)arg4;
- (bycopy id)targetsInProject:(bycopy id)arg1;
- (bycopy id)targetsInProject:(bycopy id)arg1 containingFile:(bycopy id)arg2;

@end

