//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXModule.h>

@class NSButton, NSButtonCell, NSComboBox, NSMatrix, NSMutableArray, NSPopUpButton, NSTextField;

@interface PBXSimpleFinder : PBXModule
{
    NSComboBox *_findTextComboBox;
    NSComboBox *_replaceTextComboBox;
    NSButton *_ignoreCaseButton;
    NSButton *_wrapTextButton;
    NSPopUpButton *_wholeWordsPopUp;
    NSPopUpButton *_findTypePopUp;
    NSMatrix *_replaceOptions;
    NSButtonCell *_entireFileButton;
    NSButtonCell *_selectionOnlyButton;
    NSTextField *_status;
    NSButton *_nextButton;
    NSButton *_previousButton;
    NSButton *_replaceButton;
    NSButton *_replaceAllButton;
    NSButton *_replaceAndFindButton;
    struct {
        unsigned int lastFindWasSuccessful:1;
        unsigned int observingWindow:1;
        unsigned int RESERVED:30;
    } _sfFlags;
    NSMutableArray *_previousFindStrings;
    NSMutableArray *_previousReplaceStrings;
}

+ (long long)defaultFindType;
+ (BOOL)defaultIgnoresCase;
+ (int)defaultMatchStyle;
+ (BOOL)defaultWrapText;
+ (void)initialize;
+ (void)setDefaultFindType:(long long)arg1;
+ (void)setDefaultIgnoresCase:(BOOL)arg1;
+ (void)setDefaultMatchStyle:(int)arg1;
+ (void)setDefaultWrapText:(BOOL)arg1;
+ (id)sharedSimpleFinder;
- (void)_addToPreviousFinds:(id)arg1;
- (void)_addToPreviousReplaces:(id)arg1;
- (long long)_currentFindType;
- (int)_currentMatchStyle;
- (BOOL)_findNext;
- (BOOL)_findPrevious;
- (void)_findSettingsDidChange:(id)arg1;
- (void)_loadSharedFindSettingsFromDefaults;
- (BOOL)_replaceAll;
- (BOOL)_replaceCurrent;
- (void)_showStatusCantReplace;
- (void)_showStatusNotFound;
- (void)_showStatusNothingToSearch;
- (void)_showStatusReplacementsMade:(unsigned long long)arg1;
- (void)_showStatusString:(id)arg1;
- (void)_windowDidUpdate:(id)arg1;
- (BOOL)checkRegex:(id)arg1;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)dealloc;
- (void)findNext:(id)arg1;
- (void)findNextAndDismissIfSuccessful:(id)arg1;
- (void)findOptionsChanged:(id)arg1;
- (void)findPrevious:(id)arg1;
- (void)findSelectionInFile:(id)arg1;
- (void)globalFindStringChanged:(id)arg1;
- (void)globalReplaceStringChanged:(id)arg1;
- (id)initWithModuleNibName:(id)arg1;
- (id)loadModuleWindow;
- (void)moduleViewWasInstalled:(id)arg1;
- (void)moduleViewWillBeRemoved:(id)arg1;
- (Class)moduleWindowClass;
- (id)moduleWindowFrameAutosaveName;
- (unsigned long long)moduleWindowStyleMask;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (void)replace:(id)arg1;
- (void)replaceAll:(id)arg1;
- (void)replaceAndFindNext:(id)arg1;
- (void)replaceAndFindPrevious:(id)arg1;
- (void)showSimpleFind:(id)arg1;
- (void)showWindow:(id)arg1;
- (BOOL)validateAction:(SEL)arg1;
- (void)viewDidLoad;
- (struct CGSize)viewMaxSize;
- (struct CGSize)viewMinSize;

@end

