//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXModule.h>

@class NSButton, NSImageView, NSMutableArray, NSString, NSTextField, PBXExtendedTableView;

@interface PBXSaveMultipleModule : PBXModule
{
    NSImageView *iconView;
    PBXExtendedTableView *listTable;
    NSButton *saveButton;
    NSButton *cancelButton;
    NSButton *dontSaveButton;
    NSTextField *titleField;
    BOOL _allowsCancel;
    NSString *_iconImageName;
    NSString *_windowTitle;
    NSString *_title;
    NSString *_cancelTitle;
    NSMutableArray *_documents;
}

+ (id)sharedSaveMultipleModule;
- (void)_refresh:(id)arg1;
- (void)_reset;
- (BOOL)allowsCancel;
- (void)cancelAction:(id)arg1;
- (id)cancelTitle;
- (void)dealloc;
- (void)dontSaveAction:(id)arg1;
- (id)iconImage;
- (id)initWithModuleNibName:(id)arg1;
- (id)loadModuleWindow;
- (Class)moduleWindowClass;
- (id)moduleWindowFrameAutosaveName;
- (unsigned long long)moduleWindowStyleMask;
- (long long)numberOfRowsInTableView:(id)arg1;
- (unsigned long long)runModalWithDocuments:(id)arg1;
- (unsigned long long)runModalWithDocuments:(id)arg1 relativeToWindow:(id)arg2;
- (void)saveAction:(id)arg1;
- (void)saveSelectedDocuments;
- (void)selectAll:(id)arg1;
- (void)setAllowsCancel:(BOOL)arg1;
- (void)setCancelButtonTitle:(id)arg1;
- (void)setIconImageFromName:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setWindowTitle:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)title;
- (void)updateButtons;
- (void)viewDidLoad;
- (struct CGSize)viewMinSize;
- (id)windowTitle;

@end

