//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@interface XCActionControl : NSPopUpButton
{
}

+ (id)createInstanceWithDefinition:(id)arg1 forProjectDocument:(id)arg2;
+ (id)createToolbarItemForToolbar:(BOOL)arg1;
+ (void)echoStringsForDefinition:(id)arg1;
+ (void)initialize;
- (void)_selectionDidChange:(id)arg1;
- (void)dealloc;
- (id)gearMenuItem;
- (id)initWithActionManager:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

