//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCProjectPopup.h>

@interface XCActivePlatformPopup : XCProjectPopup
{
    unsigned char _optionKey;
}

+ (id)itemIdentifier;
- (long long)_popupMaxWidth;
- (void)addObserversWithProject:(id)arg1;
- (id)formatMenuString;
- (id)initWithProject:(id)arg1;
- (BOOL)isInterestedInChangesToProject:(id)arg1;
- (id)label;
- (void)mouseDown:(id)arg1;
- (id)paletteLabel;
- (void)popupSelectionActionAtIndex:(long long)arg1 withProject:(id)arg2;
- (void)rebuildPopup:(id)arg1;
- (void)removeObserversWithProject:(id)arg1;
- (id)toolTip;

@end

