//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCDiffComparatorView.h>

@class PBXTableColumnManager;

@interface XCDiffTableComparatorView : XCDiffComparatorView
{
    PBXTableColumnManager *_leftTableColumnManager;
    PBXTableColumnManager *_rightTableColumnManager;
}

+ (Class)_dataSourceClass;
+ (Class)_mergeDataSourceClass;
+ (Class)_viewClass;
+ (void)initialize;
- (BOOL)_scrollDiffHunkMarkerToVisible:(id)arg1;
- (id)_toolTipForDiffDescriptor:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 diffContext:(id)arg2;
- (struct CGSize)leftViewContentSize;
- (struct CGSize)mergeViewContentSize;
- (struct CGSize)rightViewContentSize;

@end

