//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

#import <DevToolsInterface/NSOutlineViewDelegate-Protocol.h>

@class NSMutableDictionary, NSString, XCDocSetOutlineViewController;

@interface XCDocSetOutlineView : NSOutlineView <NSOutlineViewDelegate>
{
    XCDocSetOutlineViewController *_controller;
    NSMutableDictionary *_itemToDocSetCellDict;
    long long _rowOfContextualMenuClick;
}

- (void)_docOutlineViewWindowWillClose:(id)arg1;
- (void)awakeFromNib;
- (id)controller;
- (void)dealloc;
- (id)docSetsColumnInOutlineView;
- (void)invalidateAllDocSetCellCaches;
- (id)itemAtOutlineViewRow:(long long)arg1;
- (id)itemToDocSetCellDict;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineView:(id)arg1 didStartEditingColumn:(long long)arg2 row:(long long)arg3;
- (BOOL)outlineView:(id)arg1 shouldCollapseItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (id)outlineViewItemForEvent:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)redisplayAndUnselectOutlineViewItem:(id)arg1;
- (void)redisplayOutlineViewItem:(id)arg1;
- (void)reloadData;
- (void)removeSyndicationButtonsForPublisher:(id)arg1;
- (void)selectRowIndexes:(id)arg1 byExtendingSelection:(BOOL)arg2;
- (void)setController:(id)arg1;
- (void)subscribeFailed:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)subscribeToFeedForGroup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

