//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCElementFace.h>

@interface XCElementDebuggingFace : XCElementFace
{
    long long _countOwnSpacings;
    long long _countInheritedSpacings;
    long long _countNoSpacings;
}

- (void)_addLabel:(id)arg1 objectInfoFor:(id)arg2;
- (void)_addLabel:(id)arg1 value:(id)arg2;
- (void)layoutElement:(struct NSObject *)arg1;
- (void)layoutWindow:(id)arg1;

@end

