//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSControl.h>

@class NSViewController;

@interface XCElementView : NSControl
{
    struct NSObject *_mainElement;
}

- (void)_clear;
- (void)_closeSheet:(long long)arg1;
- (void)_completeRefresh;
- (struct CGPoint)_currentLocalMousePoint;
- (struct CGPoint)_currentLocalMousePointWithEvent:(id)arg1;
- (void)_cursorElementUpdate:(id)arg1;
- (void)_cursorUpdateForElement:(struct NSObject *)arg1 atPoint:(struct CGPoint)arg2;
- (unsigned long long)_draggingCommon:(id)arg1;
- (void)_drawDragFeedback;
- (id)_findDestinationElement:(id)arg1;
- (void)_frameChanged:(id)arg1;
- (BOOL)_giveUpFocus;
- (id)_outerDNDView;
- (void)_releaseValuesView;
- (void)_selectFirstSelectableElementAt:(struct CGPoint)arg1;
- (void)_setEnabledSubControls:(BOOL)arg1;
- (void)_unselectKeyView;
- (BOOL)_windowShouldClose:(id)arg1;
- (void)_windowWillClose;
- (BOOL)abortEditing;
- (struct NSObject *)actionDelegate;
- (id)alternateBackgroundColor;
- (void)applicationDidUpdate:(id)arg1;
- (void)applicationWillUpdate:(id)arg1;
- (void)applyDefaultSizesAdjustingViewSize;
- (void)awakeFromNib;
- (id)backgroundColor;
- (BOOL)callMakeFirstResponder:(id)arg1;
- (void)cancelOperation:(id)arg1;
- (void)cancelSheetAction:(id)arg1;
- (BOOL)commitEditing;
- (void)commitEditingWithDelegate:(id)arg1 didCommitSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (void)concludeDragOperation:(id)arg1;
- (void)configureWithScrollview:(id)arg1 scrollsH:(BOOL)arg2 scrollsV:(BOOL)arg3 resizesWindowHorizontally:(BOOL)arg4 resizesWindowVertically:(BOOL)arg5;
- (BOOL)continouslyPropagateMinSizeToWindow;
- (id)createElementFromDraggingInfo:(id)arg1;
- (id)currentKeyView;
- (void)cursorUpdate:(id)arg1;
- (id)darkColor;
- (void)dealloc;
- (void)discardEditing;
- (void)draggedImage:(id)arg1 endedAt:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingSourceOperationMaskForLocal:(BOOL)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)firstKeyView;
- (void)forcePositionElements;
- (struct NSObject *)generateMainElement;
- (void)highlightSearchResult:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)isEditing;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (id)lastKeyView;
- (id)lightColor;
- (struct NSObject *)mainElement;
- (void)makeSelected:(struct NSObject *)arg1;
- (BOOL)mayExtendBeyondWindowHorizontally;
- (BOOL)mayExtendBeyondWindowVertically;
- (id)menuForEvent:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)okSheetAction:(id)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)positionElements;
- (BOOL)prepareForDragOperation:(id)arg1;
- (void)propagateMinSizeToWindow;
- (void)receiveXCESignal:(id)arg1;
- (id)representedObject;
- (BOOL)resignFirstResponder;
- (BOOL)resizesLayoutHorizontally;
- (BOOL)resizesLayoutVertically;
- (BOOL)resizesViewHorizontally;
- (BOOL)resizesViewVertically;
- (BOOL)resizesWindowHorizontally;
- (BOOL)resizesWindowVertically;
- (id)searchResultsFor:(id)arg1;
- (struct NSObject *)selectedElement;
- (void)setActionDelegate:(struct NSObject *)arg1;
- (void)setAlternateBackgroundColor:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)setContinouslyPropagateMinSizeToWindow:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (id)setFirstKeyView:(id)arg1;
- (id)setLastKeyView:(id)arg1;
- (void)setMainElement:(struct NSObject *)arg1;
- (void)setMayExtendBeyondWindowHorizontally:(BOOL)arg1;
- (void)setMayExtendBeyondWindowVertically:(BOOL)arg1;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)setRepresentedObject:(id)arg1;
- (void)setResizesLayoutHorizontally:(BOOL)arg1;
- (void)setResizesLayoutVertically:(BOOL)arg1;
- (void)setResizesViewHorizontally:(BOOL)arg1;
- (void)setResizesViewVertically:(BOOL)arg1;
- (void)setResizesWindowHorizontally:(BOOL)arg1;
- (void)setResizesWindowVertically:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1 element:(struct NSObject *)arg2;
@property(nonatomic) NSViewController *vC; // @dynamic vC;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)updateForSelection;
- (void)validateEditing;
- (void)viewBecameFirstResponder:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillDraw;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)windowDidUpdate:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)windowWillClose:(id)arg1;

@end

