//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCElementUnit.h>

@interface XCElementObjectUnit : XCElementUnit
{
}

- (void)_tableSelectionDidChangeForTable:(id)arg1 anchor:(struct NSObject *)arg2;
- (BOOL)anchor:(struct NSObject *)arg1 confirmRepresentedObject:(id)arg2;
- (void)anchor:(struct NSObject *)arg1 didChangeRepresentedObject:(id)arg2 previousObject:(id)arg3;
- (void)dealloc;
- (BOOL)willChangeLayoutForObject:(id)arg1 fromObject:(id)arg2;

@end

