//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <DevToolsInterface/PBXCompletionItem-Protocol.h>

@class NSString, XCTextMacroSpecification;

@interface XCMacroCompletionItem : NSObject <PBXCompletionItem>
{
    XCTextMacroSpecification *_macro;
    NSString *_cachedName;
}

- (id)completionText;
- (id)completionTextWithMacroExpansionDictionary:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)descriptionText;
- (id)displayText;
- (id)displayType;
- (unsigned long long)hash;
- (id)icon;
- (id)initWithMacroSpecification:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)name;
- (long long)priority;

@end

