//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/XCSpecification.h>

@class NSMenu, NSNib, NSString;

@interface XCSCMUISpecification : XCSpecification
{
    NSString *_selectionClassName;
    NSString *_menuNibName;
    NSNib *_menuNib;
    NSMenu *_menu;
    NSMenu *_contextualMenu;
}

+ (id)localizedSpecificationTypeName;
+ (id)scmUISpecificationForSCMType:(id)arg1;
+ (id)specificationRegistryName;
+ (id)specificationType;
- (id)contextualMenu;
- (void)dealloc;
- (id)initWithPropertyListDictionary:(id)arg1 inDomain:(id)arg2;
- (id)menu;
- (id)menuNibName;
- (Class)selectionClass;
- (id)selectionClassName;

@end

