//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSButton, NSObject, NSTextField, XCProgressIndicator;
@protocol PBXTrackableTask;

@interface XCTaskView : NSView
{
    NSObject<PBXTrackableTask> *_task;
    NSButton *_stopButton;
    XCProgressIndicator *_progressIndicator;
    NSTextField *_title;
    NSTextField *_description;
}

- (void)_sizeAndPositionSubviews;
- (void)_updateIfNeeded;
- (void)_updateToMatchTaskState;
- (void)dealloc;
- (id)initWithTask:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)setString:(id)arg1 inTextField:(id)arg2;
- (void)viewDidMoveToWindow;

@end

