//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCUserScriptNode.h>

#import <DevToolsInterface/NSMenuDelegate-Protocol.h>

@class NSMenu, NSMutableArray, NSString;

@interface XCUserScriptGroup : XCUserScriptNode <NSMenuDelegate>
{
    NSMutableArray *_subNodes;
}

+ (BOOL)accessInstanceVariablesDirectly;
+ (id)archivableRelationships;
+ (id)keyPathsForValuesAffectingSubNodesArray;
+ (id)userScriptGroupWithName:(id)arg1;
- (id)contents;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countOfSubNodes;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)gidCommentForArchive;
@property(readonly) unsigned long long hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithPropertyListRepresentation:(id)arg1;
- (void)insertObject:(id)arg1 inSubNodesAtIndex:(unsigned long long)arg2;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isLeaf;
- (BOOL)isNameEditable;
@property(readonly) NSMenu *menu;
- (id)menuItem;
- (void)menuNeedsUpdate:(id)arg1;
- (id)objectInSubNodesAtIndex:(unsigned long long)arg1;
- (id)propertyListRepresentationWithUUIDs:(BOOL)arg1;
- (void)removeObjectFromSubNodesAtIndex:(unsigned long long)arg1;
- (SEL)selector;
- (void)setContents:(id)arg1;
- (void)setSubNodesArray:(id)arg1;
- (id)subNodesArray;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

