//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXObject.h>

#import <DevToolsInterface/NSCoding-Protocol.h>
#import <DevToolsInterface/NSCopying-Protocol.h>

@class NSImage, NSIndexPath, NSMenuItem, NSString, PBXKeyEquivalent, XCUserScriptGroup;

@interface XCUserScriptNode : PBXObject <NSCoding, NSCopying>
{
    XCUserScriptGroup *_parentNode;
    NSString *_name;
    NSString *_uuid;
    NSImage *_icon;
}

+ (BOOL)accessInstanceVariablesDirectly;
+ (id)archivableAttributes;
+ (id)archivableRelationships;
+ (void)initialize;
+ (BOOL)isScriptRunningWithContext:(id)arg1;
+ (void)registerUserScriptClass:(Class)arg1 withName:(id)arg2;
+ (id)scriptErrorValues;
+ (id)scriptInputValues;
+ (id)scriptOutputValues;
+ (id)scriptWorkingDirectoryValues;
+ (Class)userScriptClassWithName:(id)arg1;
+ (id)userScriptNodeFromPropertyListRepresentation:(id)arg1;
+ (id)userScriptsFromArray:(id)arg1;
- (id)arguments;
- (id)command;
- (id)commandLine;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (int)debugger;
- (id)debuggerChoices;
- (id)editorTabIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)fallbackClassNameForPListArchive;
- (id)gidCommentForArchive;
- (unsigned long long)hash;
@property(copy) NSImage *icon; // @synthesize icon=_icon;
@property(readonly) unsigned long long index;
@property(readonly) NSIndexPath *indexPath;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithPropertyListRepresentation:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isFileScript;
@property(readonly) BOOL isLeaf;
- (BOOL)isNameEditable;
@property(readonly) BOOL isSeparator;
@property(copy) PBXKeyEquivalent *keyEquivalent;
@property(copy) NSString *language;
@property(readonly) NSMenuItem *menuItem;
@property(copy) NSString *name; // @synthesize name=_name;
@property XCUserScriptGroup *parentNode; // @synthesize parentNode=_parentNode;
@property(readonly) id propertyListRepresentation;
- (id)propertyListRepresentationWithUUIDs:(BOOL)arg1;
@property(readonly) id propertyListRepresentationWithoutUUIDs;
@property(readonly) XCUserScriptNode *rootNode;
- (id)script;
- (id)scriptError;
- (id)scriptErrorAsString;
- (id)scriptInput;
- (id)scriptInputAsString;
- (id)scriptOutput;
- (id)scriptOutputAsString;
- (id)scriptURL;
- (id)scriptUTI;
- (id)scriptWorkingDirectory;
- (id)scriptWorkingDirectoryAsString;
@property(readonly) SEL selector;
@property(copy) NSString *uuid;
- (BOOL)validateName:(id *)arg1 error:(id *)arg2;

@end

