//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTProducts/DVTProductIdentifier.h>

@class DVTProductCategory, NSString;

@interface DVTMalformedProductIdentifier : DVTProductIdentifier
{
    DVTProductCategory *_productCategory;
    NSString *_bundleIdentifier;
    NSString *_name;
}

+ (id)malformedProductIdentifierWithArchive:(id)arg1;
+ (id)objectFromJSONRepresentation:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)JSONRepresentation;
- (id)bundleIdentifier;
- (id)description;
- (unsigned long long)hash;
- (id)initWithProductCategory:(id)arg1 name:(id)arg2 bundleIdentifier:(id)arg3;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSString *name; // @synthesize name=_name;
- (id)productCategory;

@end

