//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DVTProducts/DVTInvalidation-Protocol.h>

@class DVTStackBacktrace, NSHashTable, NSString;

@interface DVTProductCoordinator : NSObject <DVTInvalidation>
{
    NSHashTable *_products;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_forgetProduct:(id)arg1 invalidate:(BOOL)arg2;
- (id)init;
- (void)invalidateProduct:(id)arg1;
- (void)invalidateProducts:(id)arg1;
- (id)malformedProductWithArchives:(id)arg1;
- (void)primitiveInvalidate;
- (id)productWithBundleIdentifier:(id)arg1 productCategory:(id)arg2 productVersions:(id)arg3;
- (id)productWithProductIdentifier:(id)arg1 productVersions:(id)arg2;
@property(retain) NSHashTable *products; // @synthesize products=_products;
- (void)registerProduct:(id)arg1;
- (void)transferProduct:(id)arg1 toCoordinator:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

