//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTPlatform, NSSet, NSString;

@interface DVTProductCategory : NSObject
{
    BOOL _wantsRoundedIcons;
    BOOL _crashPointInspectableShouldShowDeviceTypes;
    BOOL _wantsOnDiskPlatformDisambiguation;
    NSString *_identifier;
    NSString *_archiveDescription;
    long long _sortOrder;
    long long _deprecatedIdentifier;
    NSString *_supportedOSVersionStringFormat;
    NSString *_crashPointInspectableOSVersionDescriptor;
    NSSet *_overridingDeviceTypes;
    NSString *_userDescriptionWhenNoPlatformExists;
}

+ (id)productCategories;
+ (id)productCategoryForDeprecatedIdentifier:(id)arg1;
+ (id)productCategoryForITunesSoftwareApplicationType:(int)arg1 usingSession:(id)arg2 error:(id *)arg3;
+ (id)productCategoryForIdentifier:(id)arg1;
+ (id)productCategoryForIdentifier:(id)arg1 fallingBackOnDeprecatedIdentifier:(id)arg2 outError:(id *)arg3;
+ (id)productCategoryForPlatformSDKIdentifier:(id)arg1;
+ (id)productCategoryForUnknownIdentifier;
- (void).cxx_destruct;
@property(readonly) NSString *archiveDescription; // @synthesize archiveDescription=_archiveDescription;
- (long long)compare:(id)arg1;
@property(readonly) NSString *crashPointInspectableOSVersionDescriptor; // @synthesize crashPointInspectableOSVersionDescriptor=_crashPointInspectableOSVersionDescriptor;
@property(readonly) BOOL crashPointInspectableShouldShowDeviceTypes; // @synthesize crashPointInspectableShouldShowDeviceTypes=_crashPointInspectableShouldShowDeviceTypes;
@property(readonly) long long deprecatedIdentifier; // @synthesize deprecatedIdentifier=_deprecatedIdentifier;
- (id)description;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1 userDescriptionWhenNoPlatformExists:(id)arg2 archiveDescription:(id)arg3 sortOrder:(long long)arg4 deprecatedIdentifier:(long long)arg5 wantsRoundedIcons:(BOOL)arg6 supportedOSVersionStringFormat:(id)arg7 crashPointInspectableOSVersionDescriptor:(id)arg8 overridingDeviceTypes:(id)arg9 wantsOnDiskPlatformDisambiguation:(BOOL)arg10 crashPointInspectableShouldShowDeviceTypes:(BOOL)arg11;
@property(readonly) NSSet *overridingDeviceTypes; // @synthesize overridingDeviceTypes=_overridingDeviceTypes;
@property(readonly) DVTPlatform *platform;
@property(readonly) NSString *platformDisambiguationString;
- (id)platformDisambiguationStringWithPrefixString:(id)arg1;
- (id)platformForCategoryIdentifier:(id)arg1;
@property(retain, nonatomic) NSString *userDescriptionWhenNoPlatformExists; // @synthesize userDescriptionWhenNoPlatformExists=_userDescriptionWhenNoPlatformExists;
@property(nonatomic) BOOL wantsOnDiskPlatformDisambiguation; // @synthesize wantsOnDiskPlatformDisambiguation=_wantsOnDiskPlatformDisambiguation;
@property(readonly) long long sortOrder; // @synthesize sortOrder=_sortOrder;
@property(readonly) NSString *supportedOSVersionStringFormat; // @synthesize supportedOSVersionStringFormat=_supportedOSVersionStringFormat;
@property(readonly) NSString *userDescription;
@property(readonly) BOOL wantsRoundedIcons; // @synthesize wantsRoundedIcons=_wantsRoundedIcons;

@end

