//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <DevToolsKit/DTDraggingInfo-Protocol.h>

@class DTDraggedImageState, NSDictionary, NSImage, NSPasteboard, NSString, NSWindow;

@interface DTDraggingContext : NSObject <DTDraggingInfo>
{
    NSWindow *draggingDestinationWindow;
    struct CGPoint draggingLocation;
    struct CGPoint draggedImageLocation;
    NSImage *draggedImage;
    NSPasteboard *draggingPasteboard;
    id draggingSource;
    NSDictionary *draggingSourceContext;
    long long draggingSequenceNumber;
    long long draggingSourceOperationMask;
    DTDraggedImageState *draggedImageState;
    struct CGSize draggingStickiness;
    BOOL draggedImageStateNeedsUpdate;
    long long draggingFormation;
    BOOL animatesToDestination;
    long long numberOfValidItemsForDrop;
}

@property BOOL animatesToDestination; // @synthesize animatesToDestination;
- (void)dealloc;
- (id)draggedImage;
- (struct CGPoint)draggedImageLocation;
- (id)draggedImageState;
- (BOOL)draggedImageStateNeedsUpdate;
- (id)draggingDestinationWindow;
@property long long draggingFormation; // @synthesize draggingFormation;
- (struct CGPoint)draggingLocation;
- (struct CGPoint)draggingLocationOnScreen;
- (id)draggingPasteboard;
- (long long)draggingSequenceNumber;
- (id)draggingSource;
- (id)draggingSourceContext;
- (unsigned long long)draggingSourceOperationMask;
- (struct CGSize)draggingStickiness;
- (void)enumerateDraggingItemsWithOptions:(unsigned long long)arg1 forView:(id)arg2 classes:(id)arg3 searchOptions:(id)arg4 usingBlock:(CDUnknownBlockType)arg5;
- (id)initWithSource:(id)arg1 andPasteboard:(id)arg2;
- (id)namesOfPromisedFilesDroppedAtDestination:(id)arg1;
@property long long numberOfValidItemsForDrop; // @synthesize numberOfValidItemsForDrop;
- (void)setDraggedImage:(id)arg1;
- (void)setDraggedImageLocation:(struct CGPoint)arg1;
- (void)setDraggedImageState:(id)arg1;
- (void)setDraggedImageStateNeedsUpdate:(BOOL)arg1;
- (void)setDraggingDestinationWindow:(id)arg1;
- (void)setDraggingLocation:(struct CGPoint)arg1;
- (void)setDraggingSequenceNumber:(long long)arg1;
- (void)setDraggingSourceContext:(id)arg1;
- (void)setDraggingSourceOperationMask:(unsigned long long)arg1;
- (void)setDraggingStickiness:(struct CGSize)arg1;
- (void)slideDraggedImageTo:(struct CGPoint)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) long long springLoadingHighlight;
@property(readonly) Class superclass;

@end

