//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class DTFlippedView, DTSplitView, DTTemplateChooserAccessoryBackgroundView, DTTemplateChooserDetailView, DTTemplateChooserMatrix, DTTypeCompletionHandler, NSMutableArray, NSScrollView, NSTextField, NSView;

@interface DTTemplateChooserViewController : NSViewController
{
    NSView *templateChooser;
    NSView *itemView;
    NSScrollView *descriptionScrollView;
    NSTextField *headingTextField;
    DTTemplateChooserMatrix *categoryMatrix;
    DTTemplateChooserMatrix *itemMatrix;
    DTSplitView *itemSplitView;
    DTFlippedView *descriptionView;
    DTTemplateChooserDetailView *detailView;
    NSView *accessoryView;
    DTTemplateChooserAccessoryBackgroundView *accessoryBackgroundView;
    DTTypeCompletionHandler *typeCompletionHandler;
    NSMutableArray *templateCategories;
    BOOL defaultsRestored;
    id delegate;
}

@property(retain) NSView *accessoryView; // @synthesize accessoryView;
- (void)addTemplateCategory:(id)arg1;
- (void)addTemplateCategory:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)awakeFromNib;
- (void)categoryClicked:(id)arg1;
- (void)clearTemplateCategories;
- (void)dealloc;
@property BOOL defaultsRestored; // @synthesize defaultsRestored;
- (id)delegate;
- (id)init;
- (void)itemClicked:(id)arg1;
- (void)itemDoubleClicked:(id)arg1;
- (void)resetSplitterPosition;
- (void)restoreDefaults;
- (BOOL)selectLastUsedObjectInMatrix:(id)arg1 forKey:(id)arg2;
- (void)selectLastUsedObjects;
- (BOOL)selectObjectInMatrix:(id)arg1 forIdentifier:(id)arg2;
- (id)selectedCategory;
- (id)selectedTemplate;
- (void)setDelegate:(id)arg1;
- (void)setHeadingText:(id)arg1;
- (void)setInstructionField:(id)arg1;
- (void)setTemplateCategories:(id)arg1;
- (double)splitView:(id)arg1 minSizeForView:(id)arg2;
- (void)splitViewSplitterDidMove:(id)arg1;
- (id)templateCategories;
- (void)templateChooserViewControllerViewDidResize:(id)arg1;
- (id)typeCompletionHandler:(id)arg1 typeCompletionStringForObject:(id)arg2;
- (void)typeSelectionInMatrix:(id)arg1 forString:(id)arg2;
- (void)update;
- (void)updateAccessoryView;
- (void)updateSelectedCategoryDefault;
- (void)updateSelectedTemplateDefault;
- (void)updateTemplateCategoriesMatrix;
- (void)updateTemplateDescription;
- (void)updateTemplateItemsMatrix;

@end

