//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface XCTextColorPreferences : NSObject
{
}

+ (id)colorForId:(short)arg1;
+ (id)colorNameForId:(short)arg1;
+ (id)defaultColorForId:(short)arg1;
+ (id)fontForId:(short)arg1;
+ (void)initialize;
+ (short)registerColor:(id)arg1;
+ (id)syntaxTypeSpecificationForId:(short)arg1;
+ (id)textColorForId:(short)arg1;

@end

