//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXCodeAssistantStrategy.h>

@class PBXFileReference, PBXNativeTarget;

@interface PBXCodeAssistantAbsolutePathBasedStrategy : PBXCodeAssistantStrategy
{
    PBXFileReference *_associatedFileReference;
    PBXNativeTarget *_associatedTarget;
}

- (id)_completionItemsFromAbsolutePath:(id)arg1;
- (id)_importLineStringUnderCursor;
- (BOOL)getItems:(id *)arg1 withInfoString:(id)arg2;
- (id)uniqueCompletionItemsAtPath:(id)arg1 withBasePriority:(long long)arg2;

@end

