//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXDebugDataValueViewModule.h>

@class PBXLSStackFrame;

@interface PBXDebugSingleDataValueViewModule : PBXDebugDataValueViewModule
{
    BOOL _firstTime;
    PBXLSStackFrame *_frameToWatch;
    BOOL _userDidResize;
    BOOL _doneWithInitialLoad;
    long long _numberOfToplevelVars;
}

- (void)_cleanup;
- (void)_setupContainerDataValue:(id)arg1;
- (void)dealloc;
- (void)debugViewModuleWindowWillClose:(id)arg1;
- (void)dsModelDidUpdate:(id)arg1;
- (void)dsModelWillDealloc:(id)arg1;
- (id)frameToWatch;
- (id)moduleNibName;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (void)setContainerDV:(id)arg1;
- (void)setContainerDataValue:(id)arg1 dataValuesToClone:(id)arg2 viewContentsAsExpression:(id)arg3;
- (void)setFrameToWatch:(id)arg1;
- (void)viewBoundsDidChangeNotification:(id)arg1;
- (void)viewDidLoad;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;

@end

