//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXHeaderBox.h>

@interface PBXDropIndicationView : PBXHeaderBox
{
    BOOL _trackingDrag;
}

- (BOOL)canBecomeKeyView;
- (void)drawRect:(struct CGRect)arg1;
- (id)dropIndicatorColor;
- (BOOL)isOpaque;
- (void)setTrackingDrag:(BOOL)arg1;

@end

