//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXModule.h>

#import <DevToolsInterface/NSOutlineViewDataSource-Protocol.h>
#import <DevToolsInterface/NSOutlineViewDelegate-Protocol.h>

@class NSArray, NSBox, NSMenu, NSMutableArray, NSString, NSTableColumn, PBXExtendedOutlineView;

@interface PBXItemsSelectionModule : PBXModule <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    PBXExtendedOutlineView *_outlineView;
    NSBox *_box;
    NSMenu *_viewContextualMenu;
    NSArray *_items;
    NSMutableArray *_checkedItems;
    BOOL _canExpandItems;
    BOOL _hasBox;
    NSTableColumn *_checkedOutlineColumn;
    NSTableColumn *_nameOutlineColumn;
}

- (void)checkAll:(id)arg1;
- (id)checkedItems;
- (void)dealloc;
- (id)init;
- (id)items;
- (id)outlineView;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)reset;
- (void)scrollFirstCheckedItemToVisible;
- (void)setCanExpandItems:(BOOL)arg1;
- (void)setCheckedItems:(id)arg1;
- (void)setHasBox:(BOOL)arg1;
- (void)setItems:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)uncheckAll:(id)arg1;
- (void)viewDidLoad;
- (BOOL)worksWhenModal;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

