//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXWizardChooserWizard.h>

@interface PBXProjectWizardChooserWizard : PBXWizardChooserWizard
{
}

+ (BOOL)allowsWizardDescriptions;
- (void)addWizardProxiesForRegisteredWizardClasses;
- (BOOL)canFinish;
- (BOOL)canProceed;
- (BOOL)checkForWizardProxiesAtBaseSearchPath:(id)arg1 subpath:(id)arg2;
- (id)preferredSortOrders;
- (void)sheetDidEndWithReturnCode:(long long)arg1 fileSystemLocations:(id)arg2 contextInfo:(void *)arg3;
- (BOOL)validateSettings;
- (BOOL)wantsChooseButton;
- (id)wizardPlatformSearchPaths;
- (id)wizardSearchDomainSubpath;

@end

