//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXTarget.h>

@interface PBXTarget (PBXTargetEditorAdditions)
- (void)addUIAspectModuleClassesForTargetEditor:(id)arg1 toStringTree:(id)arg2;
- (BOOL)allowsCopyFilesBuildPhases;
- (BOOL)allowsShellScriptBuildPhases;
- (BOOL)allowsZeroBuildPhases;
- (BOOL)wantsTopLevelItemForBuildPhases;
- (BOOL)wantsTopLevelItemForBuildRules;
@end

