//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMenu, NSTableView;
@protocol PBXTableColumnProvider;

@interface PBXTableColumnManager : NSObject
{
    NSTableView *_tableView;
    id <PBXTableColumnProvider> _provider;
    NSMenu *_headerMenu;
}

- (id)createColumnChoiceMenu;
- (void)dealloc;
- (id)headerMenu;
- (id)initWithTable:(id)arg1 provider:(id)arg2;
- (void)menuSelected:(id)arg1;
- (void)syncMenu;
- (id)tableView;
- (BOOL)validateMenuItem:(id)arg1;

@end

