//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCBuildPropertyDefinitionNodeAdapter.h>

@interface XCBuildPropertyDefinitionEnumNodeAdapter : XCBuildPropertyDefinitionNodeAdapter
{
}

- (void)addMenuItemsToPopUpCell:(id)arg1;
- (void)assignCell;
- (void)dataNode:(id)arg1 outlineView:(id)arg2 willDisplayCell:(id)arg3 forTableColumn:(id)arg4;

@end

