//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXInspectorPaneModule.h>

#import <DevToolsInterface/NSTextViewDelegate-Protocol.h>
#import <DevToolsInterface/PBXSourceLexerDelegate-Protocol.h>

@class NSButton, NSString, NSTextField, NSTextView;

@interface XCCommentsInspectorPane : PBXInspectorPaneModule <NSTextViewDelegate, PBXSourceLexerDelegate>
{
    NSTextField *_commentsLabel;
    NSTextView *_commentsTextView;
    NSButton *_helpButton;
}

+ (id)alternateLabel;
+ (BOOL)canInspectItems:(id)arg1;
+ (void)initialize;
+ (id)inspectableClasses;
+ (id)label;
+ (unsigned long long)panelPosition;
- (void)_highlightLinksInComments;
- (void)_setURLLink:(id)arg1 forRange:(struct _NSRange)arg2;
- (void)_startListeningForProjectChanges;
- (void)_stopListeningForProjectChanges;
- (id)buildPhase;
- (void)buildPhaseWasRemoved:(id)arg1;
- (void)currentInspectedItemsChanged:(id)arg1;
- (void)dealloc;
- (void)gotSyntaxClass:(int)arg1 forRange:(struct _NSRange)arg2;
- (void)textDidChange:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

