//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXExtendedTableView.h>

@interface XCDistributedBuildsTableView : PBXExtendedTableView
{
    BOOL _acceptsFirstResponder;
}

- (BOOL)acceptsFirstResponder;
- (void)setAcceptsFirstResponder:(BOOL)arg1;
- (void)setFont:(id)arg1;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;

@end

