//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXInspectorPanel.h>

@class NSMenuItem;

@interface XCDockableInspector : PBXInspectorPanel
{
    NSMenuItem *_dockMenuItem;
}

- (void)_lockInspector:(id)arg1;
- (void)_validateDockMenu;
- (void)_viewDidLoad;
- (BOOL)canCloneInDock;
- (id)cloneInDock;
- (void)dealloc;
- (id)dockMenuItems;
- (id)init;
- (id)label;

@end

