//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTMutableRangeArray, NSString, XCDWARFDocument;

@interface XCDWARFFileReference : NSObject
{
    XCDWARFDocument *_document;
    NSString *_path;
    NSString *_architecture;
    DTMutableRangeArray *_lineRanges;
}

@property(readonly) NSString *architecture; // @synthesize architecture=_architecture;
- (void)dealloc;
@property(readonly) XCDWARFDocument *document; // @synthesize document=_document;
- (id)initWithDocument:(id)arg1 path:(id)arg2 architecture:(id)arg3;
@property(readonly) DTMutableRangeArray *lineTable;
@property(readonly) NSString *path; // @synthesize path=_path;

@end

