//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/XCOrganizerNodeAdapter.h>

@interface XCOrganizerDeviceNodeAdapter : XCOrganizerNodeAdapter
{
}

- (id)actionMenuForDataNode:(id)arg1;
- (id)addMenuForDataNode:(id)arg1;
- (id)dataNode:(id)arg1 outlineView:(id)arg2 dataCellForTableColumn:(id)arg3;
- (void)dataNode:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3;
- (BOOL)dataNode:(id)arg1 shouldEditTableColumn:(id)arg2;
- (id)dataNode:(id)arg1 toolTipForTableColumn:(id)arg2;
- (id)removalConfirmationAlertForDataNode:(id)arg1;
- (void)removeDataNode:(id)arg1;

@end

