//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAlert, NSArray, NSDictionary, NSError, NSString, PBXProject, PBXProjectDocument, XCInvocationQueue, XCRefactoringModule, XCRefactoringStart, XCRefactoringTransformation;

@interface XCRefactoring : NSObject
{
    PBXProjectDocument *_projectDocument;
    PBXProject *_project;
    XCInvocationQueue *_queue;
    XCRefactoringModule *_module;
    NSString *_nextFile;
    float _complete;
    NSString *_localizedTaskDescriptionString;
    int _taskProgressType;
    XCRefactoringTransformation *_currentTransformation;
    int _fileThreadInProgress;
    int _shouldStart;
    BOOL _subsequentFileThreadCanceled;
    NSDictionary *_initialInput;
    unsigned long long _fileChangeSetIndex;
    NSError *_applyingFileChangeSetsError;
    BOOL _currentFileChangeSetFinished;
    XCRefactoringStart *_waitingStart;
    NSAlert *_errorAlert;
    NSAlert *_discardChangesAlert;
    NSArray *_scmEditFilePaths;
    BOOL _cancelingCurrentSession;
}

+ (BOOL)_areAllBuildContextsAvailable:(id)arg1;
+ (BOOL)_isIndexingInProgress:(id)arg1;
+ (BOOL)canConvertToObjC2:(id)arg1;
+ (BOOL)canRefactorPerSelectionInTextView:(id)arg1;
- (void)_appliedChangesForFileChangeSet:(id)arg1 error:(id)arg2;
- (void)_beginActivityViewerIndeterminateTask;
- (void)_beginActivityViewerPreviewTask;
- (void)_cancelCommonSteps;
- (void)_continueRefactoring:(id)arg1;
- (void)_createModule;
- (void)_discardChangesAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)_editedFileContents;
- (void)_errorAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)_finishSCMEditOperation:(id)arg1;
- (BOOL)_handleUserInput:(id)arg1 transformKeyAndInvokeFileThread:(id)arg2 error:(id *)arg3;
- (void)_initialFileThread;
- (void)_initialFileThreadResult:(id)arg1;
- (void)_initialFileThreadShouldCancelSession:(id)arg1;
- (void)_initialFileThreadShouldCancelTransformation:(id)arg1;
- (void)_initialFileThreadShouldStartNothing:(id)arg1;
- (void)_initialFileThreadShouldStartSubsequentFileThread:(id)arg1;
- (void)_invokeInitialFileThread;
- (void)_invokeSubsequentFileThread;
- (id)_localized:(id)arg1;
- (id)_makeSCMEditOperationError:(id)arg1;
- (id)_queue;
- (void)_releaseCurrentTransformation;
- (void)_runProgressDialogWithTitle:(id)arg1 window:(id *)arg2 session:(struct _NSModalSession **)arg3;
- (void)_setTaskDescriptionString:(id)arg1;
- (void)_startActivityViewerTask;
- (void)_startRefactoring:(id)arg1;
- (void)_stopActivityViewerTask;
- (void)_subsequentFileThread;
- (void)_subsequentFileThreadPostResultCommonSteps;
- (void)_subsequentFileThreadResult:(id)arg1;
- (void)_subsequentFileThreadShouldCancelSession:(id)arg1;
- (void)_subsequentFileThreadShouldCancelTransformation:(id)arg1;
- (void)_subsequentFileThreadShouldStartNothing:(id)arg1;
- (void)_subsequentFileThreadShouldStartSubsequentFileThread:(id)arg1;
- (void)_updateWithInfoArray:(id)arg1;
- (void)applyCurrentTransformation;
- (void)cancelCurrentSession;
- (void)cancelCurrentSessionDontCloseWindow;
- (void)cancelCurrentTransformation;
- (void)convertToObjC2;
- (id)dataForFilePath:(id)arg1;
- (void)dealloc;
- (void)displayError:(id)arg1;
- (id)initWithProjectDocument:(id)arg1 project:(id)arg2;
- (BOOL)postApplyForExistingTextFileChangeSet:(id)arg1 context:(void *)arg2 error:(id *)arg3;
- (id)postInitialFileInfoForTransformKey:(id)arg1 error:(id *)arg2;
- (BOOL)preApplyForExistingTextFileChangeSet:(id)arg1 context:(void **)arg2 error:(id *)arg3;
- (BOOL)previewWithSetUpModule:(id)arg1 transformKey:(id)arg2;
- (id)project;
- (void)refactorWithFile:(id)arg1 lineInfo:(struct _XCRefactoringLineInfo)arg2 selectionValidator:(id)arg3;
- (BOOL)setData:(id)arg1 context:(void *)arg2 error:(id *)arg3;
- (BOOL)setString:(id)arg1 context:(void *)arg2 error:(id *)arg3;
- (id)setUpInfoForTransformKey:(id)arg1 error:(id *)arg2;
- (void)shouldCollectCurrentTransformation;
- (id)taskBadge;
- (BOOL)taskCanBeStoppedManually;
- (id)taskDescriptionString;
- (id)taskDisplayString;
- (id)taskIdentifier;
- (float)taskPercentComplete;
- (int)taskProgressType;
- (BOOL)taskRequiresIntervention;
- (BOOL)taskStopRunning;

@end

