//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsInterface/PBXProjectModule.h>

@class NSControl, XCRefactoringSetUpModule;

@interface XCRefactoringControlModule : PBXProjectModule
{
    NSControl *control;
    XCRefactoringSetUpModule *_setUpModule;
}

- (id)control;
- (id)init;
- (void)restoreTransformationSnapshot;
- (BOOL)setSetUpModule:(id)arg1 error:(id *)arg2;
- (id)setUpModule;
- (void)sizeToFit;
- (BOOL)transformationAllowedToChange:(id *)arg1;

@end

