//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTAnalyticsAppIdentifier, DVTAnalyticsCrashPointList, NSError;

@interface _DVTCrashPointAppStoreListResult : NSObject
{
    DVTAnalyticsAppIdentifier *_appIdentifier;
    NSError *_error;
    DVTAnalyticsCrashPointList *_list;
}

+ (id)resultWithAppIdentifier:(id)arg1 listOrNil:(id)arg2 errorOrNil:(id)arg3;
- (void).cxx_destruct;
@property(readonly) DVTAnalyticsAppIdentifier *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(readonly) NSError *error; // @synthesize error=_error;
@property(readonly) DVTAnalyticsCrashPointList *list; // @synthesize list=_list;

@end

