//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTFilePath, NSArray, NSData;

@interface DVTAnalyticsSnapshot : NSObject
{
    long long _operation;
    DVTFilePath *_filePath;
    NSData *_data;
    NSArray *_childSnapshots;
}

+ (id)snapshotForDeletionWithFilePath:(id)arg1 childSnapshots:(id)arg2;
+ (id)snapshotWithFilePath:(id)arg1 data:(id)arg2 childSnapshots:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *childSnapshots; // @synthesize childSnapshots=_childSnapshots;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (id)description;
@property(readonly, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (id)init;
- (id)initWithFilePath:(id)arg1 data:(id)arg2 operation:(long long)arg3 childSnapshots:(id)arg4;
@property(readonly, nonatomic) long long operation; // @synthesize operation=_operation;
- (BOOL)writeToCachePathWithError:(id *)arg1;

@end

