//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEInMemoryLogStore.h>

@interface IDEInMemoryLogStore_Impl : IDEInMemoryLogStore
{
}

- (void)_removeLogRecord:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)addLog:(id)arg1 entityIdentifier:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (BOOL)preserveOldLogs;
- (void)setPreserveOldLogs:(BOOL)arg1;

@end

