//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDEProvisioningBasicProfile-Protocol.h>

@class IDEProfileSpecifier, NSString;
@protocol DVTProvisioningProfile, IDEProvisioningBasicTeam;

@interface IDEProvisioningBasicProfile : NSObject <IDEProvisioningBasicProfile>
{
    IDEProfileSpecifier *_specifier;
    id <DVTProvisioningProfile> _provisioningProfile;
}

+ (id)basicMissingProfileWithSpecifier:(id)arg1;
+ (id)basicProfileWithDVTProvisioningProfile:(id)arg1;
- (void).cxx_destruct;
@property(readonly) NSString *UUID;
@property(readonly) NSString *automaticIdentitySelector;
- (id)description;
@property(readonly) BOOL existsOnDisk;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSString *name;
@property(readonly) id <DVTProvisioningProfile> provisioningProfile; // @synthesize provisioningProfile=_provisioningProfile;
@property(readonly) IDEProfileSpecifier *specifier; // @synthesize specifier=_specifier;
@property(readonly) id <IDEProvisioningBasicTeam> team;

@end

