//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DTTimelineDecorator : NSObject
{
}

- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (void)decorateContainer:(struct DTTimelineDecorationContainer *)arg1 qualityOfService:(unsigned int)arg2 priority:(int)arg3 group:(id)arg4;
- (id)decorateInspectionRanges:(id)arg1;
- (void)decorateInspectionRanges:(id)arg1 qualityOfService:(unsigned int)arg2 priority:(int)arg3 group:(id)arg4;
- (BOOL)heightChangedForPlane:(id)arg1;
- (BOOL)mustDecorateOnMainThread;
- (BOOL)needsMajorMinorTickPOIs;
- (void)setDefaultsForPlane:(id)arg1;

@end

