//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTDocumentLocation, NSArray, NSError, NSString;

@interface _TtC16DVTDocumentation24DVTDocumentationResponse : NSObject
{
    // Error parsing type: , name: entities
    // Error parsing type: , name: symbolInfos
    // Error parsing type: , name: errors
    // Error parsing type: , name: _hash.storage
    // Error parsing type: , name: abstract.storage
}

- (CDUnknownBlockType).cxx_destruct;
@property(nonatomic, copy) NSString *abstract;
@property(nonatomic, readonly) DVTDocumentLocation *declarationLocation;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSError *error;
@property(nonatomic, readonly) NSArray *errors; // @synthesize errors;
@property(nonatomic, readonly) long long hash;
- (id)init;
- (BOOL)isEqualTo:(id)arg1;
@property(nonatomic, readonly) NSString *name;
@property(nonatomic, readonly) NSString *parentName;
@property(nonatomic, readonly) NSString *qualifiedDisplayName;
- (void)reportToMessageTracerForContext:(const char *)arg1;

@end

