//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDBase/XDUMLClassImp.h>

#import <XDBase/XDSCClassifier-Protocol.h>

@class NSString, XDElementReference;

@interface XDSCClass : XDUMLClassImp <XDSCClassifier>
{
    struct _XDSCClassCompactVariables _compactVariables;
    XDElementReference *_elementReference;
    long long _fileRetainCount;
}

- (id)browserDisplayName;
- (id)derivedClassifiers;
- (id)diagramDisplayName;
- (id)displayAllProperties;
- (id)displayKind;
- (id)displayLanguage;
- (id)displaySupers;
- (id)displayVisibility;
- (id)elementReference;
- (void)encodeWithCoder:(id)arg1;
- (id)fileRelease;
- (id)fileRetain;
- (long long)fileRetainCount;
- (BOOL)hasDocumentation;
- (id)hiddenPerFilterString;
- (id)initWithCoder:(id)arg1;
- (void)insertObject:(id)arg1 inOwnedCommentsAtIndex:(unsigned long long)arg2;
- (BOOL)isCategory;
- (BOOL)isHidden;
- (BOOL)isInProject;
- (long long)isIndividuallyHidden;
- (BOOL)isTreeLeaf;
- (unsigned long long)language;
- (id)ownedAttributes;
- (id)ownedOperations;
- (void)removeObjectFromOwnedCommentsAtIndex:(unsigned long long)arg1;
- (void)setElementReference:(id)arg1;
- (void)setFilterState:(unsigned long long)arg1;
- (void)setHasDocumentation:(BOOL)arg1;
- (void)setIsCategory:(BOOL)arg1;
- (void)setIsInProject:(BOOL)arg1;
- (void)setIsIndividuallyHidden:(long long)arg1;
- (void)setLanguage:(unsigned long long)arg1;
- (void)setNeedsSyncing;
- (void)setShowInBrowser:(BOOL)arg1;
- (void)setShowOption:(unsigned long long)arg1;
- (BOOL)shouldEncodeBucketNamed:(id)arg1;
- (BOOL)showInBrowser;
- (unsigned long long)showOption;
- (id)tooltip;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

