//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDBase/XDUMLNamespaceImp.h>

#import <XDBase/XDUMLOperation-Protocol.h>

@class NSMutableArray, NSString;

@interface XDUMLOperationImp : XDUMLNamespaceImp <XDUMLOperation>
{
    BOOL _isStatic;
    BOOL _isLeaf;
    BOOL _isQuery;
    NSMutableArray *_parameters;
    NSMutableArray *_returnResults;
}

- (void)dealloc;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (id)featuringClassifiers;
- (id)formalParameters;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (BOOL)isLeaf;
- (BOOL)isOrdered;
- (BOOL)isQuery;
- (BOOL)isStatic;
- (BOOL)isUnique;
- (BOOL)lazyCreateBucketNamed:(id)arg1;
- (long long)lower;
- (id)members;
- (id)newParameterWithName:(id)arg1;
- (id)newReturnParameterWithType:(id)arg1;
- (id)ownedMembers;
- (id)ownedParameters;
- (id)ownerClass;
- (id)parameters;
- (id)raisedExceptions;
- (id)redefinedElement;
- (id)redefinedOperations;
- (id)redefinitionContext;
- (id)returnResult;
- (void)setIsLeaf:(BOOL)arg1;
- (void)setIsQuery:(BOOL)arg1;
- (void)setIsStatic:(BOOL)arg1;
- (void)setOwnedParameters:(id)arg1;
- (id)type;
- (long long)upper;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

