//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSControl, NSPredicateOperator, NSPredicateView, NSString;

@protocol NSPredicateTypeController
- (NSControl *)firstKeyView;
- (id)initForPredicateView:(NSPredicateView *)arg1 forType:(NSString *)arg2 forKey:(NSString *)arg3 toMany:(BOOL)arg4;
- (NSControl *)lastKeyView;
- (id)leafPredicate;
- (NSString *)operatorForBetween;
- (NSString *)operatorForQop:(NSPredicateOperator *)arg1;
- (BOOL)passInString:(NSString *)arg1;
- (NSArray *)possibleOperators;
- (NSPredicateOperator *)qopForOperator:(NSString *)arg1;
- (void)remove;
- (NSString *)setLeafPredicate:(id)arg1;
- (void)setOperator:(NSString *)arg1;
- (struct CGSize)setPosition:(struct CGPoint)arg1 secondRow:(struct CGPoint)arg2;
- (NSString *)stringToPassOn;
- (NSString *)stringValue;
@end

