//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDInterface/XDPluginController.h>

@protocol XDModelCreationStatusObserving;

@interface XDDocumentController : XDPluginController
{
    id <XDModelCreationStatusObserving> _statusObserver;
    id _xcodeProject;
    struct {
        unsigned int isloadedDuringProjectLoading:1;
        unsigned int RESERVED:31;
    } _xdpcFlags;
}

- (BOOL)completedModelContent;
- (BOOL)isLoadedDuringProjectLoading;
- (void)notifyDocumentModelChangedNotUndoable;
- (void)printInfoDidChange;
- (void)setLoadedDuringProjectLoading:(BOOL)arg1;
- (void)setStatusObserver:(id)arg1;
- (void)setXcodeProject:(id)arg1;
- (id)xcodeProject;

@end

