//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XDInterface/XDDrawingStyle.h>

@class NSColor;

@interface XDFillStyle : XDDrawingStyle
{
    NSColor *_fillColor;
    double _gradientAngle;
    NSColor *_gradientColor;
    struct _XDFillStyleFlags _fsFlags;
}

+ (void)initialize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)drawGraphic:(id)arg1 inView:(id)arg2;
- (void)drawGraphic:(id)arg1 inView:(id)arg2 usingFillType:(int)arg3;
- (BOOL)drawsFill;
- (void)encodeWithCoder:(id)arg1;
- (id)fillColor;
- (int)fillType;
- (double)gradientAngle;
- (id)gradientColor;
- (id)initWithCoder:(id)arg1;
- (id)initWithGraphic:(id)arg1;
- (void)setDrawsFill:(BOOL)arg1;
- (void)setFillColor:(id)arg1;
- (void)setFillType:(int)arg1;
- (void)setGradientAngle:(double)arg1;
- (void)setGradientColor:(id)arg1;

@end

