//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

#import <DVTSourceControl/DVTSourceControlCancellable-Protocol.h>

@class DVTSourceControlManager, DVTSourceControlSystem, NSString;

@interface DVTSourceControlOperation : NSOperation <DVTSourceControlCancellable>
{
    BOOL _isExecuting;
    BOOL _isFinished;
    BOOL _isCanceled;
    BOOL suppressAuthenticationFailure;
    id context;
    CDUnknownBlockType _operationBlock;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _incrementalLogBlock;
    CDUnknownBlockType _terminationBlock;
    DVTSourceControlManager *_sourceControlManager;
    DVTSourceControlSystem *_system;
}

+ (id)sourceControlOperationStateQueue;
- (void).cxx_destruct;
- (void)_startOperation;
- (void)cancel;
@property __weak id context; // @synthesize context;
- (void)finish;
@property(readonly) NSString *identifier;
@property(copy) CDUnknownBlockType incrementalLogBlock; // @synthesize incrementalLogBlock=_incrementalLogBlock;
- (id)initWithSourceControlManager:(id)arg1 system:(id)arg2 operationBlock:(CDUnknownBlockType)arg3 incrementalLogBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5 terminationBlock:(CDUnknownBlockType)arg6;
- (id)initWithSourceControlManager:(id)arg1 system:(id)arg2 operationBlock:(CDUnknownBlockType)arg3 incrementalLogBlock:(CDUnknownBlockType)arg4 terminationBlock:(CDUnknownBlockType)arg5;
- (id)initWithSourceControlManager:(id)arg1 system:(id)arg2 operationBlock:(CDUnknownBlockType)arg3 progressBlock:(CDUnknownBlockType)arg4 terminationBlock:(CDUnknownBlockType)arg5;
- (id)initWithSourceControlManager:(id)arg1 system:(id)arg2 operationBlock:(CDUnknownBlockType)arg3 terminationBlock:(CDUnknownBlockType)arg4;
- (BOOL)isExecuting;
- (BOOL)isFinished;
@property(copy) CDUnknownBlockType operationBlock; // @synthesize operationBlock=_operationBlock;
@property(copy) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void)retry;
@property(retain, nonatomic) DVTSourceControlManager *sourceControlManager; // @synthesize sourceControlManager=_sourceControlManager;
@property BOOL suppressAuthenticationFailure; // @synthesize suppressAuthenticationFailure;
@property(retain, nonatomic) DVTSourceControlSystem *system; // @synthesize system=_system;
@property(copy) CDUnknownBlockType terminationBlock; // @synthesize terminationBlock=_terminationBlock;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

