//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTSourceControl/DVTSourceControlRevisionLocation.h>

@class NSString;

@interface DVTSourceControlPathLocation : DVTSourceControlRevisionLocation
{
    NSString *_relativePath;
}

+ (id)defaultImage;
+ (id)rootPathLocation;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)_init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dictionaryRepresentationWithOptions:(unsigned long long)arg1;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithRelativePath:(id)arg1;
- (id)initWithRevision:(id)arg1;
@property(readonly, getter=isDirectory) BOOL directory;
- (BOOL)isEqual:(id)arg1;
- (id)parentPathLocation;
- (id)pathLocationByAppendingPath:(id)arg1;
@property(retain) NSString *relativePath; // @synthesize relativePath=_relativePath;

@end

