//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface XRCapabilityContext : NSObject
{
    struct _opaque_pthread_rwlock_t _lock;
    NSMutableDictionary *_capabilities;
    NSMutableDictionary *_unimplementedResponses;
}

+ (void)announceUsedCapability:(id)arg1 version:(unsigned long long)arg2;
+ (id)currentContextSet;
+ (void)enterContextSet:(id)arg1;
+ (void)leaveContextSet:(id)arg1;
- (void).cxx_destruct;
- (void)addToCurrentContextSet;
- (void)announceUsedCapability:(id)arg1 version:(unsigned long long)arg2;
- (void)dealloc;
- (void)enumerateRequiredCapabilities:(CDUnknownBlockType)arg1;
- (id)init;
- (void)removeFromCurrentContextSet;

@end

