//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTInstrumentsUtilities/XRIndexSet.h>

@interface XRMutableIndexSet : XRIndexSet
{
}

- (void)_addRange:(struct _XRIndexRange)arg1;
- (void)_insertRange:(struct _XRIndexRange)arg1 atIndex:(unsigned long long)arg2;
- (void)_mergeRangesFromIndex:(unsigned long long)arg1;
- (void)addIndex:(unsigned long long)arg1;
- (void)addIndexesInRange:(struct _XRIndexRange)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)growArray;

@end

