//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSUI/NSObject-Protocol.h>

@class NSAttributedString, NSString;

@protocol DVTRadar_Associate <NSObject>
@property(copy, nonatomic) NSString *assignee;
@property(nonatomic) unsigned long long duplicateOfProblemID;
@property(nonatomic) unsigned long long priority;
@property(readonly, copy, nonatomic) NSAttributedString *radarSummary;
@property(copy, nonatomic) NSString *resolution;
@property(copy, nonatomic) NSString *state;
@property(copy, nonatomic) NSString *substate;
@end

