//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSUI/NSObject-Protocol.h>

@class DVTDocumentLocation, NSArray, NSError, XCSBot, XCSBotSupportingEditor, XCSIntegration;

@protocol XCSBotSupportingEditorHostedViewController <NSObject>
+ (BOOL)instancesCanContainDocumentLocation:(DVTDocumentLocation *)arg1;
@property(retain, nonatomic) XCSBot *bot;
@property(retain, nonatomic) XCSBotSupportingEditor *botSupportingEditor;
@property(readonly, copy) NSArray *currentSelectedDocumentLocations;
@property(readonly, copy) NSArray *currentSelectedItems;
@property(retain, nonatomic) XCSIntegration *integration;
- (void)selectDocumentLocations:(NSArray *)arg1;
- (void)setError:(NSError *)arg1;
@end

