//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DVTSourceControlRemoteRepository, NSError, NSString;

@interface XCSUICreateBotRepositoryIssue : NSObject
{
    BOOL _selected;
    NSError *_issue;
    unsigned long long _type;
    DVTSourceControlRemoteRepository *_repository;
    NSString *_workingCopyLocation;
    unsigned long long _resolution;
    NSString *_issueFingerprint;
}

- (void).cxx_destruct;
- (id)initWithRepository:(id)arg1 workingCopyLocation:(id)arg2 issue:(id)arg3;
@property(readonly) NSError *issue; // @synthesize issue=_issue;
@property(readonly) NSString *issueDisplayString;
@property(readonly) NSString *issueFingerprint; // @synthesize issueFingerprint=_issueFingerprint;
@property(readonly) __weak DVTSourceControlRemoteRepository *repository; // @synthesize repository=_repository;
@property(readonly) NSString *repositoryDisplayString;
@property unsigned long long resolution; // @synthesize resolution=_resolution;
@property BOOL selected; // @synthesize selected=_selected;
@property unsigned long long type; // @synthesize type=_type;
@property(readonly) NSString *workingCopyLocation; // @synthesize workingCopyLocation=_workingCopyLocation;

@end

