//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSColor, NSString;

@interface XCSUIBotSummaryStackedBarGraphBar : NSObject
{
    NSString *_barIdentifier;
    NSString *_barValue;
    NSColor *_barFillColor;
    NSColor *_barStrokeColor;
    struct CGRect _layoutRect;
}

+ (id)barDataWithIdentifier:(id)arg1 barValue:(id)arg2 barFillColor:(id)arg3 barStrokeColor:(id)arg4;
- (void).cxx_destruct;
@property(copy) NSColor *barFillColor; // @synthesize barFillColor=_barFillColor;
@property(copy) NSString *barIdentifier; // @synthesize barIdentifier=_barIdentifier;
@property(copy) NSColor *barStrokeColor; // @synthesize barStrokeColor=_barStrokeColor;
@property(copy) NSString *barValue; // @synthesize barValue=_barValue;
- (id)description;
@property struct CGRect layoutRect; // @synthesize layoutRect=_layoutRect;

@end

