//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEKit/IDEAssistant.h>

@class XCSUIBotDefinition_DevicePickerEditor, XCSUIBotDefinition_DevicePickerEditor_Legacy;

@interface XCSUICreateBotDevicePickerAssistant : IDEAssistant
{
    BOOL _viewIsInstalled;
    XCSUIBotDefinition_DevicePickerEditor_Legacy *_legacyDevicePickerEditor;
    XCSUIBotDefinition_DevicePickerEditor *_devicePickerEditor;
}

+ (id)keyPathsForValuesAffectingCanGoForward;
- (void).cxx_destruct;
- (id)assistantTitle;
- (BOOL)canGoForward;
- (id)createBotAssistantContext;
@property(retain, nonatomic) XCSUIBotDefinition_DevicePickerEditor *devicePickerEditor; // @synthesize devicePickerEditor=_devicePickerEditor;
@property(retain, nonatomic) XCSUIBotDefinition_DevicePickerEditor_Legacy *legacyDevicePickerEditor; // @synthesize legacyDevicePickerEditor=_legacyDevicePickerEditor;
- (void)loadView;
- (id)nextAssistantIdentifier;
- (void)primitiveInvalidate;
@property(nonatomic) BOOL viewIsInstalled; // @synthesize viewIsInstalled=_viewIsInstalled;
- (void)viewDidInstall;
- (void)viewWillUninstall;

@end

