//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSEnumerator.h>

@class JKClassLibrary, NSArray, NSString;

@interface JKJavaPackageEnumerator : NSEnumerator
{
    NSString *_name;
    JKClassLibrary *_library;
    NSArray *_packages;
    NSArray *_classNames;
    unsigned long long _index;
    NSEnumerator *_next;
    BOOL _enumerateClassNames;
}

- (void)_nextEnumerator;
- (void)dealloc;
- (id)initWithPackage:(id)arg1 enumerateClassNames:(BOOL)arg2;
- (id)nextObject;

@end

