//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JKJavaAttribute : NSObject
{
}

+ (id)attributeWithName:(id)arg1 byteStream:(struct JKByteStream *)arg2 constantPool:(CDStruct_202c1fbd *)arg3;
+ (void)initialize;
+ (void)registerAttributeClass:(Class)arg1 forName:(id)arg2;
- (id)typeName;

@end

