//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXNativeTarget.h>

@interface PBXAggregateTarget : PBXNativeTarget
{
}

+ (id)categorizedTargetName;
+ (id)standardBuildPhaseClasses;
+ (id)targetTypeDisplayName;
- (id)buildSettingsPanes;
- (BOOL)canInstallHeaders;
- (BOOL)canPackageHeaders;
- (id)defaultProductTypeIdentifierByAnalyzingConfiguration;
- (BOOL)hasUserConfigurableBuildRules;
- (BOOL)isAggregate;
- (id)productReferenceExpectedFileTypeForConfigurationNamed:(id)arg1;
- (BOOL)productReferenceIsExecutable;
- (id)relevantToolSpecifications;
- (id)relevantToolSpecificationsForConfigurationNamed:(id)arg1;
- (id)relevantToolSpecificationsForConfigurationsNamed:(id)arg1;
- (BOOL)wantsProductSettings;

@end

