//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXBookmark.h>

@class PBXBuildStyle;

@interface PBXBuildStyleBookmark : PBXBookmark
{
    PBXBuildStyle *_buildStyle;
}

+ (id)archivableRelationships;
+ (id)archiveNameForKey:(id)arg1;
- (id)buildStyle;
- (void)dealloc;
- (id)defaultName;
- (unsigned long long)hash;
- (id)initWithBuildStyle:(id)arg1;
- (id)initWithFileReference:(id)arg1;
- (id)innerDescription;
- (BOOL)isEqual:(id)arg1;

@end

