//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXBreakpoint.h>

#import <DevToolsCore/NSCopying-Protocol.h>

@class NSString;

@interface PBXFileBreakpoint : PBXBreakpoint <NSCopying>
{
    unsigned long long _debugTimestamp;
    NSString *_functionName;
}

+ (id)archivableAttributes;
+ (id)archivableRelationships;
+ (id)breakpointWithFileReference:(id)arg1 lineNumber:(unsigned long long)arg2;
+ (id)breakpointWithTextBookmark:(id)arg1;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (long long)compareToBreakpoint:(id)arg1;
- (long long)compareUsingLineNumber:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)displayString;
- (id)fileReference;
- (id)functionName;
- (id)gidCommentForArchive;
- (id)init;
- (id)initWithFileReference:(id)arg1 lineNumber:(unsigned long long)arg2;
- (id)initWithTextBookmark:(id)arg1;
- (id)innerDescription;
- (id)locationDisplay;
- (void)purify;
- (id)readFromPListUnarchiver:(id)arg1;
- (void)release;
- (id)retain;
- (void)setDebugTimestamp:(unsigned long long)arg1;
- (void)setFileReference:(id)arg1;
- (void)setFunctionName:(id)arg1;
- (void)willChange;

@end

