//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXBuildPhase.h>

@interface PBXJavaArchiveBuildPhase : PBXBuildPhase
{
}

+ (id)defaultName;
+ (id)identifier;
- (BOOL)acceptsVariantGroups;
- (Class)dependencyGraphSnapshotClass;
- (BOOL)insertBuildFiles:(id)arg1 atIndex:(unsigned long long)arg2;

@end

