//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXCodeCompletion.h>

@interface XCJavaCodeCompletion : PBXCodeCompletion
{
}

- (void)addScopeForIndex:(id)arg1 package:(id)arg2 imports:(id)arg3;
- (id)completeExpression:(id)arg1 typeName:(id)arg2;
- (id)completeExternalDeclaration:(id)arg1 typeName:(id)arg2;
- (id)completeImportStatement:(id)arg1 typeName:(id)arg2;
- (id)completePackageStatement:(id)arg1 typeName:(id)arg2;
- (void)parseLocals:(id)arg1;
- (id)typeOfExpression:(id)arg1 resolveType:(BOOL)arg2;

@end

