//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString, NSTimer;

@interface XCPerformanceMetric : NSObject
{
    NSString *_aspect;
    unsigned long long _logLevel;
    NSString *_label;
    NSString *_context;
    NSString *_result;
    void *_identifier;
    double _start;
    NSString *_startMemoryStats;
    double _end;
    double _expectedDuration;
    double _tolerance;
    NSMutableArray *_checkpoints;
    struct __CFRunLoopObserver *_runLoopObserver;
    XCPerformanceMetric *_nextMetric;
    BOOL _stopWhenRunLoopIdle;
    double _lastRunLoopPollTime;
    double _maxRunLoopBusyInterval;
    NSTimer *_expireTimer;
    double _expireInterval;
}

+ (void)initialize;
+ (id)metricWithIdentifier:(void *)arg1;
+ (id)startedMetricForAspect:(id)arg1 logLevel:(unsigned long long)arg2 label:(id)arg3 isQAMetric:(BOOL)arg4;
- (void)_registerForRunLoopCallouts;
- (void)checkpoint:(id)arg1;
- (void)dealloc;
- (void)expire:(id)arg1;
- (id)initWithAspect:(id)arg1 logLevel:(unsigned long long)arg2 label:(id)arg3;
- (void)monitorRunLoop;
- (void)runLoopBeforeSources;
- (void)runLoopBeforeTimers;
- (void)runLoopSleeping;
- (void)runLoopWaking;
- (void)setContextString:(id)arg1;
- (void)setEndTime;
- (void)setExpectedDuration:(double)arg1 tolerance:(double)arg2;
- (void)setExpireInterval:(double)arg1;
- (void)setIdentifier:(void *)arg1;
- (void)setResultString:(id)arg1;
- (void)setStartTime;
- (void)stopWhenRunLoopIdle;
- (void)writeMetricData;

@end

