//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <DevToolsCore/XCRemoteComputer-Protocol.h>

@class NSMutableDictionary, NSString, XCPlatformSpecification, XCRemoteExecutable;

@interface XCRemoteComputer : NSObject <XCRemoteComputer>
{
    BOOL deviceAvailable;
    NSMutableDictionary *_data;
    XCRemoteExecutable *currentRemoteExecutable;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)beginListeningForDevices;
+ (BOOL)handleDroppedFile:(id)arg1;
+ (id)itemWithPlistRepresentation:(id)arg1;
+ (id)keyPathsForValuesAffectingCachePath;
+ (id)keyPathsForValuesAffectingDeviceArchitecture;
+ (id)keyPathsForValuesAffectingDeviceIdentifier;
+ (id)keyPathsForValuesAffectingDeviceIsIgnored;
+ (id)keyPathsForValuesAffectingDeviceName;
+ (id)keyPathsForValuesAffectingDeviceSoftwareVersion;
+ (id)keyPathsForValuesAffectingPlatform;
+ (void)loadOrganizerCategories;
+ (BOOL)shouldHandleDroppedFile:(id)arg1;
- (void)_willExecuteComplete;
@property(readonly) NSString *cachePath;
- (BOOL)canExecute;
@property(readonly) BOOL canRenameDevice;
- (id)currentRemoteExecutable;
@property(readonly) NSMutableDictionary *data; // @synthesize data=_data;
- (void)dealloc;
- (int)debuggerArchitectureMode;
- (id)debuggerAttachList;
@property(readonly, copy) NSString *deviceArchitecture;
@property BOOL deviceAvailable; // @synthesize deviceAvailable;
@property(readonly) BOOL deviceHasUI;
@property(copy) NSString *deviceIdentifier;
@property(readonly) BOOL deviceIsBusy;
@property BOOL deviceIsIgnored;
@property(readonly) BOOL deviceIsTransient;
@property(copy) NSString *deviceName;
@property(copy) NSString *deviceSoftwareVersion;
- (void)didExecute:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)init;
- (id)initWithPlistRepresentation:(id)arg1;
- (void)invalidate;
- (BOOL)isEqual:(id)arg1;
@property(readonly) XCPlatformSpecification *platform;
@property(readonly, copy) NSString *platformIdentifier;
- (id)plistRepresentation;
- (BOOL)preflightExecutable:(id)arg1;
- (void)renameDevice:(id)arg1;
- (id)setCurrentExecutable:(id)arg1;
- (void)setDeviceArchitecture:(id)arg1;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;
- (BOOL)shouldApplicationTerminate;
- (BOOL)useAsyncWillExecute;
- (void)willBeForgotten;
- (BOOL)willExecute:(id)arg1 debug:(BOOL)arg2 onPort:(long long *)arg3 performInstall:(BOOL)arg4;
- (void)willExecuteAsync:(id)arg1 shouldInstall:(BOOL)arg2;
- (void)willExecuteCompleted;
- (void)willExecuteFailed;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

