//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/XCRefactoringTransformationSpecificLogic.h>

@interface XCRefactoringEncapsulateSpecificLogic : XCRefactoringTransformationSpecificLogic
{
}

- (BOOL)getClass:(Class *)arg1 declaration:(id *)arg2 fromASTNode:(id)arg3 mainThreadArguments:(id)arg4 error:(id *)arg5;
- (id)localizedSnapshotTitle:(id)arg1;
- (BOOL)modifyAllFiles:(id)arg1 mainThreadArguments:(id)arg2 error:(id *)arg3;
- (id)preliminaryRelatedNames:(id)arg1;
- (id)setUpInfo:(id)arg1;
- (id)transformParamDict:(id)arg1;

@end

