//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString, XCRefactoringFileChangeSetAsynchronousContext;

@interface XCRefactoringFileChangeSet : NSObject
{
    NSString *_filePath;
    NSMutableArray *_changes;
    id _delegate;
    long long _numberOfUserVisibleChanges;
    long long _numberOfUserAcceptedChanges;
    NSString *_newName;
    XCRefactoringFileChangeSetAsynchronousContext *_asynchronousContext;
    int _fileSystemStatus;
    BOOL _isFileSystemStatusCached;
}

+ (BOOL)canSupportFileAtPath:(id)arg1;
+ (Class)refactoringFileChangeSetClassForPath:(id)arg1;
+ (id)refactoringFileChangeSetForFileAtPath:(id)arg1 transformation:(id)arg2 error:(id *)arg3;
+ (id)supportedFileTypes;
- (void)_attemptToUnlockLockedFile:(id)arg1;
- (void)_setFileSystemStatus:(int)arg1;
- (void)addChange:(id)arg1;
- (void)applyChangesWithDelegate:(id)arg1 project:(id)arg2 callbackTarget:(id)arg3 selector:(SEL)arg4;
- (BOOL)applyChangesWithDelegate:(id)arg1 project:(id)arg2 error:(id *)arg3;
- (id)asynchronousContext;
- (BOOL)canApplyChangesWithProject:(id)arg1 error:(id *)arg2;
- (BOOL)canRenameFileInProject:(id)arg1 error:(id *)arg2;
- (id)changes;
- (void)dealloc;
- (id)delegate;
- (id)description;
- (void)eraseAsynchronousContext;
- (id)filePath;
- (id)filePathForWritableCheck;
- (int)fileSystemStatusFromProject:(id)arg1 useCached:(BOOL)arg2;
- (id)initWithFilePath:(id)arg1;
- (BOOL)isEqualToFileChangeSet:(id)arg1;
- (BOOL)mayRequireFileCacheRegeneration;
- (id)newFilePath;
- (id)newName;
- (long long)numberOfChanges;
- (long long)numberOfUserAcceptedChanges;
- (long long)numberOfUserVisibleChanges;
- (BOOL)postApply:(id *)arg1 context:(void *)arg2;
- (void)postRenameApplyChangesWithDelegate:(id)arg1 project:(id)arg2 callbackTarget:(id)arg3 selector:(SEL)arg4;
- (BOOL)preApply:(id *)arg1 context:(void **)arg2;
- (void)renameFileInProject:(id)arg1 callbackTarget:(id)arg2 selector:(SEL)arg3;
- (void)renamedFileAtPath:(id)arg1 to:(id)arg2 error:(id)arg3;
- (void)saveAsynchronousContextWithDelegate:(id)arg1 project:(id)arg2 callbackTarget:(id)arg3 selector:(SEL)arg4;
- (void)setNewName:(id)arg1;
- (void)setNumberOfUserAcceptedChanges:(long long)arg1;
- (void)setNumberOfUserVisibleChanges:(long long)arg1;
- (BOOL)willRenameFile;

@end

