//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, XCRefactoringTextFileChange;

@interface XCRefactoringEditInfo : NSObject
{
    XCRefactoringTextFileChange *_textFileChange;
    struct _NSRange _originalTextCharacterRange;
    NSString *_originalString;
    struct _XCRefactoringLineInfo _newTextLineInfo;
}

- (void)dealloc;
- (id)description;
- (id)initWithTextFileChange:(id)arg1 originalTextCharacterRange:(struct _NSRange)arg2 originalString:(id)arg3 newTextLineInfo:(struct _XCRefactoringLineInfo)arg4;
@property(readonly) struct _XCRefactoringLineInfo newTextLineInfo; // @synthesize newTextLineInfo=_newTextLineInfo;
@property(readonly) NSString *originalString; // @synthesize originalString=_originalString;
@property(readonly) struct _NSRange originalTextCharacterRange; // @synthesize originalTextCharacterRange=_originalTextCharacterRange;
- (void)removeLineFromNewTextLineInfoRange;
- (void)shiftNewTextLineInfoByColumnDelta:(long long)arg1;
- (void)shiftNewTextLineInfoByLineDelta:(long long)arg1;
@property(readonly) XCRefactoringTextFileChange *textFileChange; // @synthesize textFileChange=_textFileChange;

@end

