//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/XCRefactoringNibFileChange.h>

@interface XCRefactoringNibFileClassChange : XCRefactoringNibFileChange
{
}

+ (id)commandString;
- (id)destinationClass;
- (void)setDestinationClass:(id)arg1;
- (void)setSourceClass:(id)arg1;
- (id)sourceClass;

@end

