//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSConditionLock, XCPath;

@interface XCSearchPath : NSObject
{
    XCPath *_path;
    unsigned int _isCaseSensitive:1;
    unsigned int _followsSymlinks:1;
    unsigned int _status:2;
    unsigned int RESERVED:28;
    XCSearchPath *_nextSearchPath;
    NSConditionLock *_lock;
}

+ (id)_searchPathRegistryDictionary;
+ (id)searchPathWithPath:(id)arg1;
- (void)_finishedScanning;
- (void)_scanDirectories;
- (id)absolutePathMatchingEntryName:(id)arg1;
- (unsigned long long)count;
- (void)dealloc;
- (void)finishLoading;
- (id)init;
- (id)initWithPath:(id)arg1;
- (id)initWithPath:(id)arg1 caseSensitive:(BOOL)arg2 followsSymlinks:(BOOL)arg3;
- (id)initWithPath:(id)arg1 followsSymlinks:(BOOL)arg2;
- (id)nextSearchPath;
- (id)path;
- (void)setNextSearchPath:(id)arg1;
- (void)startLoadingInBackground;
- (int)status;

@end

