//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImageView.h>

@interface _TtC9DVTMarkupP33_8D794F29D5B038FCB7B9F093D50033A415InlineImageView : NSImageView
{
    // Error parsing type: , name: range
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 range:(struct _NSRange)arg2;
@property(nonatomic, readonly) struct _NSRange range; // @synthesize range;

@end

