//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DocSetIndexSearch : NSObject
{
    struct __SKSearch *_search;
    BOOL _moreToSearch;
}

- (void)cancel;
- (void)dealloc;
- (unsigned long long)findMaximumMatches:(unsigned long long)arg1 inMaximumTime:(double)arg2 returningIDs:(long long *)arg3 andScores:(float *)arg4;
- (id)initWithIndex:(id)arg1 query:(id)arg2 options:(unsigned int)arg3;
- (BOOL)isFinished;
- (struct __SKSearch *)searchRef;

@end

