//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDETestingSpecifier-Protocol.h>

@class DVTObservingToken, IDEDeviceAppDataReference, IDELocationScenarioReference, NSArray, NSMutableArray, NSSet, NSString;
@protocol IDETestable;

@interface IDEConcreteTestingSpecifier : NSObject <IDETestingSpecifier>
{
    id <IDETestable> _testable;
    NSMutableArray *_mutableSkippedTests;
    IDEDeviceAppDataReference *_deviceAppDataReference;
    IDELocationScenarioReference *_locationScenarioReference;
    DVTObservingToken *_buildableValidityObservingToken;
    NSSet *_adHocTests;
    BOOL _skipped;
}

- (void).cxx_destruct;
@property(copy) NSSet *adHocTests;
@property(retain) IDEDeviceAppDataReference *deviceAppDataReference;
- (void)disableTest:(id)arg1;
- (void)enableTest:(id)arg1;
- (id)initWithTestable:(id)arg1;
@property(retain) IDELocationScenarioReference *locationScenarioReference;
@property BOOL skipped;
@property(copy) NSArray *skippedTests;
- (id)testable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

