//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEProvisioningProfile-Protocol.h>

@class IDEPortalProfileWrapper;
@protocol IDEEnhancedProvisioningProfile, IDEProvisioningLocalProfileState;

@protocol IDEEnhancedProvisioningProfile <IDEProvisioningProfile>
- (BOOL)isEqualToEnhancedProfile:(id <IDEEnhancedProvisioningProfile>)arg1;
@property(readonly, nonatomic) id <IDEProvisioningLocalProfileState> localState;
@property(readonly, nonatomic) IDEPortalProfileWrapper *portalProfileWrapper;
@property(readonly, nonatomic) unsigned long long state;
@end

