//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDEProvisioningEntitlementsOverrides : NSObject
{
    NSString *_appIdentifierPrefix;
    NSString *_teamIdentifierPrefix;
    NSString *_bundleIdentifier;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appIdentifierPrefix; // @synthesize appIdentifierPrefix=_appIdentifierPrefix;
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (id)description;
@property(retain, nonatomic) NSString *teamIdentifierPrefix; // @synthesize teamIdentifierPrefix=_teamIdentifierPrefix;

@end

