//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/IDEProvisioningTeam-Protocol.h>

@class NSSet, NSString;

@interface IDEProvisioningTeam : NSObject <IDEProvisioningTeam>
{
    BOOL _freeProvisioningTeam;
    NSString *_teamID;
    NSString *_name;
    NSString *_displayName;
    NSSet *_supportedCertificateKinds;
}

- (void).cxx_destruct;
- (BOOL)canCreateCertificatesOfKind:(id)arg1;
@property(readonly, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly) unsigned long long hash;
- (id)initWithPortalTeam:(id)arg1;
- (id)initWithTeamID:(id)arg1 name:(id)arg2 freeProvisioningTeam:(BOOL)arg3 supportedCertificateKinds:(id)arg4;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic, getter=isFreeProvisioningTeam) BOOL freeProvisioningTeam;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy) NSSet *supportedCertificateKinds; // @synthesize supportedCertificateKinds=_supportedCertificateKinds;
@property(readonly, nonatomic) NSString *teamID;
@property(readonly, nonatomic) NSString *teamName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

