//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IDEFoundation/IDEContainer.h>

@class DVTObservingToken, IDEPlaygroundCommonSharedContext, IDEPlaygroundSharedContext;

@interface IDEPlaygroundCommon : IDEContainer
{
    DVTObservingToken *_workspaceFinishedLoadingObservingToken;
    DVTObservingToken *_workspaceRunContextsObservingToken;
}

+ (BOOL)isOnlyUsedForUserInteraction;
+ (BOOL)isSourcesDirectorySubPath:(id)arg1;
- (void).cxx_destruct;
- (void)_addDirectoryPathObservationForPath:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_addPlaygroundDirectoriesObservation;
- (void)_changeContainerFilePath:(id)arg1 inContext:(id)arg2;
- (void)_didChangeContainerFilePath:(id)arg1 inContext:(id)arg2;
- (void)_registerReferenceWithContexts;
- (void)_removeDirectoryPathObservationForPath:(id)arg1;
- (void)_removePlaygroundDirectoriesObservation;
- (BOOL)_shouldRespondToFileChangeOnDisk;
- (id)_sourcesDirectoryPath;
- (void)_unregisterReferenceWithContexts;
- (void)_willChangeContainerFilePath:(id)arg1 inContext:(id)arg2;
- (void)_workspaceRunContextsChanged;
- (id)computedChildItemSubpathsEditable;
- (id)computedChildItemSubpathsFixed;
@property(readonly, nonatomic) IDEPlaygroundCommonSharedContext *context;
- (id)createRootGroup;
- (id)initWithFilePath:(id)arg1 extension:(id)arg2 workspace:(id)arg3 options:(id)arg4 error:(id *)arg5;
@property(readonly, nonatomic) IDEPlaygroundSharedContext *playgroundContext;
- (void)primitiveInvalidate;

@end

