//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEPlaygroundToolchainSupport : NSObject
{
}

+ (id)toolchain;
+ (id)toolchainFrameworksPathForPlatform:(id)arg1;
+ (BOOL)toolchainIsValidForPlaygroundExecutionAgainstPlatform:(id)arg1 error:(id *)arg2;
+ (id)toolchainLLDBPath;
+ (id)toolchainPath;
+ (id)toolchainPlatformPathForPlatform:(id)arg1;
+ (id)toolchainPlaygroundLoggerPathForPlatform:(id)arg1;
+ (id)toolchainPrivateFrameworksPathForPlatform:(id)arg1;
+ (id)toolchainSwiftLibrariesPathForPlatform:(id)arg1;
+ (id)toolchainSwiftStandardLibraryPathForPlatform:(id)arg1;

@end

