//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTFoundation/DVTCoverageDataContainer.h>

@class NSArray, NSNumber, NSString;

@interface IDESchemeActionCodeCoverageFile : DVTCoverageDataContainer
{
    NSString *_documentLocation;
    NSArray *_functions;
    NSArray *_lines;
    NSNumber *_functionCoverage;
}

- (void).cxx_destruct;
- (id)aggregateWithCodeCoverageFile:(id)arg1;
- (id)description;
@property(readonly, nonatomic) NSString *documentLocation; // @synthesize documentLocation=_documentLocation;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) NSNumber *functionCoverage; // @synthesize functionCoverage=_functionCoverage;
@property(readonly, nonatomic) NSArray *functions; // @synthesize functions=_functions;
- (id)initWithCoder:(id)arg1;
- (id)initWithDocumentLocation:(id)arg1 lines:(id)arg2 functions:(id)arg3 lineCoverage:(id)arg4 functionCoverage:(id)arg5;
@property(readonly, nonatomic) NSArray *lines; // @synthesize lines=_lines;
- (id)mergeLines:(id)arg1;
- (id)wrappedContainer;

@end

