//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <IDEFoundation/DVTInvalidation-Protocol.h>
#import <IDEFoundation/IDETestsInTestableObserver-Protocol.h>

@class DVTStackBacktrace, IDETestManager, NSMutableSet, NSString, NSURL;

@interface IDETestFileChangeBroker : NSObject <IDETestsInTestableObserver, DVTInvalidation>
{
    IDETestManager *_testManager;
    NSURL *_url;
    NSMutableSet *_fileObservers;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_notifyObserversTestsInFileUpdated;
- (void)addTestFileObserver:(id)arg1;
- (void)allTestablesChanged;
@property(readonly, copy) NSString *description;
- (BOOL)hasObservers;
- (id)initWithURL:(id)arg1 testManager:(id)arg2;
- (void)notifyAllTestablesChanged;
- (void)primitiveInvalidate;
- (void)removeTestFileObserver:(id)arg1;
- (void)testablesChanged:(id)arg1;
- (void)testsChanged:(id)arg1;
- (void)updateObservation;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

