//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DYGLProfileConstraints : NSObject
{
    CDStruct_96187c50 _constraintsData;
}

- (const CDStruct_96187c50 *)constRefToConstraintsData;
- (id)initWithConstraints:(const CDStruct_96187c50 *)arg1;
- (CDStruct_96187c50 *)refToConstraintsData;

@end

