//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DTXResourceTracker, NSArray;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface DTXTransport : NSObject
{
    NSObject<OS_dispatch_queue> *_serializer;
    NSObject<OS_dispatch_queue> *_handlerGuard;
    DTXResourceTracker *_tracker;
    CDUnknownBlockType _dataReceivedHandler;
    unsigned int _status;
    NSObject<OS_dispatch_semaphore> *_waitForResume;
    BOOL _resumed;
}

+ (BOOL)recognizesURL:(id)arg1;
+ (id)schemes;
- (BOOL)canReceive;
- (BOOL)canTransmit;
@property(copy, nonatomic) CDUnknownBlockType dataReceivedHandler;
- (void)dealloc;
- (void)disconnect;
- (id)init;
- (id)initWithLocalAddress:(id)arg1;
- (id)initWithRemoteAddress:(id)arg1;
@property(readonly) NSArray *localAddresses;
- (id)permittedBlockCompressionTypes;
- (void)received:(const char *)arg1 ofLength:(unsigned long long)arg2 destructor:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) DTXResourceTracker *resourceTracker; // @synthesize resourceTracker=_tracker;
@property unsigned int status; // @synthesize status=_status;
- (unsigned int)supportedDirections;
- (unsigned long long)transmit:(const void *)arg1 ofLength:(unsigned long long)arg2;
- (unsigned long long)transmit:(const void *)arg1 ofLength:(unsigned long long)arg2 withRateLimiter:(id)arg3;

@end

