//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DVTInstrumentsUtilities/NSObject-Protocol.h>

@class NSArray;

@protocol XRIntKeyedDictionaryImmutable <NSObject>
- (NSArray *)allObjects;
- (unsigned long long)count;
- (void)enumerateObjectsAndIntegerKeys:(void (^)(id, unsigned long long, char *))arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)objectForIntegerKey:(unsigned long long)arg1;
@end

