//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable, _XRLazyKVOBlockToken;
@protocol XRLazyKVOResponder;

@interface XRLazyKVOAdapter : NSObject
{
    NSMapTable *_keyPathsByContextByClz;
    NSMapTable *_keyPathsByContextByObj;
    struct unordered_set<const void *, std::__1::hash<const void *>, std::__1::equal_to<const void *>, std::__1::allocator<const void *>> _updatedContexts;
    struct unordered_set<const void *, std::__1::hash<const void *>, std::__1::equal_to<const void *>, std::__1::allocator<const void *>> _presentedContexts;
    id <XRLazyKVOResponder> _responder;
    BOOL _implementsWillChangeHandler;
    BOOL _suspended;
    NSArray *_runLoopModes;
    _XRLazyKVOBlockToken *_strongBlockAdapterToken;
}

+ (id)observeKeyPath:(id)arg1 object:(id)arg2 observer:(id)arg3 lazyUpdateBlock:(CDUnknownBlockType)arg4;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_callbackHandler;
- (void)clear;
- (void)dealloc;
- (void)fireCallbackContext:(const void *)arg1 whenKeypaths:(id)arg2 changeOnClass:(Class)arg3;
- (BOOL)hasContextChanged:(const void *)arg1;
- (id)init;
- (id)initWithLazyKVOResponder:(id)arg1;
@property(nonatomic, getter=isSuspended) BOOL suspended; // @synthesize suspended=_suspended;
- (void)observeObject:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObservationsForObject:(id)arg1;
@property(copy, nonatomic) NSArray *runLoopModes; // @synthesize runLoopModes=_runLoopModes;
@property(retain, nonatomic) _XRLazyKVOBlockToken *strongBlockAdapterToken; // @synthesize strongBlockAdapterToken=_strongBlockAdapterToken;

@end

