//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/PBXIndexEntry.h>

#import <DevToolsCore/PBXCompletionItem-Protocol.h>

@class NSObject, NSString;

@interface PBXSymbol : PBXIndexEntry <PBXCompletionItem>
{
    NSString *_cachedName;
    NSString *_cachedDeclaration;
    NSString *_cachedType;
    NSString *_cachedSourceFileName;
    NSObject *_cachedHelpMarker;
    long long _priority;
    unsigned int _type:6;
    unsigned int _isBeginUnused:1;
    unsigned int _usage:2;
    unsigned int _language:3;
    unsigned int _inProject:1;
    unsigned int _lineno:19;
    unsigned int _typeInfoInitialized:1;
    unsigned int _isCallablePointer:1;
    unsigned int _isBlockPointer:1;
    unsigned int _isConst:1;
}

+ (BOOL)_doesHelpMarkerStringExist:(id)arg1;
+ (id)_helpMarkerCStringStorage;
+ (id)_helpMarkerCStringStoragePath;
+ (id)_pathForHelpMarkerString:(id)arg1;
+ (BOOL)canRepresentSymbolType:(int)arg1;
+ (unsigned long long)offsetOfHelpMarker:(id)arg1;
+ (void)setAPIIndexDirectory:(id)arg1;
+ (Class)symbolClassForSymbolType:(int)arg1;
+ (id)symbolWithSymbolRecord:(struct _pbxsymrec *)arg1 projectIndex:(id)arg2 location:(union _pbxsymbollocation)arg3;
- (id)_complexTypeString:(BOOL)arg1 withParameterNames:(BOOL)arg2;
- (id)_fileReferenceForPath:(id)arg1;
- (void)_gatherTypeInfo;
- (id)_symbolsOfType:(int)arg1 inheritanceOnly:(BOOL)arg2 includingInherited:(BOOL)arg3 alreadyVisited:(id)arg4;
- (id)completionText;
- (id)containerSymbol;
- (id)correspondingSymbolForUsage:(int)arg1 preserveOriginalSymbolIfNoneFound:(BOOL)arg2;
- (id)counterpartSymbol;
- (void)dealloc;
- (id)declarationString;
- (id)declarationSymbol;
- (id)definitionSymbol;
- (id)description;
- (id)descriptionText;
- (BOOL)displayNameAllowsIndent;
- (id)displayNameIncludingClassInfo:(BOOL)arg1;
- (id)displayNameIncludingClassInfo:(BOOL)arg1 abbreviated:(BOOL)arg2 indented:(BOOL)arg3;
- (id)displayText;
- (id)displayType;
- (id)documentationBookmark;
- (id)documentationFileReference;
- (BOOL)hasDocumentation;
- (id)helpMarkerFilePath;
- (id)helpMarkerLanguageType;
- (id)helpMarkerString;
- (id)helpMarkerSymbolType;
- (id)helpMarkerSymbolValue;
- (id)icon;
- (id)initWithProjectIndex:(id)arg1 symbolRecord:(struct _pbxsymrec *)arg2 location:(union _pbxsymbollocation)arg3;
- (BOOL)isBlockPointer;
- (BOOL)isCallablePointer;
- (BOOL)isConst;
- (BOOL)isFunctionPointer;
- (BOOL)isInProject;
- (int)language;
- (unsigned long long)lineNumber;
- (id)name;
- (id)nameSpace;
- (id)parameterListSymbol;
- (long long)priority;
- (id)scopeOperator;
- (id)scopeSymbol;
- (void)setPriority:(long long)arg1;
- (id)simpleName;
- (id)sourceFileBookmark;
- (id)sourceFileBookmarkPreferUsage:(int)arg1;
- (BOOL)sourceFileExists;
- (id)sourceFileName;
- (id)sourceFileNameAndLineNumber;
- (id)sourceFilePath;
- (id)sourceFileReference;
- (struct _pbxsymrec *)symbolRecord;
- (int)symbolType;
- (id)symbolTypeName;
- (id)symbolsOfType:(int)arg1 includingInherited:(BOOL)arg2;
- (id)typeDescriptor;
- (id)typeString;
- (id)typeStringWithName:(BOOL)arg1 withParameterNames:(BOOL)arg2;
- (id)uniqueName;
- (int)usage;
- (int)visibility;

@end

