//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class PBXSourceLexer;

@interface PBXSourceScanner : NSObject
{
    PBXSourceLexer *_lexer;
}

- (void)dealloc;
- (void)initInterestingSymbols;
- (void)initSourceLexerForSpecification:(id)arg1;
- (id)initWithLanguageSpecification:(id)arg1;
- (id)lexer;
- (id)parse;
- (id)parseString:(id)arg1;

@end

