//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/SCMBasePathObject.h>

@class NSMutableArray, NSOperationQueue, NSString, SCMActivity, SCMNode, SCMRequest;

@interface SCMModel : SCMBasePathObject
{
    NSOperationQueue *_operationQueue;
    NSMutableArray *_runningRequests;
    NSString *_name;
    SCMActivity *_rootActivity;
    SCMNode *_root;
    SCMRequest *_finishedRequest;
    BOOL _busy;
    BOOL _disconnected;
}

+ (void)initialize;
+ (long long)runningCriticalRequests;
+ (long long)runningRequests;
+ (void)startPendingRequests;
- (void)addRunningRequest:(id)arg1;
- (void)blameOperation;
@property(readonly) BOOL busy; // @synthesize busy=_busy;
- (void)catOperation;
- (long long)compare:(id)arg1;
- (void)copyOperation;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)createRequestWithSelector:(SEL)arg1;
- (void)dealloc;
- (void)deleteOperation;
- (id)dictionaryRepresentation;
- (void)diffOperation;
- (void)disconnect;
@property BOOL disconnected; // @synthesize disconnected=_disconnected;
@property(retain) SCMRequest *finishedRequest; // @synthesize finishedRequest=_finishedRequest;
- (void)handleFinishedRequest:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithName:(id)arg1 path:(id)arg2;
- (void)lockOperation;
- (void)logOperation;
- (void)mkdirOperation;
- (void)moveOperation;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)path;
- (void)queueRequest:(id)arg1;
- (id)requestBlameForPath:(id)arg1 revision:(id)arg2;
- (id)requestCatForPath:(id)arg1 revision:(id)arg2;
- (id)requestCatForPath:(id)arg1 toPath:(id)arg2 revision:(id)arg3;
- (Class)requestClass;
- (id)requestCopyFromPaths:(id)arg1 toPaths:(id)arg2 revision:(id)arg3 withMessage:(id)arg4;
- (id)requestDeleteForPaths:(id)arg1 withMessage:(id)arg2;
- (id)requestDiffForPath:(id)arg1 revision:(id)arg2 secondRevision:(id)arg3;
- (id)requestLockForPaths:(id)arg1 withMessage:(id)arg2;
- (id)requestLogForPath:(id)arg1 getAll:(BOOL)arg2 revision:(id)arg3 secondRevision:(id)arg4;
- (id)requestMkdirForPaths:(id)arg1 withMessage:(id)arg2;
- (id)requestMoveFromPaths:(id)arg1 toPaths:(id)arg2 withMessage:(id)arg3;
- (id)requestUnlockForPaths:(id)arg1;
@property(retain) SCMNode *root; // @synthesize root=_root;
@property(retain) SCMActivity *rootActivity; // @synthesize rootActivity=_rootActivity;
- (void)setPath:(id)arg1;
- (void)startRequest:(id)arg1;
- (id)suddenTerminationClientName;
- (id)tempFileName:(id)arg1 forRevision:(id)arg2;
- (void)unlockOperation;

@end

