//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSString, SCMNode, SCMRequest, SCMRevision;

@protocol SCMSandboxProtocol
- (void)disconnect;
- (BOOL)disconnected;
- (NSString *)modelPathForAbsolutePath:(NSString *)arg1;
- (NSString *)path;
- (SCMRequest *)refreshAll;
- (SCMRequest *)requestAddForPaths:(NSArray *)arg1;
- (SCMRequest *)requestBlameForPath:(NSString *)arg1 revision:(SCMRevision *)arg2;
- (SCMRequest *)requestCatForPath:(NSString *)arg1 revision:(SCMRevision *)arg2;
- (SCMRequest *)requestClearTagsForPaths:(NSArray *)arg1;
- (SCMRequest *)requestCommitForPaths:(NSArray *)arg1 withMessage:(NSString *)arg2;
- (SCMRequest *)requestCopyFromPaths:(NSArray *)arg1 toPaths:(NSArray *)arg2 revision:(SCMRevision *)arg3 withMessage:(NSString *)arg4;
- (SCMRequest *)requestDeleteForPaths:(NSArray *)arg1;
- (SCMRequest *)requestDiffForPath:(NSString *)arg1 revision:(SCMRevision *)arg2 secondRevision:(SCMRevision *)arg3;
- (SCMRequest *)requestEditForPaths:(NSArray *)arg1;
- (SCMRequest *)requestLogForPath:(NSString *)arg1 getAll:(BOOL)arg2 revision:(SCMRevision *)arg3 secondRevision:(SCMRevision *)arg4;
- (SCMRequest *)requestMoveFromPaths:(NSArray *)arg1 toPaths:(NSArray *)arg2 withMessage:(NSString *)arg3;
- (SCMRequest *)requestResolveForPaths:(NSArray *)arg1;
- (SCMRequest *)requestRevertForPaths:(NSArray *)arg1;
- (SCMRequest *)requestStatusForPath:(NSString *)arg1 getAll:(BOOL)arg2 revision:(SCMRevision *)arg3;
- (SCMRequest *)requestUpdateForPaths:(NSArray *)arg1 revision:(SCMRevision *)arg2;
- (SCMNode *)root;
- (void)setDisconnected:(BOOL)arg1;
- (void)setRoot:(SCMNode *)arg1;
- (SCMRequest *)updateAll;
@end

