//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, XCPlatformSpecification, XCPropertyInfoContext, XCSDKPackage;
@protocol XCConfigurationInspectables;

@interface XCConfigurationInspectionContext : NSObject
{
    id <XCConfigurationInspectables> _inspectable;
    NSString *_configName;
    NSString *_baseDirectoryPath;
    XCPropertyInfoContext *_propertyInfoContext;
    XCSDKPackage *_sdkPackage;
    XCPlatformSpecification *_platform;
}

- (id)baseDirectoryPath;
- (id)configurationName;
- (void)dealloc;
- (id)description;
- (id)initWithInspectable:(id)arg1 forConfigurationNamed:(id)arg2 baseDirectoryPath:(id)arg3;
- (id)inspectable;
- (id)platform;
- (id)propertyInfoContext;
- (id)sdkPackage;
- (void)willBeDiscarded;

@end

