//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCore/XCDependencyShadowCommand.h>

@class NSString;

@interface XCGCCPreprocessingCommand : XCDependencyShadowCommand
{
    NSString *_outputFilePath;
}

- (void)dealloc;
- (id)initWithOriginalCommand:(id)arg1 outputFilePath:(id)arg2;
- (id)outputFilePath;
- (id)subprocessCommandLineForProcessing;

@end

