//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DevToolsCParsing/EntireProject.h>

@class NSDictionary, NSMutableDictionary, NSMutableSet, XCRefactoringTransformation;

@interface XCRefactoringParser : EntireProject
{
    XCRefactoringTransformation *_transformation;
    NSMutableSet *_compilationUnitsParsed;
    NSDictionary *_buildSettings;
    NSMutableDictionary *_editorCache;
}

- (BOOL)beginHeader:(id)arg1;
- (struct RefactoringCppActions *)cppCallbackFactory;
- (void)dealloc;
- (void)fakeCriticalDefinesForLanguage;
- (unsigned long long)fileLanguage;
- (void)finalize;
- (id)frameworkSearchPaths;
- (id)getStringAtFile:(id)arg1 line:(unsigned long long)arg2;
- (id)getStringAtLocation:(id)arg1;
- (id)getStringAtLocation:(id)arg1 replacing:(id)arg2;
- (id)initWithProject:(id)arg1 transformation:(id)arg2;
- (void *)inputStreamForCompilationUnit:(id)arg1;
- (id)memorySourceForFile:(const char *)arg1;
- (BOOL)parseCompilationUnitsAndSettings:(id)arg1;
- (BOOL)parseOneCompilationUnit:(id)arg1 buildSettings:(id)arg2;
- (id)predefinedMacroNamesAndDefs;
- (id)preincludeFiles;
- (void)releaseCompileResources;
- (void)setupCompileResources;
- (BOOL)shouldRegisterStandardIncludes;
- (id)systemIncludePaths;
- (id)undefinedMacroNames;

@end

