//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSCore/XCSCodeCoverageObject.h>

@class NSNumber, NSString, XCSCodeCoverageIntegration, XCSDevice;

@interface XCSCodeCoverageDevice : XCSCodeCoverageObject
{
    XCSCodeCoverageIntegration *_integration;
    XCSDevice *_device;
    NSString *_deviceTinyID;
}

- (void).cxx_destruct;
- (void)_bindHierarchyWithIntegration:(id)arg1 parentObject:(id)arg2;
- (id)_initWithDeviceTinyID:(id)arg1 skipValidation:(BOOL)arg2 skipBindHierarchy:(BOOL)arg3 validationErrors:(id *)arg4;
- (BOOL)_validateWithDeviceTinyID:(id)arg1 validationErrors:(id *)arg2;
- (id)ccifRepresentation;
- (id)ccimRepresentation;
@property(retain, nonatomic) XCSDevice *device; // @synthesize device=_device;
@property(copy, nonatomic) NSString *deviceTinyID; // @synthesize deviceTinyID=_deviceTinyID;
- (id)dictionaryRepresentation;
- (id)initWithContents:(id)arg1 service:(id)arg2 skipValidation:(BOOL)arg3 skipBindHierarchy:(BOOL)arg4 validationErrors:(id *)arg5;
- (id)initWithContents:(id)arg1 service:(id)arg2 validationErrors:(id *)arg3;
@property(nonatomic) __weak XCSCodeCoverageIntegration *integration; // @synthesize integration=_integration;
- (id)keyPath;
@property(readonly, nonatomic) NSNumber *lineCoveragePercentage;
- (id)saveRepresentation;
- (id)saveRepresentationHumanReadable:(BOOL)arg1;

@end

