//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <XCSCore/XCSObject.h>

@class NSArray, NSNumber, NSString, XCSTestResult;

@interface XCSPerfMetricTestResult : XCSObject
{
    BOOL _passed;
    NSString *name;
    unsigned long long type;
    NSString *unit;
    NSString *_identifier;
    double _avg;
    double _min;
    double _max;
    double _rsd;
    NSNumber *_baseline;
    double _maxPercentRegression;
    double _maxPercentRelativeStandardDeviation;
    NSArray *_iterations;
    XCSTestResult *_testResult;
    unsigned long long _deviceCount;
}

+ (id)perfMetricResultWithTestResult:(id)arg1 name:(id)arg2 identifier:(id)arg3 type:(unsigned long long)arg4 unit:(id)arg5 iterations:(id)arg6 baseline:(id)arg7 maxPercentRegression:(double)arg8 maxPercentRelativeStandardDeviation:(double)arg9 hasPassed:(BOOL)arg10 validationErrors:(id *)arg11;
- (void).cxx_destruct;
- (void)_setAverageMinMaxForPerfMetricWithIterations:(struct NSArray *)arg1;
- (void)_setRelativeStandardDeviationWithIterations:(struct NSArray *)arg1;
- (BOOL)_validateWithTestResult:(id)arg1 name:(id)arg2 identifier:(id)arg3 type:(unsigned long long)arg4 unit:(id)arg5 iterations:(id)arg6 baseline:(id)arg7 hasPassed:(BOOL)arg8 validationErrors:(id *)arg9;
@property(nonatomic) double avg; // @synthesize avg=_avg;
@property(retain, nonatomic) NSNumber *baseline; // @synthesize baseline=_baseline;
- (id)description;
@property(nonatomic) unsigned long long deviceCount; // @synthesize deviceCount=_deviceCount;
- (id)dictionaryRepresentation;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithTestResult:(id)arg1 name:(id)arg2 identifier:(id)arg3 type:(unsigned long long)arg4 unit:(id)arg5 iterations:(id)arg6 baseline:(id)arg7 maxPercentRegression:(double)arg8 maxRelativeStandardDeviation:(double)arg9 hasPassed:(BOOL)arg10 validationErrors:(id *)arg11;
@property(retain, nonatomic) NSArray *iterations; // @synthesize iterations=_iterations;
@property(nonatomic) double max; // @synthesize max=_max;
@property(nonatomic) double maxPercentRegression; // @synthesize maxPercentRegression=_maxPercentRegression;
@property(nonatomic) double maxPercentRelativeStandardDeviation; // @synthesize maxPercentRelativeStandardDeviation=_maxPercentRelativeStandardDeviation;
@property(nonatomic) double min; // @synthesize min=_min;
@property(copy, nonatomic) NSString *name; // @synthesize name;
@property(nonatomic) BOOL passed; // @synthesize passed=_passed;
@property(nonatomic) double rsd; // @synthesize rsd=_rsd;
- (id)saveRepresentation;
- (id)saveRepresentationHumanReadable:(BOOL)arg1;
@property(nonatomic) __weak XCSTestResult *testResult; // @synthesize testResult=_testResult;
@property(nonatomic) unsigned long long type; // @synthesize type;
@property(copy, nonatomic) NSString *unit; // @synthesize unit;

@end

