//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PhysicsKit/NSCoding-Protocol.h>

@class PKPhysicsBody;

@interface PKPhysicsJoint : NSObject <NSCoding>
{
    BOOL _inUse;
    BOOL _implicit;
    struct b2Joint *_baseJoint;
    PKPhysicsBody *_bodyA;
    PKPhysicsBody *_bodyB;
}

- (void).cxx_destruct;
- (BOOL)_implicit;
- (BOOL)_inUse;
@property(nonatomic) struct b2Joint *_joint;
@property(readonly, nonatomic) struct b2JointDef *_jointDef;
@property(retain, nonatomic) PKPhysicsBody *bodyA; // @synthesize bodyA=_bodyA;
@property(retain, nonatomic) PKPhysicsBody *bodyB; // @synthesize bodyB=_bodyB;
- (void)create;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(readonly, nonatomic) struct CGVector reactionForce;
@property(readonly, nonatomic) double reactionTorque;
- (void)set_implicit:(BOOL)arg1;
- (void)set_inUse:(BOOL)arg1;

@end

