//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 15 2018 10:31:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DTPlugInManager;

@interface DTExtensionPoint : NSObject
{
    id _extensionPointData;
    DTPlugInManager *_plugInManager;
    void *reserved[2];
}

- (id)_extensionPointDescription;
- (id)bundle;
- (id)childExtensionPoints;
- (void)dealloc;
- (id)extensionClassName;
- (id)extensionProtocolName;
- (id)extensionSchema;
- (id)identifier;
- (id)initWithExtensionPointDescription:(id)arg1 plugInManager:(id)arg2;
- (id)name;
- (id)parentExtensionPoint;
- (id)plugIn;
- (id)sharedExtensions;
- (id)version;

@end

